using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Farplane.FFX.Values
{
    public static class AutoAbility
    {
        public static AutoAbilityItem[] AutoAbilities =
        {
            new AutoAbilityItem {ID = 0x8000 + 123, Name="Aeon Immunities" },
            new AutoAbilityItem {ID = 0x8000 + 7, Name="Alchemy" },
            new AutoAbilityItem {ID = 0x8000 + 86, Name="Auto-Haste" },
            new AutoAbilityItem {ID = 0x8000 + 9, Name="Auto-Med" },
            new AutoAbilityItem {ID = 0x8000 + 10, Name="Auto-Phoenix" },
            new AutoAbilityItem {ID = 0x8000 + 8, Name="Auto-Potion" },
            new AutoAbilityItem {ID = 0x8000 + 85, Name="Auto-Protect" },
            new AutoAbilityItem {ID = 0x8000 + 88, Name="Auto-Reflect" },
            new AutoAbilityItem {ID = 0x8000 + 87, Name="Auto-Regen" },
            new AutoAbilityItem {ID = 0x8000 + 84, Name="Auto-Shell" },
            new AutoAbilityItem {ID = 0x8000 + 81, Name="Beserk Ward" },
            new AutoAbilityItem {ID = 0x8000 + 80, Name="Beserkproof" },
            new AutoAbilityItem {ID = 0x8000 + 25, Name="Break Damage Limit" },
            new AutoAbilityItem {ID = 0x8000 + 23, Name="Break HP Limit" },
            new AutoAbilityItem {ID = 0x8000 + 24, Name="Break MP Limit" },
            new AutoAbilityItem {ID = 0x8000 + 122, Name="Capture" },
            new AutoAbilityItem {ID = 0x8000 + 79, Name="Confuse Ward" },
            new AutoAbilityItem {ID = 0x8000 + 78, Name="Confuseproof" },
            new AutoAbilityItem {ID = 0x8000 + 3, Name="Counterattack" },
            new AutoAbilityItem {ID = 0x8000 + 83, Name="Curse Ward" },
            new AutoAbilityItem {ID = 0x8000 + 82, Name="Curseproof" },
            new AutoAbilityItem {ID = 0x8000 + 73, Name="Dark Ward" },
            new AutoAbilityItem {ID = 0x8000 + 72, Name="Darkproof" },
            new AutoAbilityItem {ID = 0x8000 + 70, Name="Darkstrike" },
            new AutoAbilityItem {ID = 0x8000 + 71, Name="Darktouch" },
            new AutoAbilityItem {ID = 0x8000 + 49, Name="Death Ward" },
            new AutoAbilityItem {ID = 0x8000 + 48, Name="Deathproof" },
            new AutoAbilityItem {ID = 0x8000 + 46, Name="Deathstrike" },
            new AutoAbilityItem {ID = 0x8000 + 47, Name="Deathtouch" },
            new AutoAbilityItem {ID = 0x8000 + 106, Name="Defense +3%" },
            new AutoAbilityItem {ID = 0x8000 + 107, Name="Defense +5%" },
            new AutoAbilityItem {ID = 0x8000 + 108, Name="Defense +10%" },
            new AutoAbilityItem {ID = 0x8000 + 109, Name="Defense +20%" },
            new AutoAbilityItem {ID = 0x807F, Name="Distill Ability" },
            new AutoAbilityItem {ID = 0x8000 + 125, Name="Distill Mana" },
            new AutoAbilityItem {ID = 0x8000 + 124, Name="Distill Power" },
            new AutoAbilityItem {ID = 0x8000 + 126, Name="Distill Speed" },
            new AutoAbilityItem {ID = 0x8000 + 18, Name="Double AP" },
            new AutoAbilityItem {ID = 0x8000 + 14, Name="Double Overdrive" },
            new AutoAbilityItem {ID = 0x8000 + 4, Name="Evade & Counter" },
            new AutoAbilityItem {ID = 0x8000 + 33, Name="Fire Eater" },
            new AutoAbilityItem {ID = 0x8000 + 31, Name="Fire Ward" },
            new AutoAbilityItem {ID = 0x8000 + 32, Name="Fireproof" },
            new AutoAbilityItem {ID = 0x8000 + 30, Name="Firestrike" },
            new AutoAbilityItem {ID = 0x8000 + 1, Name="First Strike" },
            new AutoAbilityItem {ID = 0x8000 + 26, Name="Gillionaire" },
            new AutoAbilityItem {ID = 0x8000 + 12, Name="Half MP Cost" },
            new AutoAbilityItem {ID = 0x8000 + 114, Name="HP +5%" },
            new AutoAbilityItem {ID = 0x8000 + 115, Name="HP +10%" },
            new AutoAbilityItem {ID = 0x8000 + 116, Name="HP +20%" },
            new AutoAbilityItem {ID = 0x8000 + 117, Name="HP +30%" },
            new AutoAbilityItem {ID = 0x8000 + 27, Name="HP Stroll" },
            new AutoAbilityItem {ID = 0x8000 + 37, Name="Ice Eater" },
            new AutoAbilityItem {ID = 0x8000 + 35, Name="Ice Ward" },
            new AutoAbilityItem {ID = 0x8000 + 36, Name="Iceproof" },
            new AutoAbilityItem {ID = 0x8000 + 34, Name="Icestrike" },
            new AutoAbilityItem {ID = 0x8000 + 2, Name="Initiative" },
            new AutoAbilityItem {ID = 0x8000 + 41, Name="Lightning Eater" },
            new AutoAbilityItem {ID = 0x8000 + 39, Name="Lightning Ward" },
            new AutoAbilityItem {ID = 0x8000 + 40, Name="Lightningproof" },
            new AutoAbilityItem {ID = 0x8000 + 38, Name="Lightningstrike" },
            new AutoAbilityItem {ID = 0x8000 + 102, Name="Magic +3%" },
            new AutoAbilityItem {ID = 0x8000 + 103, Name="Magic +5%" },
            new AutoAbilityItem {ID = 0x8000 + 104, Name="Magic +10%" },
            new AutoAbilityItem {ID = 0x8000 + 105, Name="Magic +20%" },
            new AutoAbilityItem {ID = 0x8000 + 6, Name="Magic Booster" },
            new AutoAbilityItem {ID = 0x8000 + 5, Name="Magic Counter" },
            new AutoAbilityItem {ID = 0x8000 + 110, Name="Magic Def +3%" },
            new AutoAbilityItem {ID = 0x8000 + 111, Name="Magic Def +5%" },
            new AutoAbilityItem {ID = 0x8000 + 112, Name="Magic Def +10%" },
            new AutoAbilityItem {ID = 0x8000 + 113, Name="Magic Def +20%" },
            new AutoAbilityItem {ID = 0x8000 + 22, Name="Master Thief" },
            new AutoAbilityItem {ID = 0x8000 + 118, Name="MP +5%" },
            new AutoAbilityItem {ID = 0x8000 + 119, Name="MP +10%" },
            new AutoAbilityItem {ID = 0x8000 + 120, Name="MP +20%" },
            new AutoAbilityItem {ID = 0x8000 + 121, Name="MP +30%" },
            new AutoAbilityItem {ID = 0x8000 + 28, Name="MP Stroll" },
            new AutoAbilityItem {ID = 0x8000 + 20, Name="No AP" },
            new AutoAbilityItem {ID = 0x8000 + 29, Name="No Encounters" },
            new AutoAbilityItem {ID = 0x8000 + 13, Name="One MP Cost" },
            new AutoAbilityItem {ID = 0x8000 + 17, Name="Overdrive ? AP" },
            new AutoAbilityItem {ID = 0x8000 + 21, Name="Pickpocket" },
            new AutoAbilityItem {ID = 0x8000 + 11, Name="Piercing" },
            new AutoAbilityItem {ID = 0x8000 + 61, Name="Poison Ward" },
            new AutoAbilityItem {ID = 0x8000 + 60, Name="Poisonproof" },
            new AutoAbilityItem {ID = 0x8000 + 58, Name="Poisonstrike" },
            new AutoAbilityItem {ID = 0x8000 + 59, Name="Poisontouch" },
            new AutoAbilityItem {ID = 0x8080, Name="Sensor" },
            new AutoAbilityItem {ID = 0x8000 + 69, Name="Silence Ward" },
            new AutoAbilityItem {ID = 0x8000 + 68, Name="Silenceproof" },
            new AutoAbilityItem {ID = 0x8000 + 66, Name="Silencestrike" },
            new AutoAbilityItem {ID = 0x8000 + 67, Name="Silencetouch" },
            new AutoAbilityItem {ID = 0x8000 + 65, Name="Sleep Ward" },
            new AutoAbilityItem {ID = 0x8000 + 64, Name="Sleepproof" },
            new AutoAbilityItem {ID = 0x8000 + 62, Name="Sleepstrike" },
            new AutoAbilityItem {ID = 0x8000 + 63, Name="Sleeptouch" },
            new AutoAbilityItem {ID = 0x8000 + 77, Name="Slow Ward" },
            new AutoAbilityItem {ID = 0x8000 + 76, Name="Slowproof" },
            new AutoAbilityItem {ID = 0x8000 + 74, Name="Slowstrike" },
            new AutoAbilityItem {ID = 0x8000 + 75, Name="Slowtouch" },
            new AutoAbilityItem {ID = 0x8000 + 91, Name="SOS Haste" },
            new AutoAbilityItem {ID = 0x8000 + 97, Name="SOS NulBlaze" },
            new AutoAbilityItem {ID = 0x8000 + 95, Name="SOS NulFrost" },
            new AutoAbilityItem {ID = 0x8000 + 96, Name="SOS NulShock" },
            new AutoAbilityItem {ID = 0x8000 + 94, Name="SOS NulTide" },
            new AutoAbilityItem {ID = 0x8000 + 16, Name="SOS Overdrive" },
            new AutoAbilityItem {ID = 0x8000 + 90, Name="SOS Protect" },
            new AutoAbilityItem {ID = 0x8000 + 93, Name="SOS Reflect" },
            new AutoAbilityItem {ID = 0x8000 + 92, Name="SOS Regen" },
            new AutoAbilityItem {ID = 0x8000 + 89, Name="SOS Shell" },
            new AutoAbilityItem {ID = 0x8000 + 57, Name="Stone Ward" },
            new AutoAbilityItem {ID = 0x8000 + 56, Name="Stoneproof" },
            new AutoAbilityItem {ID = 0x8000 + 54, Name="Stonestrike" },
            new AutoAbilityItem {ID = 0x8000 + 55, Name="Stonetouch" },
            new AutoAbilityItem {ID = 0x8000 + 98, Name="Strength +3%" },
            new AutoAbilityItem {ID = 0x8000 + 99, Name="Strength +5%" },
            new AutoAbilityItem {ID = 0x8000 + 100, Name="Strength +10%" },
            new AutoAbilityItem {ID = 0x8000 + 101, Name="Strength +20%" },
            new AutoAbilityItem {ID = 0x8000 + 19, Name="Triple AP" },
            new AutoAbilityItem {ID = 0x8000 + 15, Name="Triple Overdrive" },
            new AutoAbilityItem {ID = 0x8000 + 45, Name="Water Eater" },
            new AutoAbilityItem {ID = 0x8000 + 43, Name="Water Ward" },
            new AutoAbilityItem {ID = 0x8000 + 44, Name="Waterproof" },
            new AutoAbilityItem {ID = 0x8000 + 42, Name="Waterstrike" },
            new AutoAbilityItem {ID = 0x8000 + 53, Name="Zombie Ward" },
            new AutoAbilityItem {ID = 0x8000 + 52, Name="Zombieproof" },
            new AutoAbilityItem {ID = 0x8000 + 50, Name="Zombiestrike" },
            new AutoAbilityItem {ID = 0x8000 + 51, Name="Zombietouch" },
        };


        public static AutoAbilityItem FromID(int abilityID)
        {
            return AutoAbilities.FirstOrDefault(a => a.ID == abilityID);
        }
    }

    public class AutoAbilityItem
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}
