using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using Farplane.Memory;

namespace Farplane.FFX.Values
{
    public class BlitzballValues
    {
        public static BlitzballValue[] Players =
        {
            new BlitzballValue {Index = 0, Name = "Tidus"},
            new BlitzballValue {Index = 1, Name = "Wakka"},
            new BlitzballValue {Index = 2, Name = "Datto"},
            new BlitzballValue {Index = 3, Name = "Letty"},
            new BlitzballValue {Index = 4, Name = "Jassu"},
            new BlitzballValue {Index = 5, Name = "Botta"},
            new BlitzballValue {Index = 6, Name = "Keepa"},
            new BlitzballValue {Index = 7, Name = "Bickson"},
            new BlitzballValue {Index = 8, Name = "Abus"},
            new BlitzballValue {Index = 9, Name = "Graav"},
            new BlitzballValue {Index = 10, Name = "Doram"},
            new BlitzballValue {Index = 11, Name = "Balgerda"},
            new BlitzballValue {Index = 12, Name = "Raudy"},
            new BlitzballValue {Index = 13, Name = "Larbeight"},
            new BlitzballValue {Index = 14, Name = "Isken"},
            new BlitzballValue {Index = 15, Name = "Vuroja"},
            new BlitzballValue {Index = 16, Name = "Kulukan"},
            new BlitzballValue {Index = 17, Name = "Deim"},
            new BlitzballValue {Index = 18, Name = "Nizarut"},
            new BlitzballValue {Index = 19, Name = "Eigaar"},
            new BlitzballValue {Index = 20, Name = "Blappa"},
            new BlitzballValue {Index = 21, Name = "Berrik"},
            new BlitzballValue {Index = 22, Name = "Judda"},
            new BlitzballValue {Index = 23, Name = "Lakkam"},
            new BlitzballValue {Index = 24, Name = "Nimrook"},
            new BlitzballValue {Index = 25, Name = "Basik Ronso"},
            new BlitzballValue {Index = 26, Name = "Argai Ronso"},
            new BlitzballValue {Index = 27, Name = "Gazna Ronso"},
            new BlitzballValue {Index = 28, Name = "Nuvy Ronso"},
            new BlitzballValue {Index = 29, Name = "Irga Ronso"},
            new BlitzballValue {Index = 30, Name = "Zamzi Ronso"},
            new BlitzballValue {Index = 31, Name = "Giera Guado"},
            new BlitzballValue {Index = 32, Name = "Zazi Guado"},
            new BlitzballValue {Index = 33, Name = "Nav Guado"},
            new BlitzballValue {Index = 34, Name = "Auda Guado"},
            new BlitzballValue {Index = 35, Name = "Pah Guado"},
            new BlitzballValue {Index = 36, Name = "Noy Guado"},
            new BlitzballValue {Index = 37, Name = "Rin"},
            new BlitzballValue {Index = 38, Name = "Tatts"},
            new BlitzballValue {Index = 39, Name = "Kyou"},
            new BlitzballValue {Index = 40, Name = "Shuu"},
            new BlitzballValue {Index = 41, Name = "Nedus"},
            new BlitzballValue {Index = 42, Name = "Biggs"},
            new BlitzballValue {Index = 43, Name = "Wedge"},
            new BlitzballValue {Index = 44, Name = "Ropp"},
            new BlitzballValue {Index = 45, Name = "Linna"},
            new BlitzballValue {Index = 46, Name = "Mep"},
            new BlitzballValue {Index = 47, Name = "Zalitz"},
            new BlitzballValue {Index = 48, Name = "Naida"},
            new BlitzballValue {Index = 49, Name = "Durren"},
            new BlitzballValue {Index = 50, Name = "Jumal"},
            new BlitzballValue {Index = 51, Name = "Svanda"},
            new BlitzballValue {Index = 52, Name = "Vilucha"},
            new BlitzballValue {Index = 53, Name = "Shaami"},
            new BlitzballValue {Index = 54, Name = "Zev Ronso"},
            new BlitzballValue {Index = 55, Name = "Yuma Guado"},
            new BlitzballValue {Index = 56, Name = "Kiyuri"},
            new BlitzballValue {Index = 57, Name = "Brother"},
            new BlitzballValue {Index = 58, Name = "Mifurey"},
            new BlitzballValue {Index = 59, Name = "Miyu"},
        };

        public static BlitzballValue[] Teams =
        {
            new BlitzballValue {Index = 0, Name = "Luca Goers"},
            new BlitzballValue {Index = 1, Name = "Kilika Beasts"},
            new BlitzballValue {Index = 2, Name = "Al Bhed Psyches"},
            new BlitzballValue {Index = 3, Name = "Ronso Fangs"},
            new BlitzballValue {Index = 4, Name = "Guado Glories"},
            new BlitzballValue {Index = 5, Name = "Besaid Aurochs"},
            new BlitzballValue {Index = 0x1D, Name = "No Team"},
        };

        public static BlitzballValue[] Techs =
        {
            new BlitzballValue {Index = 1, Name = "Jecht Shot"},
            new BlitzballValue {Index = 2, Name = "Jecht Shot 2"},
            new BlitzballValue {Index = 3, Name = "Sphere Shot"},
            new BlitzballValue {Index = 4, Name = "Invisible Shot"},
            new BlitzballValue {Index = 5, Name = "Venom Shot"},
            new BlitzballValue {Index = 6, Name = "Venom Shot 2"},
            new BlitzballValue {Index = 7, Name = "Venom Shot 3"},
            new BlitzballValue {Index = 8, Name = "Nap Shot"},
            new BlitzballValue {Index = 9, Name = "Nap Shot 2"},
            new BlitzballValue {Index = 10, Name = "Nap Shot 3"},
            new BlitzballValue {Index = 11, Name = "Wither Shot"},
            new BlitzballValue {Index = 12, Name = "Wither Shot 2"},
            new BlitzballValue {Index = 13, Name = "Wither Shot 3"},
            new BlitzballValue {Index = 14, Name = "Venom Pass"},
            new BlitzballValue {Index = 15, Name = "Venom Pass 2"},
            new BlitzballValue {Index = 16, Name = "Venom Pass 3"},
            new BlitzballValue {Index = 17, Name = "Nap Pass"},
            new BlitzballValue {Index = 18, Name = "Nap Pass 2"},
            new BlitzballValue {Index = 19, Name = "Nap Pass 3"},
            new BlitzballValue {Index = 20, Name = "Wither Pass"},
            new BlitzballValue {Index = 21, Name = "Wither Pass 2"},
            new BlitzballValue {Index = 22, Name = "Wither Pass 3"},
            new BlitzballValue {Index = 23, Name = "Volley Shot"},
            new BlitzballValue {Index = 24, Name = "Volley Shot 2"},
            new BlitzballValue {Index = 25, Name = "Volley Shot 3"},
            new BlitzballValue {Index = 26, Name = "Venom Tackle"},
            new BlitzballValue {Index = 27, Name = "Venom Tackle 2"},
            new BlitzballValue {Index = 28, Name = "Venom Tackle 3"},
            new BlitzballValue {Index = 29, Name = "Nap Tackle"},
            new BlitzballValue {Index = 30, Name = "Nap Tackle 2"},
            new BlitzballValue {Index = 31, Name = "Nap Tackle 3"},
            new BlitzballValue {Index = 32, Name = "Wither Tackle"},
            new BlitzballValue {Index = 33, Name = "Wither Tackle 2"},
            new BlitzballValue {Index = 34, Name = "Wither Tackle 3"},
            new BlitzballValue {Index = 35, Name = "Drain Tackle"},
            new BlitzballValue {Index = 36, Name = "Drain Tackle 2"},
            new BlitzballValue {Index = 37, Name = "Drain Tackle 3"},
            new BlitzballValue {Index = 38, Name = "Tackle Slip"},
            new BlitzballValue {Index = 39, Name = "Tackle Slip 2"},
            new BlitzballValue {Index = 40, Name = "Anti-Venom"},
            new BlitzballValue {Index = 41, Name = "Anti-Venom 2"},
            new BlitzballValue {Index = 42, Name = "Anti-Nap"},
            new BlitzballValue {Index = 43, Name = "Anti-Nap 2"},
            new BlitzballValue {Index = 44, Name = "Anti-Wither"},
            new BlitzballValue {Index = 45, Name = "Anti-Wither 2"},
            new BlitzballValue {Index = 46, Name = "Anti-Drain"},
            new BlitzballValue {Index = 47, Name = "Anti-Drain 2"},
            new BlitzballValue {Index = 48, Name = "Spin Ball"},
            new BlitzballValue {Index = 49, Name = "Grip Gloves"},
            new BlitzballValue {Index = 50, Name = "Elite Defense"},
            new BlitzballValue {Index = 51, Name = "Brawler"},
            new BlitzballValue {Index = 52, Name = "Pile Venom"},
            new BlitzballValue {Index = 53, Name = "Pile Wither"},
            new BlitzballValue {Index = 54, Name = "Regen"},
            new BlitzballValue {Index = 55, Name = "Good Morning!"},
            new BlitzballValue {Index = 56, Name = "Hi-Risk"},
            new BlitzballValue {Index = 57, Name = "Golden Arm"},
            new BlitzballValue {Index = 58, Name = "Gamble"},
            new BlitzballValue {Index = 59, Name = "Super Goalie"},
            new BlitzballValue {Index = 60, Name = "Aurochs Spirit"},
        };

        public static BlitzballValue[] Prizes =
        {
            new BlitzballValue {Index = 0, Name = "Hi-Potion"},
            new BlitzballValue {Index = 1, Name = "Dark Matter"},
            new BlitzballValue {Index = 2, Name = "Teleport Sphere"},
            new BlitzballValue {Index = 3, Name = "Three Stars"},
            new BlitzballValue {Index = 4, Name = "Luck Sphere"},
            new BlitzballValue {Index = 5, Name = "Underdog's Secret"},
            new BlitzballValue {Index = 6, Name = "Megalixir"},
            new BlitzballValue {Index = 7, Name = "Return Sphere"},
            new BlitzballValue {Index = 8, Name = "Lv. 1 Key Sphere"},
            new BlitzballValue {Index = 9, Name = "Mega Phoenix"},
            new BlitzballValue {Index = 10, Name = "Elixir"},
            new BlitzballValue {Index = 11, Name = "Mega-Potion"},
            new BlitzballValue {Index = 12, Name = "X-Potion"},
            new BlitzballValue {Index = 13, Name = "Ether"},
            new BlitzballValue {Index = 14, Name = "Remedy"},
            new BlitzballValue {Index = 15, Name = "Phoenix Down"},
            new BlitzballValue {Index = 16, Name = "Hi-Potion"},
            new BlitzballValue {Index = 17, Name = "Power Sphere"},
            new BlitzballValue {Index = 18, Name = "Mana Sphere"},
            new BlitzballValue {Index = 19, Name = "Speed Sphere"},
            new BlitzballValue {Index = 20, Name = "Ability Sphere"},
            new BlitzballValue {Index = 21, Name = "Echo Screen"},
            new BlitzballValue {Index = 22, Name = "Eye Drops"},
            new BlitzballValue {Index = 23, Name = "Antidote"},
            new BlitzballValue {Index = 24, Name = "Jupiter Sigil"},
            new BlitzballValue {Index = 25, Name = "Elixir"},
            new BlitzballValue {Index = 26, Name = "X-Potion"},
            new BlitzballValue {Index = 27, Name = "Remedy"},
            new BlitzballValue {Index = 28, Name = "Hi-Potion"},
            new BlitzballValue {Index = 29, Name = "Echo Screen"},
            new BlitzballValue {Index = 30, Name = "Eye Drops"},
            new BlitzballValue {Index = 31, Name = "Antidote"},
            new BlitzballValue {Index = 32, Name = "Soft"},
            new BlitzballValue {Index = 33, Name = "Potion"},
            new BlitzballValue {Index = 34, Name = "Phoenix Down"},
            new BlitzballValue {Index = 35, Name = "Potion"},
            new BlitzballValue {Index = 36, Name = "Phoenix Down"},
            new BlitzballValue {Index = 37, Name = "Hi-Potion"},
            new BlitzballValue {Index = 38, Name = "Hi-Potion"},
            new BlitzballValue {Index = 39, Name = "Potion"},
            new BlitzballValue {Index = 40, Name = "Phoenix Down"},
            new BlitzballValue {Index = 41, Name = "Return Sphere"},
            new BlitzballValue {Index = 42, Name = "Rename Card"},
            new BlitzballValue {Index = 43, Name = "Ether"},
            new BlitzballValue {Index = 44, Name = "X-Potion"},
            new BlitzballValue {Index = 45, Name = "Mega-Potion"},
            new BlitzballValue {Index = 46, Name = "Remedy"},
            new BlitzballValue {Index = 47, Name = "Sun Crest"},
            new BlitzballValue {Index = 48, Name = "Moon Crest"},
            new BlitzballValue {Index = 49, Name = "Mars Crest"},
            new BlitzballValue {Index = 50, Name = "Saturn Crest"},
            new BlitzballValue {Index = 51, Name = "Jupiter Crest"},
            new BlitzballValue {Index = 52, Name = "Venus Crest"},
            new BlitzballValue {Index = 53, Name = "Mercury Crest"},
            new BlitzballValue {Index = 54, Name = "Sun Sigil"},
            new BlitzballValue {Index = 55, Name = "Moon Sigil"},
            new BlitzballValue {Index = 56, Name = "Mars Sigil"},
            new BlitzballValue {Index = 57, Name = "Saturn Sigil"},
            new BlitzballValue {Index = 58, Name = "Venus Sigil"},
            new BlitzballValue {Index = 59, Name = "Mercury Sigil"},
            new BlitzballValue {Index = 60, Name = "Megalixir"},
            new BlitzballValue {Index = 61, Name = "Elixir"},
            new BlitzballValue {Index = 62, Name = "Hi-Potion"},
            new BlitzballValue {Index = 63, Name = "Potion"},
            new BlitzballValue {Index = 64, Name = "Potion"},
            new BlitzballValue {Index = 65, Name = ""},
            new BlitzballValue {Index = 66, Name = "Remedy"},
            new BlitzballValue {Index = 67, Name = "Seeker's Ring"},
            new BlitzballValue {Index = 68, Name = "Phoenix Down"},
            new BlitzballValue {Index = 69, Name = ""},
            new BlitzballValue {Index = 70, Name = "Ether"},
            new BlitzballValue {Index = 71, Name = "Antidote"},
            new BlitzballValue {Index = 72, Name = "Elixir"},
            new BlitzballValue {Index = 73, Name = "Remedy"},
            new BlitzballValue {Index = 74, Name = "Phoenix Down"},
            new BlitzballValue {Index = 75, Name = "Hi-Potion"},
            new BlitzballValue {Index = 76, Name = "Potion"},
            new BlitzballValue {Index = 77, Name = "Variable Steel"},
            new BlitzballValue {Index = 78, Name = "Soft Ring"},
            new BlitzballValue {Index = 79, Name = "Hi-Potion"},
            new BlitzballValue {Index = 80, Name = "Ether"},
            new BlitzballValue {Index = 81, Name = "Mega-Potion"},
            new BlitzballValue {Index = 82, Name = "Halberd"},
            new BlitzballValue {Index = 83, Name = "Potion"},
            new BlitzballValue {Index = 84, Name = "Hi-Potion"},
            new BlitzballValue {Index = 85, Name = ""},
            new BlitzballValue {Index = 86, Name = "Elixir"},
            new BlitzballValue {Index = 87, Name = "Ether"},
            new BlitzballValue {Index = 88, Name = "Hi-Potion"},
            new BlitzballValue {Index = 89, Name = "Hunter's Spear"},
            new BlitzballValue {Index = 90, Name = "Antidote"},
            new BlitzballValue {Index = 91, Name = "Hi-Potion"},
            new BlitzballValue {Index = 92, Name = "Soft"},
            new BlitzballValue {Index = 93, Name = "Red Ring"},
            new BlitzballValue {Index = 94, Name = "Ether"},
            new BlitzballValue {Index = 95, Name = "Hi-Potion"},
            new BlitzballValue {Index = 96, Name = ""},
            new BlitzballValue {Index = 97, Name = "Lv. 1 Key Sphere"},
            new BlitzballValue {Index = 98, Name = "Antidote"},
            new BlitzballValue {Index = 99, Name = "Tough Bangle"},
            new BlitzballValue {Index = 100, Name = "Phoenix Down"},
            new BlitzballValue {Index = 101, Name = "Jecht Shot"},
            new BlitzballValue {Index = 102, Name = "Jecht Shot 2"},
            new BlitzballValue {Index = 103, Name = "Sphere Shot"},
            new BlitzballValue {Index = 104, Name = "Invisible Shot"},
            new BlitzballValue {Index = 105, Name = "Venom Shot"},
            new BlitzballValue {Index = 106, Name = "Venom Shot 2"},
            new BlitzballValue {Index = 107, Name = "Venom Shot 3"},
            new BlitzballValue {Index = 108, Name = "Nap Shot"},
            new BlitzballValue {Index = 109, Name = "Nap Shot 2"},
            new BlitzballValue {Index = 110, Name = "Nap Shot 3"},
            new BlitzballValue {Index = 111, Name = "Wither Shot"},
            new BlitzballValue {Index = 112, Name = "Wither Shot 2"},
            new BlitzballValue {Index = 113, Name = "Wither Shot 3"},
            new BlitzballValue {Index = 114, Name = "Venom Pass"},
            new BlitzballValue {Index = 115, Name = "Venom Pass 2"},
            new BlitzballValue {Index = 116, Name = "Venom Pass 3"},
            new BlitzballValue {Index = 117, Name = "Nap Pass"},
            new BlitzballValue {Index = 118, Name = "Nap Pass 2"},
            new BlitzballValue {Index = 119, Name = "Nap Pass 3"},
            new BlitzballValue {Index = 120, Name = "Wither Pass"},
            new BlitzballValue {Index = 121, Name = "Wither Pass 2"},
            new BlitzballValue {Index = 122, Name = "Wither Pass 3"},
            new BlitzballValue {Index = 123, Name = "Volley Shot"},
            new BlitzballValue {Index = 124, Name = "Volley Shot 2"},
            new BlitzballValue {Index = 125, Name = "Volley Shot 3"},
            new BlitzballValue {Index = 126, Name = "Venom Tackle"},
            new BlitzballValue {Index = 127, Name = "Venom Tackle 2"},
            new BlitzballValue {Index = 128, Name = "Venom Tackle 3"},
            new BlitzballValue {Index = 129, Name = "Nap Tackle"},
            new BlitzballValue {Index = 130, Name = "Nap Tackle 2"},
            new BlitzballValue {Index = 131, Name = "Nap Tackle 3"},
            new BlitzballValue {Index = 132, Name = "Wither Tackle"},
            new BlitzballValue {Index = 133, Name = "Wither Tackle 2"},
            new BlitzballValue {Index = 134, Name = "Wither Tackle 3"},
            new BlitzballValue {Index = 135, Name = "Drain Tackle"},
            new BlitzballValue {Index = 136, Name = "Drain Tackle 2"},
            new BlitzballValue {Index = 137, Name = "Drain Tackle 3"},
            new BlitzballValue {Index = 138, Name = "Tackle Slip"},
            new BlitzballValue {Index = 139, Name = "Tackle Slip 2"},
            new BlitzballValue {Index = 140, Name = "Anti-Venom"},
            new BlitzballValue {Index = 141, Name = "Anti-Venom 2"},
            new BlitzballValue {Index = 142, Name = "Anti-Nap"},
            new BlitzballValue {Index = 143, Name = "Anti-Nap 2"},
            new BlitzballValue {Index = 144, Name = "Anti-Wither"},
            new BlitzballValue {Index = 145, Name = "Anti-Wither 2"},
            new BlitzballValue {Index = 146, Name = "Anti-Drain"},
            new BlitzballValue {Index = 147, Name = "Anti-Drain 2"},
            new BlitzballValue {Index = 148, Name = "Spin Ball"},
            new BlitzballValue {Index = 149, Name = "Grip Gloves"},
            new BlitzballValue {Index = 150, Name = "Elite Defense"},
            new BlitzballValue {Index = 151, Name = "Brawler"},
            new BlitzballValue {Index = 152, Name = "Pile Venom"},
            new BlitzballValue {Index = 153, Name = "Pile Wither"},
            new BlitzballValue {Index = 154, Name = "Regen"},
            new BlitzballValue {Index = 155, Name = "Good Morning!"},
            new BlitzballValue {Index = 156, Name = "Hi-Risk"},
            new BlitzballValue {Index = 157, Name = "Golden Arm"},
            new BlitzballValue {Index = 158, Name = "Gamble"},
            new BlitzballValue {Index = 159, Name = "Super Goalie"},
            new BlitzballValue {Index = 160, Name = "Aurochs Spirit"},
            new BlitzballValue {Index = 161, Name = "Normal"},
            new BlitzballValue {Index = 162, Name = "Counter"},
            new BlitzballValue {Index = 163, Name = "Center Attack"},
            new BlitzballValue {Index = 164, Name = "Normal"},
            new BlitzballValue {Index = 165, Name = "Right Side"},
            new BlitzballValue {Index = 166, Name = "Left Side"},
            new BlitzballValue {Index = 167, Name = "Flat Line"},
            new BlitzballValue {Index = 168, Name = "Double Sides"},
            new BlitzballValue {Index = 169, Name = "All-Out Defense"},
            new BlitzballValue {Index = 170, Name = "Mark Mode"},
            new BlitzballValue {Index = 286, Name = "Tech Find"},
            new BlitzballValue {Index = 287, Name = "Attack Reels"},
            new BlitzballValue {Index = 288, Name = "Status Reels"},
            new BlitzballValue {Index = 289, Name = "Aurochs Reels"},
        };

        public static BlitzballValue[] TournamentStates =
        {
            new BlitzballValue() {Index = 0x00, Name = "No Data"},
            new BlitzballValue() {Index = 0x01, Name = "No Tournament"},
            new BlitzballValue() {Index = 0x02, Name = "No Tournament"},
            new BlitzballValue() {Index = 0x03, Name = "No Tournament"},
            new BlitzballValue() {Index = 0x04, Name = "New Tournament"},
            new BlitzballValue() {Index = 0x05, Name = "New Tournament"},
            new BlitzballValue() {Index = 0x06, Name = "New Tournament"},
            new BlitzballValue() {Index = 0x14, Name = "Round 1"},
            new BlitzballValue() {Index = 0x15, Name = "Round 2"},
            new BlitzballValue() {Index = 0x16, Name = "Round 3"},
        };

        public static BlitzballValue[] LeagueStates =
        {
            new BlitzballValue() {Index = 0x00, Name = "Round 1"},
            new BlitzballValue() {Index = 0x01, Name = "Round 2"},
            new BlitzballValue() {Index = 0x02, Name = "Round 3"},
            new BlitzballValue() {Index = 0x03, Name = "Round 4"},
            new BlitzballValue() {Index = 0x04, Name = "Round 5"},
            new BlitzballValue() {Index = 0x05, Name = "Round 6"},
            new BlitzballValue() {Index = 0x06, Name = "Round 7"},
            new BlitzballValue() {Index = 0x07, Name = "Round 8"},
            new BlitzballValue() {Index = 0x08, Name = "Round 9"},
            new BlitzballValue() {Index = 0x09, Name = "Round 10"},
            new BlitzballValue() {Index = 0x64, Name = "Round 10"},
            new BlitzballValue() {Index = 0x0a, Name = "New Season"},
        };
    }

    public class BlitzballValue
    {
        public int Index { get; set; }
        public string Name { get; set; }
    }
}