using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Farplane.FFX.Values
{
    public static class WeaponName
    {
        public static string[][] WeaponNames =
        {
            new string[]
            {
                "Caladbolg",
                "Brotherhood",
                "Taming Sword",
                "Crystal Sword",
                "Excalibur",
                "Ragnarok",
                "Balmung",
                "Save the Queen",
                "Heartbreaker",
                "Lionheart",
                "Durandal",
                "Ascalon",
                "Ambitious",
                "Hrunting",
                "Longsword",
                "Astral Sword",
                "Apocalypse",
                "Longsword",
                "Longsword",
                "Master Sword",
                "Runemaster",
                "Warlock",
                "Arc Sword",
                "Gilventure",
                "Tri-Steel",
                "Helter-Skelter",
                "Vendetta",
                "Avenger",
                "P-Steel",
                "M-Steel",
                "S-Steel",
                "A-Steel",
                "Prism Steel",
                "Mirage Sword",
                "Lifesaver",
                "Sonic Steel",
                "Vigilante",
                "Dance Macabre",
                "Largamente",
                "Gravestone",
                "Sidewinder",
                "Nightmare",
                "Mage Masher",
                "Nightbringer",
                "Knight Sword",
                "Wizard Sword",
                "Double-Edge",
                "Razzmatazz",
                "Deathbringer",
                "Stunning Steel",
                "Basilisk Steel",
                "Poison Steel",
                "Lullaby Steel",
                "Muted Steel",
                "Twilight Steel",
                "Hunter's Sword",
                "Flametongue",
                "Ice Brand",
                "Lightning Steel",
                "Liquid Steel",
                "Variable Steel",
                "Force Saber",
                "Baroque Sword",
                "Sorcery Sword",
                "Soldier's Saber",
                "Rune Steel",
                "Enchanted Sword",
                "Fencing Saber",
                "Warrior's Sword",
                "Slasher",
                "Longsword",
                "Longsword",
                "Longsword",
                "Longsword",
                "Endless Road",
                "Genji Shield",
                "Emblem",
                "Crystal Shield",
                "Aegis Shield",
                "Golem Shield",
                "Revive Shield",
                "Rescue Shield",
                "Paladin Shield",
                "Diamond Shield",
                "Ruby Shield",
                "Dynasty Shield",
                "Magister Shield",
                "Collector's Shield",
                "Treasure Shield",
                "Shield of Hope",
                "Assault Shield",
                "Phantom Shield",
                "Recovery Shield",
                "Spiritual Shield",
                "Phoenix Shield",
                "Curative Shield",
                "Rainbow Shield",
                "Shining Shield",
                "Faerie Shield",
                "Peaceful Shield",
                "Shaman Shield",
                "Barrier Shield",
                "Star Shield",
                "Marching Shield",
                "Moon Shield",
                "Regen Shield",
                "Haste Shield",
                "Reflect Shield",
                "Shell Shield",
                "Protect Shield",
                "Buckler",
                "Platinum Shield",
                "Sapphire Shield",
                "Knight's Shield",
                "Wizard Shield",
                "Elemental Shield",
                "Defending Shield",
                "Crimson Shield",
                "Snow Shield",
                "Ochre Shield",
                "Cerulean Shield",
                "Medical Shield",
                "Lucid Shield",
                "Serene Shield",
                "Light Shield",
                "Soul Shield",
                "Blessed Shield",
                "Soft Shield",
                "Serum Shield",
                "Alert Shield",
                "Echo Shield",
                "Bright Shield",
                "Red Shield",
                "White Shield",
                "Yellow Shield",
                "Blue Shield",
                "NulTide Shield",
                "NulBlaze Shield",
                "NulShock Shield",
                "NulFrost Shield",
                "Adept's Shield",
                "Tetra Shield",
                "Mythril Shield",
                "Gold Shield",
                "Emerald Shield",
                "Soldier's Shield",
                "Mage's Shield",
                "Silver Shield",
                "Onyx Shield",
                "Sorcery Shield",
                "Warrior's Shield",
                "Glorious Shield",
                "Metal Shield",
                "Pearl Shield",
                "Magic Shield",
                "Seeker's Shield",
                "Shield",
                "Buckler",
                "Sanctuary",
                "Buckler",
                "Buckler",
                "Buckler",
                "Buckler",
                "Buckler",
                "Buckler",
                "Buckler",
                "Buckler",
                "Buckler",
                "Buckler",
                "Buckler",
                "-"
            },
            new string[]
            {
                "Nirvana",
                "Staff",
                "Herding Staff",
                "Arc Arcana",
                "Abraxas",
                "Heavenly Axis",
                "Judgment",
                "Seraphim Rod",
                "Rod of Roses",
                "Nimbus Rod",
                "Wonder Wing",
                "Wing Wand",
                "Wonder Wand",
                "Laevatein",
                "Staff",
                "Astral Rod",
                "Chaos Rod",
                "Staff",
                "Staff",
                "Power Staff",
                "Shining Staff",
                "Faerie Staff",
                "Magistral Rod",
                "El Dorado",
                "Tri-Rod",
                "Wicked Wand",
                "Nemesis Rod",
                "Defender",
                "P-Staff",
                "M-Staff",
                "S-Staff",
                "A-Staff",
                "Prism Rod",
                "Mirage Rod",
                "Healing Rod",
                "Wind Rod",
                "Conductor",
                "Punisher",
                "Impasse",
                "Calcite Staff",
                "Bizarre Staff",
                "Staff of Thorns",
                "Reticent Staff",
                "Darkness Staff",
                "Monk Staff",
                "Mage's Staff",
                "Dual Rod",
                "Ominous Rod",
                "Death Wand",
                "Entangling Rod",
                "Break Rod",
                "Beladonna Wand",
                "Lullaby Rod",
                "Rod of Silence",
                "Rod of Darkness",
                "Rod of Wisdom",
                "Rod of Fire",
                "Rod of Ice",
                "Rod of Lightning",
                "Rod of Water",
                "Malleable Staff",
                "Force Rod",
                "Ductile Rod",
                "Sorcery Rod",
                "Full Metal Rod",
                "Rune Rod",
                "Enchanted Rod",
                "Rod of Striking",
                "Rod of Beating",
                "Spiked Rod",
                "Staff",
                "Staff",
                "Staff",
                "Staff",
                "Solomon Ring",
                "Arcane Ring",
                "Mythical Ring",
                "Sophia Ring",
                "Aegis Ring",
                "Sheltering Ring",
                "Saviour Ring",
                "Healing Ring",
                "Forbidding Ring",
                "Diamond Ring",
                "Ruby Ring",
                "Fortitude Ring",
                "Magical Ring",
                "Collector Ring",
                "Treasure Ring",
                "Ring of Hope",
                "Assault Ring",
                "Phantom Ring",
                "Recovery Ring",
                "Spiritual Ring",
                "Phoenix Ring",
                "Curative Ring",
                "Rainbow Ring",
                "Shining Ring",
                "Faerie Ring",
                "Peaceful Ring",
                "Shaman Ring",
                "Barrier Ring",
                "Star Ring",
                "Marching Ring",
                "Moon Ring",
                "Regen Ring",
                "Haste Ring",
                "Reflect Ring",
                "Shell Ring",
                "Protect Ring",
                "Ring",
                "Platinum Ring",
                "Sapphire Ring",
                "Power Ring",
                "Wizard Ring",
                "Elemental Ring",
                "Defending Ring",
                "Crimson Ring",
                "Snow Ring",
                "Ochre Ring",
                "Cerulean Ring",
                "Medical Ring",
                "Lucid Ring",
                "Serene Ring",
                "Light Ring",
                "Soul Ring",
                "Blessed Ring",
                "Soft Ring",
                "Serum Ring",
                "Alert Ring",
                "Echo Ring",
                "Bright Ring",
                "Red Ring",
                "White Ring",
                "Yellow Ring",
                "Blue Ring",
                "NulTide Ring",
                "NulBlaze Ring",
                "NulShock Ring",
                "NulFrost Ring",
                "Adept's Ring",
                "Tetra Ring",
                "Mythril Ring",
                "Gold Ring",
                "Emerald Ring",
                "Soldier's Ring",
                "Mage's Ring",
                "Silver Ring",
                "Onyx Ring",
                "Sorcery Ring",
                "Tough Ring",
                "Glorious Ring",
                "Metal Ring",
                "Pearl Ring",
                "Magic Ring",
                "Seeker's Ring",
                "Wide Ring",
                "Ring",
                "Holy Ring",
                "Ring",
                "Ring",
                "Ring",
                "Ring",
                "Ring",
                "Ring",
                "Ring",
                "Ring",
                "Ring",
                "Ring",
                "Ring",
                "-"
            },
            new string[]
            {

                "Masamune",
                "Dull Blade",
                "Beastmaster",
                "Conqueror",
                "Heaven's Cloud",
                "Muramasa",
                "Alkaid",
                "Peacemaker",
                "Genji Blade",
                "Dragonkiller",
                "Painkiller",
                "Divider",
                "The Nameless",
                "Ogrekiller",
                "Dull Blade",
                "Murasame",
                "Riot Blade",
                "Dull Blade",
                "Dull Blade",
                "Master Ogre",
                "Master Djinn",
                "Matoya's Blade",
                "Inducer",
                "Gilmonger",
                "Ichimonji",
                "Corruptor",
                "Ashura",
                "Kotetsu",
                "P-Blade",
                "M-Blade",
                "S-Blade",
                "A-Blade",
                "Prism Blade",
                "Mirage Blade",
                "Lifegiver",
                "Sonic Blade",
                "Sentry",
                "Assassin Blade",
                "Blockade",
                "Stillblade",
                "Venomous Blade",
                "Dozing Blade",
                "Tacit Blade",
                "Dark Blade",
                "Ogre Blade",
                "Djinn Blade",
                "Dual Blade",
                "Chaos Blade",
                "Critical Blade",
                "Stunner",
                "Gorgon Gaze",
                "Spider's Kiss",
                "Peaceful Slumber",
                "Soundless Scream",
                "Blurry Moon",
                "Hunter's Blade",
                "Fire Blade",
                "Frost Blade",
                "Thunder Blade",
                "Water Blade",
                "Shiranui",
                "Basara Blade",
                "Shimmering Blade",
                "Spiritual Blade",
                "Knight Blade",
                "Rune Blade",
                "Magic Blade",
                "Warblade",
                "Nodachi",
                "Katana",
                "Dull Blade",
                "Dull Blade",
                "Dull Blade",
                "Dull Blade",
                "Overlord",
                "Genji Bracer",
                "Dragon Lord",
                "Glutton",
                "Resistant",
                "Warder",
                "Immortal",
                "Healer",
                "Undefeated",
                "Diamond Bracer",
                "Ruby Bracer",
                "Battle Bracer",
                "Magical Bracer",
                "Collector Bracer",
                "Treasure Bracer",
                "Bracer of Hope",
                "Assault Bracer",
                "Phantom Bracer",
                "Recovery Bracer",
                "Spiritual Bracer",
                "Phoenix Bracer",
                "Curative Bracer",
                "Rainbow Bracer",
                "Shining Bracer",
                "Faerie Bracer",
                "Peaceful Bracer",
                "Shaman Bracer",
                "Barrier Bracer",
                "Star Bracer",
                "Marching Bracer",
                "Moon Bracer",
                "Regen Bracer",
                "Haste Bracer",
                "Reflect Bracer",
                "Shell Bracer",
                "Protect Bracer",
                "Bracer",
                "Platinum Bracer",
                "Sapphire Bracer",
                "Knight's Bracer",
                "Wizard Bracer",
                "Elemental Bracer",
                "Defending Bracer",
                "Crimson Bracer",
                "Snow Bracer",
                "Ochre Bracer",
                "Cerulean Bracer",
                "Medical Bracer",
                "Lucid Bracer",
                "Serene Bracer",
                "Light Bracer",
                "Soul Bracer",
                "Blessed Bracer",
                "Soft Bracer",
                "Serum Bracer",
                "Alert Bracer",
                "Echo Bracer",
                "Bright Bracer",
                "Red Bracer",
                "White Bracer",
                "Yellow Bracer",
                "Blue Bracer",
                "NulTide Bracer",
                "NulBlaze Bracer",
                "NulShock Bracer",
                "NulFrost Bracer",
                "Adept's Bracer",
                "Tetra Bracer",
                "Mythril Bracer",
                "Gold Bracer",
                "Emerald Bracer",
                "Soldier's Bracer",
                "Mage's Bracer",
                "Silver Bracer",
                "Onyx Bracer",
                "Sorcery Bracer",
                "Warrior's Bracer",
                "Glorious Bracer",
                "Metal Bracer",
                "Pearl Bracer",
                "Magic Bracer",
                "Seeker's Bracer",
                "Guardian Bracer",
                "Bracer",
                "Solidity",
                "Bracer",
                "Bracer",
                "Bracer",
                "Bracer",
                "Bracer",
                "Bracer",
                "Bracer",
                "Bracer",
                "Bracer",
                "Bracer",
                "Bracer",
                "-"
            },
            new string[]
            {
                "Spirit Lance",
                "Spear",
                "Taming Spear",
                "Quadforce",
                "Gungnir",
                "Luin",
                "Gae Bolg",
                "Venus Gospel",
                "Highwind",
                "Berserker",
                "Horn of the Ronso",
                "Chariot",
                "Transmuter",
                "Kain's Lance",
                "Spear",
                "Astral Spear",
                "Chaos Lance",
                "Spear",
                "Spear",
                "Giant Spear",
                "Titan Lance",
                "Eldritch Lance",
                "Shamanic Spear",
                "Prospector",
                "Trident",
                "Vicious Lance",
                "Dragoon Lance",
                "Rebel Lance",
                "P-Lance",
                "M-Lance",
                "S-Lance",
                "A-Lance",
                "Prism Spear",
                "Mirage Lance",
                "Healer Spear",
                "Sonic Lance",
                "Detector",
                "Thanatos Lance",
                "Net Spear",
                "Rock Buster",
                "Venom Spike",
                "Hypnos Spear",
                "Mage Hunter",
                "Darkbringer",
                "Knight Lance",
                "Wizard Lance",
                "Twin Lance",
                "Calamity Spear",
                "Matador Spear",
                "Web Lance",
                "Break Lance",
                "Snakehead",
                "Dream Lance",
                "Silent Spear",
                "Dusk Lance",
                "Hunter's Spear",
                "Heat Lance",
                "Ice Lance",
                "Thunder Spear",
                "Tidal Spear",
                "Shapeshifter",
                "Force Lance",
                "Halberd",
                "Magic Lance",
                "Full Metal Spear",
                "Rune Lance",
                "Enchanted Lance",
                "Striking Spear",
                "Heavy Spear",
                "Harpoon",
                "Spear",
                "Spear",
                "Spear",
                "Spear",
                "Pride of the Ronso",
                "Genji Armlet",
                "Sage's Armlet",
                "Crystal Armlet",
                "Aegis Armlet",
                "Adamantite",
                "Orichalcum",
                "Safe Passage",
                "Ronso Armlet",
                "Diamond Armlet",
                "Ruby Armlet",
                "Enhanced Armlet",
                "Magical Armlet",
                "Collector Armlet",
                "Treasure Armlet",
                "Armlet of Hope",
                "Assault Armlet",
                "Phantom Armlet",
                "Recovery Armlet",
                "Spiritual Armlet",
                "Phoenix Armlet",
                "Curative Armlet",
                "Rainbow Armlet",
                "Shining Armlet",
                "Faerie Armlet",
                "Peaceful Armlet",
                "Shaman Armlet",
                "Barrier Armlet",
                "Star Armlet",
                "Marching Armlet",
                "Moon Armlet",
                "Regen Armlet",
                "Haste Armlet",
                "Reflect Armlet",
                "Shell Armlet",
                "Protect Armlet",
                "Armlet",
                "Platinum Armlet",
                "Sapphire Armlet",
                "Knight's Armlet",
                "Wizard Armlet",
                "Elemental Armlet",
                "Defending Armlet",
                "Crimson Armlet",
                "Snow Armlet",
                "Ochre Armlet",
                "Cerulean Armlet",
                "Medical Armlet",
                "Lucid Armlet",
                "Serene Armlet",
                "Light Armlet",
                "Soul Armlet",
                "Blessed Armlet",
                "Soft Armlet",
                "Serum Armlet",
                "Alert Armlet",
                "Echo Armlet",
                "Bright Armlet",
                "Red Armlet",
                "White Armlet",
                "Yellow Armlet",
                "Blue Armlet",
                "NulTide Armlet",
                "NulBlaze Armlet",
                "NulShock Armlet",
                "NulFrost Armlet",
                "Adept's Armlet",
                "Tetra Armlet",
                "Mythril Armlet",
                "Gold Armlet",
                "Emerald Armlet",
                "Soldier's Armlet",
                "Mage's Armlet",
                "Silver Armlet",
                "Onyx Armlet",
                "Sorcery Armlet",
                "Warrior's Armlet",
                "Glorious Armlet",
                "Metal Armlet",
                "Pearl Armlet",
                "Magic Armlet",
                "Seeker's Armlet",
                "Guardian Armlet",
                "Armlet",
                "Acropolis",
                "Armlet",
                "Armlet",
                "Armlet",
                "Armlet",
                "Armlet",
                "Armlet",
                "Armlet",
                "Armlet",
                "Armlet",
                "Armlet",
                "Armlet",
                "-"
            },
            new string[]
            {
                "World Champion",
                "Official Ball",
                "Catcher",
                "Four-on-One",
                "Grand Slam",
                "Blowout",
                "Rout",
                "Tie Breaker",
                "Winning Streak",
                "Scoring Spree",
                "Triple Score",
                "Double Score",
                "Rookie Star",
                "Buzzerbeater",
                "Official Ball",
                "Overtime",
                "Penalty Master",
                "Official Ball",
                "Official Ball",
                "Ace Striker",
                "Ace Wizard",
                "Over the Top",
                "Halftime",
                "Free Agent",
                "Tricolor",
                "Triple Penalty",
                "Turnover",
                "Rematch",
                "P-Ball",
                "M-Ball",
                "S-Ball",
                "A-Ball",
                "Prism Ball",
                "Mirage Ball",
                "Comeback",
                "Breakaway",
                "First Goal",
                "Sudden Death",
                "Timeout",
                "Stone Cold",
                "Violation",
                "Sleeper",
                "Muffler",
                "Blackout",
                "Power Play",
                "Virtuoso",
                "Double Header",
                "Double Penalty",
                "Rough Play",
                "Delay of Game",
                "T.K.O.",
                "Rulebreaker",
                "Dream Team",
                "Noisebreaker",
                "Blind Pass",
                "Scout",
                "Fire Ball",
                "Ice Ball",
                "Thunder Ball",
                "Water Ball",
                "All-Rounder",
                "Ovation",
                "Switch Hitter",
                "Trickster",
                "Striker",
                "Rune Ball",
                "Magic Ball",
                "Hyper Ball",
                "Power Ball",
                "Center Forward",
                "Official Ball",
                "Official Ball",
                "Official Ball",
                "Official Ball",
                "Indomitable",
                "Super Goalie",
                "High Spirits",
                "Final Four",
                "Great Four",
                "The Guardian",
                "Automatic",
                "First Aid",
                "Keeper",
                "Diamond Armguard",
                "Ruby Armguard",
                "Power Ace",
                "Magic Ace",
                "Best Play",
                "Great Play",
                "Benchwarmer",
                "Triple Save",
                "Element Save",
                "Recovery Armguard",
                "Spiritual Armguard",
                "Miracle Comeback",
                "Top Shape",
                "Miracle Save",
                "Last-Ditch",
                "Triple Guard",
                "Off-Season",
                "Shaman Armguard",
                "Hat Trick",
                "Pep Talk",
                "Auto Armguard",
                "Danger Armguard",
                "Second Wind",
                "Fast Break",
                "Reflect Armguard",
                "Shell Armguard",
                "Protect Armguard",
                "Armguard",
                "Platinum Armguard",
                "Sapphire Armguard",
                "Power Armguard",
                "Energy Armguard",
                "Elemental Armguard",
                "Low Risk",
                "Crimson Armguard",
                "Snow Armguard",
                "Ochre Armguard",
                "Cerulean Armguard",
                "Medical Armguard",
                "Lucid Armguard",
                "Serene Armguard",
                "Light Armguard",
                "Soul Armguard",
                "Blessed Armguard",
                "Soft Armguard",
                "Serum Armguard",
                "Alert Armguard",
                "Echo Armguard",
                "Bright Armguard",
                "Red Armguard",
                "White Armguard",
                "Yellow Armguard",
                "Blue Armguard",
                "NulTide Armguard",
                "NulBlaze Armguard",
                "NulShock Armguard",
                "NulFrost Armguard",
                "Adept's Armguard",
                "Tetra Armguard",
                "Mythril Armguard",
                "Gold Armguard",
                "Emerald Armguard",
                "Soldier's Armguard",
                "Mage's Armguard",
                "Silver Armguard",
                "Onyx Armguard",
                "Sorcery Armguard",
                "Warrior's Armguard",
                "Glorious Armguard",
                "Metal Armguard",
                "Pearl Armguard",
                "Magic Armguard",
                "Seeker's Armguard",
                "Guardian Armguard",
                "Armguard",
                "Shutout",
                "Armguard",
                "Armguard",
                "Armguard",
                "Armguard",
                "Armguard",
                "Armguard",
                "Armguard",
                "Armguard",
                "Armguard",
                "Armguard",
                "Armguard",
                "-"
            },
            new string[]
            {
                "Onion Knight",
                "Moogle",
                "Trapper Mog",
                "Moomba Quartet",
                "Soul of Mog",
                "Space Soul",
                "Space Master",
                "Space King",
                "Space Force",
                "Space Energy",
                "Comet Cactuar",
                "Star Cactuar",
                "Lord Cactuar",
                "Space Power",
                "Moogle",
                "Magical Cactuar",
                "Chaotic Cait Sith",
                "Moogle",
                "Moogle",
                "Space Warrior",
                "Space Mage",
                "Mana Mog",
                "Cactuar Wizard",
                "Space Bandit",
                "Moomba Trio",
                "Abaddon Cait Sith",
                "Vengeful Cactuar",
                "Raging Cactuar",
                "P-Mog",
                "M-Mog",
                "S-Mog",
                "A-Mog",
                "Prism Cactuar",
                "Booster Cactuar",
                "Medical Mog",
                "Swift Cactuar",
                "Cactuar Spy",
                "Wicked Cait Sith",
                "Chronos Cait Sith",
                "Stone Cait Sith",
                "Toxic Cait Sith",
                "Dreamy Cait Sith",
                "Mute Cait Sith",
                "Dark Cait Sith",
                "Power Mog",
                "Magician Mog",
                "Moomba Duo",
                "Ominous Cait Sith",
                "Fatal Cait Sith",
                "Late Cait Sith",
                "Fossil Cait Sith",
                "Noxious Cait Sith",
                "Sleepy Cait Sith",
                "Quiet Cait Sith",
                "Blinding Cait Sith",
                "Cactuar Scope",
                "Fire Moomba",
                "Ice Moomba",
                "Thunder Moomba",
                "Water Moomba",
                "Morphing Mog",
                "Moomba Force",
                "Variable Mog",
                "Moomba Mage",
                "Moomba Warrior",
                "Rune Mog",
                "Magical Mog",
                "Buster Mog",
                "Attack Mog",
                "Stinger Mog",
                "Moogle",
                "Moogle",
                "Moogle",
                "Moogle",
                "Samantha Soul",
                "Minerva Bangle",
                "Mythical Bangle",
                "Draupnir",
                "Aegis Bangle",
                "Precious Bangle",
                "Imperial Bangle",
                "Auto Bangle",
                "Black Bangle",
                "Diamond Bangle",
                "Ruby Bangle",
                "Queen's Bangle",
                "Magister Bangle",
                "Collector Bangle",
                "Treasure Bangle",
                "Bangle of Hope",
                "Assault Bangle",
                "Phantom Bangle",
                "Recovery Bangle",
                "Spiritual Bangle",
                "Phoenix Bangle",
                "Curative Bangle",
                "Rainbow Bangle",
                "Shining Bangle",
                "Faerie Bangle",
                "Peaceful Bangle",
                "Shaman Bangle",
                "Barrier Bangle",
                "Star Bangle",
                "Marching Bangle",
                "Moon Bangle",
                "Regen Bangle",
                "Haste Bangle",
                "Reflect Bangle",
                "Shell Bangle",
                "Protect Bangle",
                "Bangle",
                "Platinum Bangle",
                "Sapphire Bangle",
                "Power Bangle",
                "Wizard Bangle",
                "Elemental Bangle",
                "Savior Bangle",
                "Crimson Bangle",
                "Snow Bangle",
                "Ochre Bangle",
                "Cerulean Bangle",
                "Medical Bangle",
                "Lucid Bangle",
                "Serene Bangle",
                "Light Bangle",
                "Soul Bangle",
                "Blessed Bangle",
                "Soft Bangle",
                "Serum Bangle",
                "Alert Bangle",
                "Echo Bangle",
                "Bright Bangle",
                "Red Bangle",
                "White Bangle",
                "Yellow Bangle",
                "Blue Bangle",
                "NulTide Bangle",
                "NulBlaze Bangle",
                "NulShock Bangle",
                "NulFrost Bangle",
                "Adept's Bangle",
                "Tetra Bangle",
                "Mythril Bangle",
                "Gold Bangle",
                "Emerald Bangle",
                "Vita Bangle",
                "Mage's Bangle",
                "Silver Bangle",
                "Onyx Bangle",
                "Sorcery Bangle",
                "Tough Bangle",
                "Glorious Bangle",
                "Metal Bangle",
                "Pearl Bangle",
                "Magic Bangle",
                "Seeker's Bangle",
                "Guardian Bangle",
                "Bangle",
                "Eternity",
                "Bangle",
                "Bangle",
                "Bangle",
                "Bangle",
                "Bangle",
                "Bangle",
                "Bangle",
                "Bangle",
                "Bangle",
                "Bangle",
                "Bangle",
                "-"
            },
            new string[]
            {

                "Godhand",
                "Claw",
                "Iron Grip",
                "Deus Ex Machina",
                "Kaiser Knuckles",
                "Victorix",
                "Unlimited",
                "Warmonger",
                "Overload",
                "Override",
                "Golden Arm",
                "Golden Hand",
                "Ironside",
                "Battle Freak",
                "Claw",
                "Infinity",
                "Tempest Claw",
                "Claw",
                "Claw",
                "Spartan",
                "Brunhilde",
                "Valkyrie",
                "Magical Rave",
                "Stickyfingers",
                "Rising Sun",
                "Typhoon Claw",
                "Untouchable",
                "Tit-for-Tat",
                "P-Claw",
                "M-Claw",
                "S-Claw",
                "A-Claw",
                "Prism Claw",
                "Mirage Claw",
                "Survivor",
                "Vanguard",
                "Sonar",
                "Executioner",
                "Clockwork",
                "Colossus",
                "Manticore Claw",
                "Lights Out",
                "Mage Masher",
                "Jammer",
                "Iron Claw",
                "The Ogre",
                "Dual Claw",
                "Hurricane Claw",
                "Ninja Claw",
                "Clock Hand",
                "Break Knuckles",
                "Poison Claw",
                "Daydreamer",
                "Tongue Holder",
                "Eye Poker",
                "Hawkeye",
                "Hot Knuckles",
                "Ice Claw",
                "Shocking Fist",
                "Tidal Knuckles",
                "Flexible Arm",
                "Force Knuckles",
                "Devastator",
                "Magic Knuckles",
                "Buster Knuckles",
                "Magic Claw",
                "Magic Glove",
                "Buster Claw",
                "Buster Glove",
                "Barbed Knuckles",
                "Claw",
                "Claw",
                "Claw",
                "Claw",
                "Dreadnought",
                "Atlas",
                "Celestial",
                "Invincible",
                "Armada",
                "Triumph",
                "Intrepid",
                "Goliath",
                "Argonaut",
                "Diamond Targe",
                "Ruby Targe",
                "Warlord",
                "Dominator",
                "Buccaneer",
                "Corsair",
                "Targe of Hope",
                "Assault Targe",
                "Phantom Targe",
                "Recovery Targe",
                "Spiritual Targe",
                "Phoenix Targe",
                "Curative Targe",
                "Phalanx",
                "Tercio",
                "Talisman",
                "Peaceful Targe",
                "Shaman Targe",
                "Victorious",
                "Star Targe",
                "Marching Targe",
                "Moon Targe",
                "Regen Targe",
                "Haste Targe",
                "Reflect Targe",
                "Shell Targe",
                "Protect Targe",
                "Targe",
                "Centurion",
                "Echelon",
                "Knight's Targe",
                "Wizard Targe",
                "Elemental Targe",
                "Reliant",
                "Crimson Targe",
                "Snow Targe",
                "Ochre Targe",
                "Cerulean Targe",
                "Medical Targe",
                "Lucid Targe",
                "Dauntless",
                "Light Targe",
                "Soul Targe",
                "Blessed Targe",
                "Soft Targe",
                "Serum Targe",
                "Alert Targe",
                "Echo Targe",
                "Bright Targe",
                "Red Targe",
                "White Targe",
                "Yellow Targe",
                "Blue Targe",
                "NulTide Targe",
                "NulBlaze Targe",
                "NulShock Targe",
                "NulFrost Targe",
                "Adept's Targe",
                "Tetra Targe",
                "Mythril Targe",
                "Gold Targe",
                "Emerald Targe",
                "Soldier's Targe",
                "Mage's Targe",
                "Silver Targe",
                "Onyx Targe",
                "Sorcery Targe",
                "Warrior's Targe",
                "Glorious Targe",
                "Metal Targe",
                "Pearl Targe",
                "Magic Targe",
                "Seeker's Targe",
                "Guardian Targe",
                "Targe",
                "Impervious",
                "Targe",
                "Targe",
                "Targe",
                "Targe",
                "Targe",
                "Targe",
                "Targe",
                "Targe",
                "Targe",
                "Targe",
                "Targe",
                "-",
            },
        };
    }

}
