using System.Collections.Generic;
using System.Linq;

namespace Farplane.FFX2.Values
{
    public static class AutoAbilities
    {
        public static List<AutoAbility> AutoAbilityList = new List<AutoAbility>
        {
            new AutoAbility {ID = 0x8000, Name = "First Strike"},
            new AutoAbility {ID = 0x8001, Name = "Initiative"},
            new AutoAbility {ID = 0x8002, Name = "Counterattack"},
            new AutoAbility {ID = 0x8003, Name = "Evade & Counter"},
            new AutoAbility {ID = 0x8004, Name = "Magic Counter"},
            new AutoAbility {ID = 0x8005, Name = "Magic Booster"},
            new AutoAbility {ID = 0x8006, Name = "Chemist"},
            new AutoAbility {ID = 0x8007, Name = "Elementalist"},
            new AutoAbility {ID = 0x8008, Name = "Physicist"},
            new AutoAbility {ID = 0x8009, Name = "Double AP"},
            new AutoAbility {ID = 0x800a, Name = "Triple AP"},
            new AutoAbility {ID = 0x800b, Name = "Break HP Limit"},
            new AutoAbility {ID = 0x800c, Name = "Break MP Limit"},
            new AutoAbility {ID = 0x800d, Name = "Break Damage Limit"},
            new AutoAbility {ID = 0x800e, Name = "Butterfingers"},
            new AutoAbility {ID = 0x800f, Name = "Gillionaire"},
            new AutoAbility {ID = 0x8010, Name = "Double Items"},
            new AutoAbility {ID = 0x8011, Name = "Double EXP"},
            new AutoAbility {ID = 0x8012, Name = "Item Hunter"},
            new AutoAbility {ID = 0x8013, Name = "Piercing Magic"},
            new AutoAbility {ID = 0x8014, Name = "HP Stroll"},
            new AutoAbility {ID = 0x8015, Name = "MP Stroll"},
            new AutoAbility {ID = 0x8016, Name = "HP/MP Stroll"},
            new AutoAbility {ID = 0x8017, Name = "No Encounters"},
            new AutoAbility {ID = 0x8018, Name = "Trigger Happy Lv.2"},
            new AutoAbility {ID = 0x8019, Name = "Trigger Happy Lv.3"},
            new AutoAbility {ID = 0x801a, Name = "Scan Lv.2"},
            new AutoAbility {ID = 0x801b, Name = "Scan Lv.3"},
            new AutoAbility {ID = 0x801c, Name = "Half MP Cost"},
            new AutoAbility {ID = 0x801d, Name = "One MP Cost"},
            new AutoAbility {ID = 0x801e, Name = "Fiend Hunter Lv.2"},
            new AutoAbility {ID = 0x801f, Name = "Items Lv.2"},
            new AutoAbility {ID = 0x8020, Name = "Black Magic Lv.2"},
            new AutoAbility {ID = 0x8021, Name = "Black Magic Lv.3"},
            new AutoAbility {ID = 0x8022, Name = "White Magic Lv.2"},
            new AutoAbility {ID = 0x8023, Name = "White Magic Lv.3"},
            new AutoAbility {ID = 0x8024, Name = "Kogoro Lv.2"},
            new AutoAbility {ID = 0x8025, Name = "Kogoro Lv.3"},
            new AutoAbility {ID = 0x8026, Name = "Ghiki Lv.2"},
            new AutoAbility {ID = 0x8027, Name = "Ghiki Lv.3"},
            new AutoAbility {ID = 0x8028, Name = "Flurry Lv.2"},
            new AutoAbility {ID = 0x8029, Name = "Flurry Lv.3"},
            new AutoAbility {ID = 0x802a, Name = "Firestrike"},
            new AutoAbility {ID = 0x802b, Name = "Fire Ward"},
            new AutoAbility {ID = 0x802c, Name = "Fireproof"},
            new AutoAbility {ID = 0x802d, Name = "Fire Eater"},
            new AutoAbility {ID = 0x802e, Name = "Icestrike"},
            new AutoAbility {ID = 0x802f, Name = "Ice Ward"},
            new AutoAbility {ID = 0x8030, Name = "Iceproof"},
            new AutoAbility {ID = 0x8031, Name = "Ice Eater"},
            new AutoAbility {ID = 0x8032, Name = "Lightningstrike"},
            new AutoAbility {ID = 0x8033, Name = "Lightning Ward"},
            new AutoAbility {ID = 0x8034, Name = "Lightningproof"},
            new AutoAbility {ID = 0x8035, Name = "Lightning Eater"},
            new AutoAbility {ID = 0x8036, Name = "Waterstrike"},
            new AutoAbility {ID = 0x8037, Name = "Water Ward"},
            new AutoAbility {ID = 0x8038, Name = "Waterproof"},
            new AutoAbility {ID = 0x8039, Name = "Water Eater"},
            new AutoAbility {ID = 0x803a, Name = "Gravitystrike"},
            new AutoAbility {ID = 0x803b, Name = "Gravity Ward"},
            new AutoAbility {ID = 0x803c, Name = "Gravityproof"},
            new AutoAbility {ID = 0x803d, Name = "Gravity Eater"},
            new AutoAbility {ID = 0x803e, Name = "Holystrike"},
            new AutoAbility {ID = 0x803f, Name = "Holy Eater"},
            new AutoAbility {ID = 0x8040, Name = "Fire/Ice Strike"},
            new AutoAbility {ID = 0x8041, Name = "Fire/Ice Eater"},
            new AutoAbility {ID = 0x8042, Name = "Lightning/Water Strike"},
            new AutoAbility {ID = 0x8043, Name = "Lightning/Water Eater"},
            new AutoAbility {ID = 0x8044, Name = "Tetrastrike"},
            new AutoAbility {ID = 0x8045, Name = "Tetra Ward"},
            new AutoAbility {ID = 0x8046, Name = "Tetraproof"},
            new AutoAbility {ID = 0x8047, Name = "Tetra Eater"},
            new AutoAbility {ID = 0x8048, Name = "Omnistrike"},
            new AutoAbility {ID = 0x8049, Name = "Deathtouch"},
            new AutoAbility {ID = 0x804a, Name = "Deathproof"},
            new AutoAbility {ID = 0x804b, Name = "Stonetouch"},
            new AutoAbility {ID = 0x804c, Name = "Stoneproof"},
            new AutoAbility {ID = 0x804d, Name = "Sleeptouch"},
            new AutoAbility {ID = 0x804e, Name = "Sleepproof"},
            new AutoAbility {ID = 0x804f, Name = "Silencetouch"},
            new AutoAbility {ID = 0x8050, Name = "Silenceproof"},
            new AutoAbility {ID = 0x8051, Name = "Darktouch"},
            new AutoAbility {ID = 0x8052, Name = "Darkproof"},
            new AutoAbility {ID = 0x8053, Name = "Poisontouch"},
            new AutoAbility {ID = 0x8054, Name = "Poisonproof"},
            new AutoAbility {ID = 0x8055, Name = "Confusetouch"},
            new AutoAbility {ID = 0x8056, Name = "Confuseproof"},
            new AutoAbility {ID = 0x8057, Name = "Berserktouch"},
            new AutoAbility {ID = 0x8058, Name = "Berserkproof"},
            new AutoAbility {ID = 0x8059, Name = "Doomtouch"},
            new AutoAbility {ID = 0x805a, Name = "Doomproof"},
            new AutoAbility {ID = 0x805b, Name = "Curseproof"},
            new AutoAbility {ID = 0x805c, Name = "Pointlessproof"},
            new AutoAbility {ID = 0x805d, Name = "Itchproof"},
            new AutoAbility {ID = 0x805e, Name = "Slowtouch"},
            new AutoAbility {ID = 0x805f, Name = "Slowproof"},
            new AutoAbility {ID = 0x8060, Name = "Stoptouch"},
            new AutoAbility {ID = 0x8061, Name = "Stopproof"},
            new AutoAbility {ID = 0x8062, Name = "Sense Preserver"},
            new AutoAbility {ID = 0x8063, Name = "Health Preserver"},
            new AutoAbility {ID = 0x8064, Name = "Sanity Preserver"},
            new AutoAbility {ID = 0x8065, Name = "Time Preserver"},
            new AutoAbility {ID = 0x8066, Name = "Life Preserver"},
            new AutoAbility {ID = 0x8067, Name = "Ribbon"},
            new AutoAbility {ID = 0x8068, Name = "Ribbon"},
            new AutoAbility {ID = 0x8069, Name = "Super Ribbon"},
            new AutoAbility {ID = 0x806a, Name = "Auto-Shell"},
            new AutoAbility {ID = 0x806b, Name = "Auto-Protect"},
            new AutoAbility {ID = 0x806c, Name = "Auto-Wall"},
            new AutoAbility {ID = 0x806d, Name = "Auto-Reflect"},
            new AutoAbility {ID = 0x806e, Name = "Auto-Regen"},
            new AutoAbility {ID = 0x806f, Name = "Auto-Haste"},
            new AutoAbility {ID = 0x8070, Name = "Critical"},
            new AutoAbility {ID = 0x8071, Name = "Spellspring"},
            new AutoAbility {ID = 0x8072, Name = "Double HP"},
            new AutoAbility {ID = 0x8073, Name = "Triple HP"},
            new AutoAbility {ID = 0x8074, Name = "SOS Shell"},
            new AutoAbility {ID = 0x8075, Name = "SOS Protect"},
            new AutoAbility {ID = 0x8076, Name = "SOS Reflect"},
            new AutoAbility {ID = 0x8077, Name = "SOS Regen"},
            new AutoAbility {ID = 0x8078, Name = "SOS Haste"},
            new AutoAbility {ID = 0x8079, Name = "SOS Spellspring"},
            new AutoAbility {ID = 0x807a, Name = "SOS ????"},
            new AutoAbility {ID = 0x807b, Name = "SOS Critical"},
            new AutoAbility {ID = 0x807c, Name = "Turbo Swordplay"},
            new AutoAbility {ID = 0x807d, Name = "Turbo Bushido"},
            new AutoAbility {ID = 0x807e, Name = "Turbo Arcana"},
            new AutoAbility {ID = 0x807f, Name = "Turbo Instinct"},
            new AutoAbility {ID = 0x8080, Name = "Turbo Black Magic"},
            new AutoAbility {ID = 0x8081, Name = "Turbo White Magic"},
            new AutoAbility {ID = 0x8082, Name = "Strength +5"},
            new AutoAbility {ID = 0x8083, Name = "Defense +5"},
            new AutoAbility {ID = 0x8084, Name = "Magic +5"},
            new AutoAbility {ID = 0x8085, Name = "Magic Defense +5"},
            new AutoAbility {ID = 0x8086, Name = "Strength +10"},
            new AutoAbility {ID = 0x8087, Name = "Magic +10"},
            new AutoAbility {ID = 0x8088, Name = "Defense +10"},
            new AutoAbility {ID = 0x8089, Name = "Magic Defense +10"},
            new AutoAbility {ID = 0x808a, Name = "Strength +15"},
            new AutoAbility {ID = 0x808b, Name = "Magic +15"},
            new AutoAbility {ID = 0x808c, Name = "Defense +15"},
            new AutoAbility {ID = 0x808d, Name = "Magic Defense +15"},
            new AutoAbility {ID = 0x808e, Name = "Strength +20"},
            new AutoAbility {ID = 0x808f, Name = "Magic +20"},
            new AutoAbility {ID = 0x8090, Name = "Defense +20"},
            new AutoAbility {ID = 0x8091, Name = "Magic Defense +20"},
            new AutoAbility {ID = 0x8092, Name = "Accuracy +20"},
            new AutoAbility {ID = 0x8093, Name = "Agility +5"},
            new AutoAbility {ID = 0x8094, Name = "Luck +30"},
            new AutoAbility {ID = 0x8095, Name = "Kijo's Soul"},
            new AutoAbility {ID = 0x8096, Name = "Majo's Soul"},
            new AutoAbility {ID = 0x8097, Name = "Double All"},
            new AutoAbility {ID = 0x8098, Name = "Double HP"},
            new AutoAbility {ID = 0x8099, Name = "Double MP"},
            new AutoAbility {ID = 0x809a, Name = "More Encounters"},
            new AutoAbility {ID = 0x809b, Name = "SOS Wall"},
            new AutoAbility {ID = 0x809c, Name = "Nitro Black Magic"},
            new AutoAbility {ID = 0x809d, Name = "Poison/Sleep Attack"},
            new AutoAbility {ID = 0x809e, Name = "Death/Pointless Def."},
            new AutoAbility {ID = 0x809f, Name = "Ailment Def."},
            new AutoAbility {ID = 0x80a0, Name = "Tetra Absorb"},
            new AutoAbility {ID = 0x80a1, Name = "Total Limit Break"}
        };

        public static List<string> GetAutoAbilityNames()
        {
            return AutoAbilityList.Select(a => a.Name).ToList();
        }

        public static AutoAbility GetAutoAbility(int abilityID)
        {
            var autoAbility = AutoAbilityList.FirstOrDefault(ability => ability.ID == abilityID);
            return autoAbility;
        }
    }

    public class AutoAbility
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}