using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Farplane.FFX2.Values
{
    class Commands
    {
        public static List<string> GetCommandNames()
        {
            List<string> names = new List<string>();
            foreach (var c in CommandList)
                names.Add(c.Name);

            return names;
        }

        public static int IndexByID(int commandID)
        {
            if (commandID == 0 || commandID == 0xFF) return 0;
            var c = CommandList.First(cl => cl.ID == commandID);
            if (c != null) return CommandList.IndexOf(c);
            return 0;
        }

        public static Command GetCommand(int ID)
        {
            var cmd = CommandList.FirstOrDefault(command => command.ID == ID);
            return cmd;
        }
        
        public static List<Command> CommandList = new List<Command>()
        {
            new Command {ID = 0x3000, Name = "Item"},
            new Command {ID = 0x3001, Name = "Escape"},
            new Command {ID = 0x3002, Name = "Dresspheres"},
            new Command {ID = 0x3003, Name = "(UNUSED)"},
            new Command {ID = 0x3004, Name = "(UNUSED)"},
            new Command {ID = 0x3005, Name = "(UNUSED)"},
            new Command {ID = 0x3006, Name = "(UNUSED)"},
            new Command {ID = 0x3007, Name = "(UNUSED)"},
            new Command {ID = 0x3008, Name = "Gunplay"},
            new Command {ID = 0x3009, Name = "Stash"},
            new Command {ID = 0x300A, Name = "Blue Bullet"},
            new Command {ID = 0x300B, Name = "Fiend Hunter"},
            new Command {ID = 0x300C, Name = "Dance"},
            new Command {ID = 0x300D, Name = "Sing"},
            new Command {ID = 0x300E, Name = "Kupo!"},
            new Command {ID = 0x300F, Name = "Wildcat"},
            new Command {ID = 0x3010, Name = "Cutlery"},
            new Command {ID = 0x3011, Name = "Flimflam"},
            new Command {ID = 0x3012, Name = "Gamble"},
            new Command {ID = 0x3013, Name = "Kogoro"},
            new Command {ID = 0x3014, Name = "Ghiki"},
            new Command {ID = 0x3015, Name = "Flurry"},
            new Command {ID = 0x3016, Name = "Fallalery"},
            new Command {ID = 0x3017, Name = "Left Pistil"},
            new Command {ID = 0x3018, Name = "Right Pistil"},
            new Command {ID = 0x3019, Name = "Machinations"},
            new Command {ID = 0x301A, Name = "Smash"},
            new Command {ID = 0x301B, Name = "Crush"},
            new Command {ID = 0x301C, Name = "Throttle"},
            new Command {ID = 0x301D, Name = "Dextral Arts"},
            new Command {ID = 0x301E, Name = "Sinistal Arts"},
            new Command {ID = 0x301F, Name = "Swordplay"},
            new Command {ID = 0x3020, Name = "Bushido"},
            new Command {ID = 0x3021, Name = "Arcana"},
            new Command {ID = 0x3022, Name = "Instinct"},
            new Command {ID = 0x3023, Name = "Black Magic"},
            new Command {ID = 0x3024, Name = "White Magic"},
            new Command {ID = 0x3025, Name = "Auto-Life"},
            new Command {ID = 0x3026, Name = "Doom"},
            new Command {ID = 0x3027, Name = "Energy Ray"},
            new Command {ID = 0x3028, Name = "Energy Blast"},
            new Command {ID = 0x3029, Name = "Hellfire"},
            new Command {ID = 0x302A, Name = "Mjollnir"},
            new Command {ID = 0x302B, Name = "Mega-Flare"},
            new Command {ID = 0x302C, Name = "Attack"},
            new Command {ID = 0x302D, Name = "Attack"},
            new Command {ID = 0x302E, Name = "Attack"},
            new Command {ID = 0x302F, Name = "Attack"},
            new Command {ID = 0x3030, Name = "Attack"},
            new Command {ID = 0x3031, Name = "Attack"},
            new Command {ID = 0x3032, Name = "Trigger Happy"},
            new Command {ID = 0x3033, Name = "Potshot"},
            new Command {ID = 0x3034, Name = "Cheap Shot"},
            new Command {ID = 0x3035, Name = "Enchanted Ammo"},
            new Command {ID = 0x3036, Name = "Target MP"},
            new Command {ID = 0x3037, Name = "Quarter Pounder"},
            new Command {ID = 0x3038, Name = "On the Level"},
            new Command {ID = 0x3039, Name = "Burst Shot"},
            new Command {ID = 0x303A, Name = "Table-turner"},
            new Command {ID = 0x303B, Name = "Scattershot"},
            new Command {ID = 0x303C, Name = "Scatterburst"},
            new Command {ID = 0x303D, Name = "Scan"},
            new Command {ID = 0x303E, Name = "Shell Cracker"},
            new Command {ID = 0x303F, Name = "Anti Aircraft"},
            new Command {ID = 0x3040, Name = "Silver Bullet"},
            new Command {ID = 0x3041, Name = "Flan Eater"},
            new Command {ID = 0x3042, Name = "Elementillery"},
            new Command {ID = 0x3043, Name = "Killasaurus"},
            new Command {ID = 0x3044, Name = "Drake Slayer"},
            new Command {ID = 0x3045, Name = "Dismantler"},
            new Command {ID = 0x3046, Name = "Mech Destroyer"},
            new Command {ID = 0x3047, Name = "Demon Muzzle"},
            new Command {ID = 0x3048, Name = "Fire Breath"},
            new Command {ID = 0x3049, Name = "Seed Cannon"},
            new Command {ID = 0x304A, Name = "Stone Breath"},
            new Command {ID = 0x304B, Name = "Absorb"},
            new Command {ID = 0x304C, Name = "White Wind"},
            new Command {ID = 0x304D, Name = "Bad Breath"},
            new Command {ID = 0x304E, Name = "Mighty Guard"},
            new Command {ID = 0x304F, Name = "Supernova"},
            new Command {ID = 0x3050, Name = "Cry in the Night"},
            new Command {ID = 0x3051, Name = "Drill Shot"},
            new Command {ID = 0x3052, Name = "Mortar"},
            new Command {ID = 0x3053, Name = "Annihilator"},
            new Command {ID = 0x3054, Name = "Heaven's Cataract"},
            new Command {ID = 0x3055, Name = "1000 Needles"},
            new Command {ID = 0x3056, Name = "Storm Cannon"},
            new Command {ID = 0x3057, Name = "Blaster"},
            new Command {ID = 0x3058, Name = "Mix"},
            new Command {ID = 0x3059, Name = "Potion"},
            new Command {ID = 0x305A, Name = "Hi-Potion"},
            new Command {ID = 0x305B, Name = "Mega-Potion"},
            new Command {ID = 0x305C, Name = "X-Potion"},
            new Command {ID = 0x305D, Name = "Remedy"},
            new Command {ID = 0x305E, Name = "Dispel Tonic"},
            new Command {ID = 0x305F, Name = "Phoenix Down"},
            new Command {ID = 0x3060, Name = "Mega Phoenix"},
            new Command {ID = 0x3061, Name = "Ether"},
            new Command {ID = 0x3062, Name = "Elixir"},
            new Command {ID = 0x3063, Name = "Assault"},
            new Command {ID = 0x3064, Name = "Sentinel"},
            new Command {ID = 0x3065, Name = "Power Break"},
            new Command {ID = 0x3066, Name = "Armor Break"},
            new Command {ID = 0x3067, Name = "Magic Break"},
            new Command {ID = 0x3068, Name = "Mental Break"},
            new Command {ID = 0x3069, Name = "Flametongue"},
            new Command {ID = 0x306A, Name = "Icebrand"},
            new Command {ID = 0x306B, Name = "Thunder Blade"},
            new Command {ID = 0x306C, Name = "Liquid Steel"},
            new Command {ID = 0x306D, Name = "Demi Sword"},
            new Command {ID = 0x306E, Name = "Excalibur"},
            new Command {ID = 0x306F, Name = "Delay Attack"},
            new Command {ID = 0x3070, Name = "Delay Buster"},
            new Command {ID = 0x3071, Name = "Mirror of Equity"},
            new Command {ID = 0x3072, Name = "Magicide"},
            new Command {ID = 0x3073, Name = "Dismissal"},
            new Command {ID = 0x3074, Name = "Fingersnap"},
            new Command {ID = 0x3075, Name = "Sparkler"},
            new Command {ID = 0x3076, Name = "Fireworks"},
            new Command {ID = 0x3077, Name = "Momentum"},
            new Command {ID = 0x3078, Name = "Shin-Zantetsu"},
            new Command {ID = 0x3079, Name = "Nonpareil"},
            new Command {ID = 0x307A, Name = "No Fear"},
            new Command {ID = 0x307B, Name = "Clean Slate"},
            new Command {ID = 0x307C, Name = "Hayate"},
            new Command {ID = 0x307D, Name = "Spare Change"},
            new Command {ID = 0x307E, Name = "Zantetsu"},
            new Command {ID = 0x307F, Name = "Darkness"},
            new Command {ID = 0x3080, Name = "Charon"},
            new Command {ID = 0x3081, Name = "Drain"},
            new Command {ID = 0x3082, Name = "Demi"},
            new Command {ID = 0x3083, Name = "Confuse"},
            new Command {ID = 0x3084, Name = "Break"},
            new Command {ID = 0x3085, Name = "Bio"},
            new Command {ID = 0x3086, Name = "Doom"},
            new Command {ID = 0x3087, Name = "Death"},
            new Command {ID = 0x3088, Name = "Black Sky"},
            new Command {ID = 0x3089, Name = "Berserk"},
            new Command {ID = 0x308A, Name = "Howl"},
            new Command {ID = 0x308B, Name = "Cripple"},
            new Command {ID = 0x308C, Name = "Mad Rush"},
            new Command {ID = 0x308D, Name = "Crackdown"},
            new Command {ID = 0x308E, Name = "Eject"},
            new Command {ID = 0x308F, Name = "Unhinge"},
            new Command {ID = 0x3090, Name = "Intimidate"},
            new Command {ID = 0x3091, Name = "Envenom"},
            new Command {ID = 0x3092, Name = "Hurt"},
            new Command {ID = 0x3093, Name = "Darkness Dance"},
            new Command {ID = 0x3094, Name = "Samba of Silence"},
            new Command {ID = 0x3095, Name = "MP Mambo"},
            new Command {ID = 0x3096, Name = "Magical Masque"},
            new Command {ID = 0x3097, Name = "Sleepy Shuffle"},
            new Command {ID = 0x3098, Name = "Carnival Cancan"},
            new Command {ID = 0x3099, Name = "Slowdance"},
            new Command {ID = 0x309A, Name = "Brakedance"},
            new Command {ID = 0x309B, Name = "Jitterbug"},
            new Command {ID = 0x309C, Name = "Dirty Dancing"},
            new Command {ID = 0x309D, Name = "Battle Cry"},
            new Command {ID = 0x309E, Name = "Cantus Firmus"},
            new Command {ID = 0x309F, Name = "Esoteric Melody"},
            new Command {ID = 0x30A0, Name = "Disenchant"},
            new Command {ID = 0x30A1, Name = "Perfect Pitch"},
            new Command {ID = 0x30A2, Name = "Matador's Song"},
            new Command {ID = 0x30A3, Name = "Focus"},
            new Command {ID = 0x30A4, Name = "MP Absorb"},
            new Command {ID = 0x30A5, Name = "Fire"},
            new Command {ID = 0x30A6, Name = "Blizzard"},
            new Command {ID = 0x30A7, Name = "Thunder"},
            new Command {ID = 0x30A8, Name = "Water"},
            new Command {ID = 0x30A9, Name = "Fira"},
            new Command {ID = 0x30AA, Name = "Blizzara"},
            new Command {ID = 0x30AB, Name = "Thundara"},
            new Command {ID = 0x30AC, Name = "Watera"},
            new Command {ID = 0x30AD, Name = "Firaga"},
            new Command {ID = 0x30AE, Name = "Blizzaga"},
            new Command {ID = 0x30AF, Name = "Thundaga"},
            new Command {ID = 0x30B0, Name = "Waterga"},
            new Command {ID = 0x30B1, Name = "Pray"},
            new Command {ID = 0x30B2, Name = "Vigor"},
            new Command {ID = 0x30B3, Name = "Cure"},
            new Command {ID = 0x30B4, Name = "Cura"},
            new Command {ID = 0x30B5, Name = "Curaga"},
            new Command {ID = 0x30B6, Name = "Regen"},
            new Command {ID = 0x30B7, Name = "Esuna"},
            new Command {ID = 0x30B8, Name = "Dispel"},
            new Command {ID = 0x30B9, Name = "Life"},
            new Command {ID = 0x30BA, Name = "Full-Life"},
            new Command {ID = 0x30BB, Name = "Shell"},
            new Command {ID = 0x30BC, Name = "Protect"},
            new Command {ID = 0x30BD, Name = "Reflect"},
            new Command {ID = 0x30BE, Name = "Full-Cure"},
            new Command {ID = 0x30BF, Name = "Steal"},
            new Command {ID = 0x30C0, Name = "Pilfer Gil"},
            new Command {ID = 0x30C1, Name = "Borrowed Time"},
            new Command {ID = 0x30C2, Name = "Pilfer HP"},
            new Command {ID = 0x30C3, Name = "Pilfer MP"},
            new Command {ID = 0x30C4, Name = "Sticky Fingers"},
            new Command {ID = 0x30C5, Name = "Master Thief"},
            new Command {ID = 0x30C6, Name = "Soul Swipe"},
            new Command {ID = 0x30C7, Name = "Steal Will"},
            new Command {ID = 0x30C8, Name = "Flee"},
            new Command {ID = 0x30C9, Name = "Kogoro Blaze"},
            new Command {ID = 0x30CA, Name = "Kogoro Freeze"},
            new Command {ID = 0x30CB, Name = "Kogoro Shock"},
            new Command {ID = 0x30CC, Name = "Kogoro Deluge"},
            new Command {ID = 0x30CD, Name = "Kogoro Strike"},
            new Command {ID = 0x30CE, Name = "Doom Kogoro"},
            new Command {ID = 0x30CF, Name = "Kogoro Cure"},
            new Command {ID = 0x30D0, Name = "Kogoro Remedy"},
            new Command {ID = 0x30D1, Name = "Holy Kogoro"},
            new Command {ID = 0x30D2, Name = "Pound!"},
            new Command {ID = 0x30D3, Name = "Ghiki Gouge"},
            new Command {ID = 0x30D4, Name = "Ghiki Gag"},
            new Command {ID = 0x30D5, Name = "Mugger Ghiki"},
            new Command {ID = 0x30D6, Name = "Pesky Ghiki"},
            new Command {ID = 0x30D7, Name = "Bully Ghiki"},
            new Command {ID = 0x30D8, Name = "Ghiki Meds"},
            new Command {ID = 0x30D9, Name = "Ghiki Pep"},
            new Command {ID = 0x30DA, Name = "Ghiki Cheer"},
            new Command {ID = 0x30DB, Name = "Sneaky Ghiki"},
            new Command {ID = 0x30DC, Name = "Swarm, Swarm!"},
            new Command {ID = 0x30DD, Name = "Poison Flurry"},
            new Command {ID = 0x30DE, Name = "Stone Flurry"},
            new Command {ID = 0x30DF, Name = "Death Flurry"},
            new Command {ID = 0x30E0, Name = "Flurry Guard"},
            new Command {ID = 0x30E1, Name = "Flurry Speed"},
            new Command {ID = 0x30E2, Name = "Flurry Shield"},
            new Command {ID = 0x30E3, Name = "HP Flurry"},
            new Command {ID = 0x30E4, Name = "Recovery Flurry"},
            new Command {ID = 0x30E5, Name = "Carrier Flurry"},
            new Command {ID = 0x30E6, Name = "Maulwings!"},
            new Command {ID = 0x30E7, Name = "Attack Reels"},
            new Command {ID = 0x30E8, Name = "Magic Reels"},
            new Command {ID = 0x30E9, Name = "Item Reels"},
            new Command {ID = 0x30EA, Name = "Random Reels"},
            new Command {ID = 0x30EB, Name = "Two Dice"},
            new Command {ID = 0x30EC, Name = "Four Dice"},
            new Command {ID = 0x30ED, Name = "Luck"},
            new Command {ID = 0x30EE, Name = "Felicity"},
            new Command {ID = 0x30EF, Name = "Tantalize"},
            new Command {ID = 0x30F0, Name = "Bribe"},
            new Command {ID = 0x30F1, Name = "Moogle Cure"},
            new Command {ID = 0x30F2, Name = "Moogle Regen"},
            new Command {ID = 0x30F3, Name = "Moogle Wall"},
            new Command {ID = 0x30F4, Name = "Moogle Life"},
            new Command {ID = 0x30F5, Name = "Moogle Curema"},
            new Command {ID = 0x30F6, Name = "Moogle Regenja"},
            new Command {ID = 0x30F7, Name = "Moogle Wallja"},
            new Command {ID = 0x30F8, Name = "Moogle Lifeja"},
            new Command {ID = 0x30F9, Name = "Moogle Jolt"},
            new Command {ID = 0x30FA, Name = "Moogle Beam"},
            new Command {ID = 0x30FB, Name = "Cait Fire"},
            new Command {ID = 0x30FC, Name = "Cait Blizzard"},
            new Command {ID = 0x30FD, Name = "Cait Thunder"},
            new Command {ID = 0x30FE, Name = "Cait Water"},
            new Command {ID = 0x30FF, Name = "Power Eraser"},
            new Command {ID = 0x3100, Name = "Armor Eraser"},
            new Command {ID = 0x3101, Name = "Magic Eraser"},
            new Command {ID = 0x3102, Name = "Mental Eraser"},
            new Command {ID = 0x3103, Name = "Speed Eraser"},
            new Command {ID = 0x3104, Name = "PuPu Platter"},
            new Command {ID = 0x3105, Name = "Sleep Knife"},
            new Command {ID = 0x3106, Name = "Dark Knife"},
            new Command {ID = 0x3107, Name = "Silence Knife"},
            new Command {ID = 0x3108, Name = "Poison Knife"},
            new Command {ID = 0x3109, Name = "Berserk Knife"},
            new Command {ID = 0x310A, Name = "Stop Knife"},
            new Command {ID = 0x310B, Name = "Stone Knife"},
            new Command {ID = 0x310C, Name = "Arsenic Knife"},
            new Command {ID = 0x310D, Name = "Quartet Knife"},
            new Command {ID = 0x310E, Name = "Cactling Gun"},
            new Command {ID = 0x310F, Name = "Heat Whirl"},
            new Command {ID = 0x3110, Name = "Ice Whirl"},
            new Command {ID = 0x3111, Name = "Electric Whirl"},
            new Command {ID = 0x3112, Name = "Aqua Whirl"},
            new Command {ID = 0x3113, Name = "Shield"},
            new Command {ID = 0x3114, Name = "Barrier"},
            new Command {ID = 0x3115, Name = "Libra"},
            new Command {ID = 0x3116, Name = "Flare Whirl"},
            new Command {ID = 0x3117, Name = "All-Life"},
            new Command {ID = 0x3118, Name = "Great Whirl"},
            new Command {ID = 0x3119, Name = "White Pollen"},
            new Command {ID = 0x311A, Name = "White Honey"},
            new Command {ID = 0x311B, Name = "Hard Leaves"},
            new Command {ID = 0x311C, Name = "Tough Nuts"},
            new Command {ID = 0x311D, Name = "Mirror Petals"},
            new Command {ID = 0x311E, Name = "Floral Rush"},
            new Command {ID = 0x311F, Name = "Floral Bomb"},
            new Command {ID = 0x3120, Name = "Fallal Bomb"},
            new Command {ID = 0x3121, Name = "Floral Magisol"},
            new Command {ID = 0x3122, Name = "Fallal Magisol"},
            new Command {ID = 0x3123, Name = "Right Stigma"},
            new Command {ID = 0x3124, Name = "Dream Pollen"},
            new Command {ID = 0x3125, Name = "Mad Seeds"},
            new Command {ID = 0x3126, Name = "Sticky Honey"},
            new Command {ID = 0x3127, Name = "Halfdeath Petals"},
            new Command {ID = 0x3128, Name = "Poison Leaves"},
            new Command {ID = 0x3129, Name = "Death Petals"},
            new Command {ID = 0x312A, Name = "Ash Floralysis"},
            new Command {ID = 0x312B, Name = "Panic Floralysis"},
            new Command {ID = 0x312C, Name = "Congealed Honey"},
            new Command {ID = 0x312D, Name = "Silent White"},
            new Command {ID = 0x312E, Name = "Left Stigma"},
            new Command {ID = 0x312F, Name = "Attack"},
            new Command {ID = 0x3130, Name = "Death Missile"},
            new Command {ID = 0x3131, Name = "Bio Missile"},
            new Command {ID = 0x3132, Name = "Break Missile"},
            new Command {ID = 0x3133, Name = "Berserk Missile"},
            new Command {ID = 0x3134, Name = "Stop Missile"},
            new Command {ID = 0x3135, Name = "Confuse Missile"},
            new Command {ID = 0x3136, Name = "Shockwave"},
            new Command {ID = 0x3137, Name = "Shockstorm"},
            new Command {ID = 0x3138, Name = "Revival"},
            new Command {ID = 0x3139, Name = "Vajra"},
            new Command {ID = 0x313A, Name = "Homing Ray"},
            new Command {ID = 0x313B, Name = "HP Repair"},
            new Command {ID = 0x313C, Name = "MP Repair"},
            new Command {ID = 0x313D, Name = "Howitzer"},
            new Command {ID = 0x313E, Name = "Sleep Shell"},
            new Command {ID = 0x313F, Name = "Slow Shell"},
            new Command {ID = 0x3140, Name = "Anti-Power Shell"},
            new Command {ID = 0x3141, Name = "Anti-Armor Shell"},
            new Command {ID = 0x3142, Name = "Scan"},
            new Command {ID = 0x3113, Name = "Shellter"},
            new Command {ID = 0x3144, Name = "Protector"},
            new Command {ID = 0x3145, Name = "Homing Ray"},
            new Command {ID = 0x3146, Name = "HP Repair"},
            new Command {ID = 0x3147, Name = "MP Repair"},
            new Command {ID = 0x3148, Name = "Howitzer"},
            new Command {ID = 0x3149, Name = "Blind Shell"},
            new Command {ID = 0x314A, Name = "Silence Shell"},
            new Command {ID = 0x314B, Name = "Anti-Magic Shell"},
            new Command {ID = 0x314C, Name = "Anti-Mental Shell"},
            new Command {ID = 0x314D, Name = "Booster"},
            new Command {ID = 0x314E, Name = "Offense"},
            new Command {ID = 0x314F, Name = "Defense"},
            new Command {ID = 0x3150, Name = "Aestus"},
            new Command {ID = 0x3151, Name = "Winterkill"},
            new Command {ID = 0x3152, Name = "Levin"},
            new Command {ID = 0x3153, Name = "Whelmen"},
            new Command {ID = 0x3154, Name = "Wisenen"},
            new Command {ID = 0x3155, Name = "Fiers"},
            new Command {ID = 0x3156, Name = "Deeth"},
            new Command {ID = 0x3157, Name = "Assoil"},
            new Command {ID = 0x3158, Name = "Fright"},
            new Command {ID = 0x3159, Name = "Sword Dance"},
            new Command {ID = 0x315A, Name = "Venom Wing"},
            new Command {ID = 0x315B, Name = "Blind Wing"},
            new Command {ID = 0x315C, Name = "Mute Wing"},
            new Command {ID = 0x315D, Name = "Rock Wing"},
            new Command {ID = 0x315E, Name = "Lazy Wing"},
            new Command {ID = 0x315F, Name = "Violent Wing"},
            new Command {ID = 0x3160, Name = "Still Wing"},
            new Command {ID = 0x3161, Name = "Crazy Wing"},
            new Command {ID = 0x3162, Name = "Stamina"},
            new Command {ID = 0x3163, Name = "Mettle"},
            new Command {ID = 0x3164, Name = "Reboot"},
            new Command {ID = 0x3165, Name = "Steel Feather"},
            new Command {ID = 0x3166, Name = "Diamond Feather"},
            new Command {ID = 0x3167, Name = "Pumice Feather"},
            new Command {ID = 0x3168, Name = "Ma'at's Feather"},
            new Command {ID = 0x3169, Name = "White Feather"},
            new Command {ID = 0x316A, Name = "Buckle Feather"},
            new Command {ID = 0x316B, Name = "Cloudy Feather"},
            new Command {ID = 0x316C, Name = "Pointed Feather"},
            new Command {ID = 0x316D, Name = "Stamina"},
            new Command {ID = 0x316E, Name = "Mettle"},
            new Command {ID = 0x316F, Name = "Reboot"},
            new Command {ID = 0x3170, Name = "Flare"},
            new Command {ID = 0x3171, Name = "Ultima"},
            new Command {ID = 0x3172, Name = "Holy"},
            new Command {ID = 0x3173, Name = "Auto-Life"},
            new Command {ID = 0x3174, Name = "Mug"},
            new Command {ID = 0x3175, Name = "Nab gil"},
            new Command {ID = 0x3176, Name = "Haste"},
            new Command {ID = 0x3177, Name = "Hastega"},
            new Command {ID = 0x3178, Name = "Blind"},
            new Command {ID = 0x3179, Name = "Silence"},
            new Command {ID = 0x317A, Name = "Sleep"},
            new Command {ID = 0x317B, Name = "Absorb MP"},
            new Command {ID = 0x317C, Name = "Absorb MP"}, //Not 100% sure about this one
            new Command {ID = 0x317D, Name = "(Nichts)"},
            new Command {ID = 0x317E, Name = "(Nichts)"},
            new Command {ID = 0x317F, Name = "(Nichts)"},
            new Command {ID = 0x3180, Name = "(Nichts)"},
            new Command {ID = 0x3181, Name = "Time Trip End"},
            new Command {ID = 0x3182, Name = "Final Damage"},
            new Command {ID = 0x3183, Name = "Pineapple"},
            new Command {ID = 0x3184, Name = "Potato Masher"},
            new Command {ID = 0x3185, Name = "Cluster Bomb"},
            new Command {ID = 0x3186, Name = "Sunburst"},
            new Command {ID = 0x3187, Name = "Blaster Mine"},
            new Command {ID = 0x3188, Name = "Hazardous Shell"},
            new Command {ID = 0x3189, Name = "Heat Blaster"},
            new Command {ID = 0x318A, Name = "Firestorm "},
            new Command {ID = 0x318B, Name = "Burning Soul"},
            new Command {ID = 0x318C, Name = "Brimstone"},
            new Command {ID = 0x318D, Name = "Abaddon Flame"},
            new Command {ID = 0x318E, Name = "Snow Flurry"},
            new Command {ID = 0x318F, Name = "Icefall"},
            new Command {ID = 0x3190, Name = "Winter Storm"},
            new Command {ID = 0x3191, Name = "Black Ice"},
            new Command {ID = 0x3192, Name = "Krysta"},
            new Command {ID = 0x3193, Name = "Thunderbolt"},
            new Command {ID = 0x3194, Name = "Rolling Thunder"},
            new Command {ID = 0x3195, Name = "Lightning Bolt"},
            new Command {ID = 0x3196, Name = "Electroshock"},
            new Command {ID = 0x3197, Name = "Thunderblast"},
            new Command {ID = 0x3198, Name = "Waterfall "},
            new Command {ID = 0x3199, Name = "Flash Flood"}, 
            new Command {ID = 0x319A, Name = "Tidal Wave"},
            new Command {ID = 0x319B, Name = "Aqua Toxin"},
            new Command {ID = 0x319C, Name = "Dark Rain"},
            new Command {ID = 0x319D, Name = "Nega Burst"},
            new Command {ID = 0x319E, Name = "Black Hole"},
            new Command {ID = 0x319F, Name = "Tallboy"},
            new Command {ID = 0x31A0, Name = "Grand Slam"},
            new Command {ID = 0x31A1, Name = "Archangel"},
            new Command {ID = 0x31A2, Name = "White Hole"},
            new Command {ID = 0x31A3, Name = "Remedy"},
            new Command {ID = 0x31A4, Name = "Panacea"},
            new Command {ID = 0x31A5, Name = "Ultra cure"},
            new Command {ID = 0x31A6, Name = "Mega Phoenix"},
            new Command {ID = 0x31A7, Name = "Final Phoenix"},
            new Command {ID = 0x31A8, Name = "Fantasy Phoenix"},
            new Command {ID = 0x31A9, Name = "Hi-Potion"},
            new Command {ID = 0x31AA, Name = "Mega-Potion"},
            new Command {ID = 0x31AB, Name = "Ultra-Potion"},
            new Command {ID = 0x31AC, Name = "Final Elixir"},
            new Command {ID = 0x31AD, Name = "Meteor Strike"},
            new Command {ID = 0x31AE, Name = "Chocobo Wing"},
            new Command {ID = 0x31AF, Name = "Soul Spring"},
            new Command {ID = 0x31B0, Name = "Soul Sea"},
            new Command {ID = 0x31B1, Name = "Wall"},
            new Command {ID = 0x31B2, Name = "Hi-Wall"},
            new Command {ID = 0x31B3, Name = "Final wall"},
            new Command {ID = 0x31B4, Name = "Mega vitality"},
            new Command {ID = 0x31B5, Name = "Mega Cocktail"},
            new Command {ID = 0x31B6, Name = "Mega Mana"},
            new Command {ID = 0x31B7, Name = "Hero Drink"},
            new Command {ID = 0x31B8, Name = "Miracle Drink"},
            new Command {ID = 0x31B9, Name = "Shin-Zantetsu"},
            new Command {ID = 0x31BA, Name = "Excalibur"},
            new Command {ID = 0x31BB, Name = "Cripple"},
            new Command {ID = 0x31BC, Name = "Delay Buster"},
            new Command {ID = 0x31BD, Name = "Intimidate"},
            new Command {ID = 0x31BE, Name = "Fireworks"},
            new Command {ID = 0x31BF, Name = "Clean Slate"},
            new Command {ID = 0x31C0, Name = "Power Break"},
            new Command {ID = 0x31C1, Name = "Eject"},
            new Command {ID = 0x31C2, Name = "Magicide"},
            new Command {ID = 0x31C3, Name = "Armor Break"},
            new Command {ID = 0x31C4, Name = "Ultima"},
            new Command {ID = 0x31C5, Name = "Black Sky"},
            new Command {ID = 0x31C6, Name = "Flare"},
            new Command {ID = 0x31C7, Name = "Firaga"},
            new Command {ID = 0x31C8, Name = "Auto-Life"},
            new Command {ID = 0x31C9, Name = "Demi"},
            new Command {ID = 0x31CA, Name = "Bio"},
            new Command {ID = 0x31CB, Name = "Thundara"},
            new Command {ID = 0x31CC, Name = "Esuna"},
            new Command {ID = 0x31CD, Name = "Break"},
            new Command {ID = 0x31CE, Name = "Cura"},
            new Command {ID = 0x31CF, Name = "Megalixir+"},
            new Command {ID = 0x31D0, Name = "Mighty Guard+"},
            new Command {ID = 0x31D1, Name = "Supremen Gem"},
            new Command {ID = 0x31D2, Name = "Blessed Gem"},
            new Command {ID = 0x31D3, Name = "Megalixir"},
            new Command {ID = 0x31D4, Name = "Mighty Guard"},
            new Command {ID = 0x31D5, Name = "Mega-Ether"},
            new Command {ID = 0x31D6, Name = "L-Bomb"},
            new Command {ID = 0x31D7, Name = "Ether"},
            new Command {ID = 0x31D8, Name = "Lunar Curtain+"},
            new Command {ID = 0x31D9, Name = "Light Curtain+"},
            new Command {ID = 0x31DA, Name = "CONGRATS!"},
            new Command {ID = 0x31DB, Name = "Mega-Potion"},
            new Command {ID = 0x31DC, Name = "Blizzaga"},
            new Command {ID = 0x31DD, Name = "Cry in the Night"},
            new Command {ID = 0x31DE, Name = "Dark Matter"},
            new Command {ID = 0x31DF, Name = "Quartet Knife"},
            new Command {ID = 0x31E0, Name = "Mental Break"},
            new Command {ID = 0x31E1, Name = "Cure"},
            new Command {ID = 0x31E2, Name = "Primo Grenade"},
            new Command {ID = 0x31E3, Name = "Hi-Potion"},
            new Command {ID = 0x31E4, Name = "Potion"},
            new Command {ID = 0x31E5, Name = "Dud"},
            new Command {ID = 0x31E6, Name = "Psycho Bomb"},
            new Command {ID = 0x31E7, Name = "Telekinesis"},
            new Command {ID = 0x31E8, Name = "Maser Eye"},
            new Command {ID = 0x31E9, Name = "Brain Storm"},
            new Command {ID = 0x31EA, Name = "Time Trip"},
            new Command {ID = 0x31EB, Name = "Express"},
            new Command {ID = 0x31EC, Name = "Magic Guard"},
            new Command {ID = 0x31ED, Name = "Physics Guard"},
            new Command {ID = 0x31EE, Name = "Teleport"},
            new Command {ID = 0x31EF, Name = "Excellence"},
            new Command {ID = 0x31F0, Name = "Psionics"},
            new Command {ID = 0x31F1, Name = "Festivities"},
            new Command {ID = 0x31F2, Name = "Festivities"},
            new Command {ID = 0x31F3, Name = "Festivities"},
            new Command {ID = 0x31F4, Name = "Spinner"},
            new Command {ID = 0x31F5, Name = "Spinner"},
            new Command {ID = 0x31F6, Name = "Spinner"},
            new Command {ID = 0x31F7, Name = "Popper"},
            new Command {ID = 0x31F8, Name = "Popper"},
            new Command {ID = 0x31F9, Name = "Popper"},
            new Command {ID = 0x31FA, Name = "Twinkler"},
            new Command {ID = 0x31FB, Name = "Twinkler"},
            new Command {ID = 0x31FC, Name = "Twinkler"},
            new Command {ID = 0x31FD, Name = "Fountain"},
            new Command {ID = 0x31FE, Name = "Fountain"},
            new Command {ID = 0x31FF, Name = "Fountain"},
            new Command {ID = 0x3200, Name = "Fire Sandals"},
            new Command {ID = 0x3201, Name = "Ice Sandals"},
            new Command {ID = 0x3202, Name = "Lightning Sandals"},
            new Command {ID = 0x3203, Name = "Water Sandals"},
            new Command {ID = 0x3204, Name = "Flare Sandals"},
            new Command {ID = 0x3205, Name = "Ultima Sandals"},
            new Command {ID = 0x3206, Name = "Fire fish"},
            new Command {ID = 0x3207, Name = "Ice fish"},
            new Command {ID = 0x3208, Name = "Lightning fish"},
            new Command {ID = 0x3209, Name = "Water fish"},
            new Command {ID = 0x320A, Name = "Gravity fish"},
            new Command {ID = 0x320B, Name = "Holy fish"},
            new Command {ID = 0x320C, Name = "Silence Mask"},
            new Command {ID = 0x320D, Name = "Darkness Mask"},
            new Command {ID = 0x320E, Name = "Poison Mask"},
            new Command {ID = 0x320F, Name = "Sleep Mask"},
            new Command {ID = 0x3210, Name = "Stop Mask"},
            new Command {ID = 0x3211, Name = "Petrify Mask"},
            new Command {ID = 0x3212, Name = "Fire"},
            new Command {ID = 0x3213, Name = "Fira"},
            new Command {ID = 0x3214, Name = "Firaga"},
            new Command {ID = 0x3215, Name = "Firaga 2"},
            new Command {ID = 0x3216, Name = "Blizzard"},
            new Command {ID = 0x3217, Name = "Blizzara"},
            new Command {ID = 0x3218, Name = "Blizzaga"},
            new Command {ID = 0x3219, Name = "Blizzaga 2"},
            new Command {ID = 0x321A, Name = "Thunder"},
            new Command {ID = 0x321B, Name = "Thundara"},
            new Command {ID = 0x321C, Name = "Thundaga"},
            new Command {ID = 0x321D, Name = "Thundaga 2"},
            new Command {ID = 0x321E, Name = "Water"},
            new Command {ID = 0x321F, Name = "Watera"},
            new Command {ID = 0x3220, Name = "Waterga"},
            new Command {ID = 0x3221, Name = "Waterga 2"},
            new Command {ID = 0x3222, Name = "Sleep"},
            new Command {ID = 0x3223, Name = "Berserk"},
            new Command {ID = 0x3224, Name = "Break"},
            new Command {ID = 0x3225, Name = "Flare"},
            new Command {ID = 0x3226, Name = "Silence"},
            new Command {ID = 0x3227, Name = "Blind"},
            new Command {ID = 0x3228, Name = "Death"},
            new Command {ID = 0x3229, Name = "Ultima"},
            new Command {ID = 0x4000, Name = "Attack"},
            new Command {ID = 0x4001, Name = "Attack"},
            new Command {ID = 0x4002, Name = "Annoyed by the long battle"},
            new Command {ID = 0x4003, Name = "Attack"},
            new Command {ID = 0x4004, Name = "Poison Attack"},
            new Command {ID = 0x4005, Name = "Sleep Attack"},
            new Command {ID = 0x4006, Name = "Silence Attack"},
            new Command {ID = 0x4007, Name = "Confuse Attack"},
            new Command {ID = 0x4008, Name = "Dark Attack"},
            new Command {ID = 0x4009, Name = "Slow Attack"},
            new Command {ID = 0x400A, Name = "Stop Attack"},
            new Command {ID = 0x400B, Name = "Delay Shock"},
            new Command {ID = 0x400C, Name = "Curse Attack"},
            new Command {ID = 0x400D, Name = "Heartless Attack"},
            new Command {ID = 0x400E, Name = "Attack"},
            new Command {ID = 0x400F, Name = "Kill Attack"},
            new Command {ID = 0x4010, Name = "Drain Attack"},
            new Command {ID = 0x4011, Name = "Very annoyed by the long battle"},
            new Command {ID = 0x4012, Name = "Attack"},
            new Command {ID = 0x4013, Name = "MP Buster"},
            new Command {ID = 0x4014, Name = "Attack"},
            new Command {ID = 0x4015, Name = "Critical Attack"},
            new Command {ID = 0x4016, Name = "Sleep Needle"},
            new Command {ID = 0x4017, Name = "Poison Needle"},
            new Command {ID = 0x4018, Name = "Triple Shock"},
            new Command {ID = 0x4019, Name = "Seed Cannon"},
            new Command {ID = 0x401A, Name = "Heavy seed cannon"},
            new Command {ID = 0x401B, Name = "Seed Burst"},
            new Command {ID = 0x401C, Name = "Stony Glare"},
            new Command {ID = 0x401D, Name = "Readying Quake"},
            new Command {ID = 0x401E, Name = "Earthquake"},
            new Command {ID = 0x401F, Name = "Umbral Gaze"},
            new Command {ID = 0x4020, Name = "Lingering Gaze"},
            new Command {ID = 0x4021, Name = "Lingering Gaze"},
            new Command {ID = 0x4022, Name = "Halting Gaze"},
            new Command {ID = 0x4023, Name = "Supersonic wave"},
            new Command {ID = 0x4024, Name = "Sonic Boom"},
            new Command {ID = 0x4025, Name = "Sonic Storm"},
            new Command {ID = 0x4026, Name = "Attack"},
            new Command {ID = 0x4027, Name = "Attack"},
            new Command {ID = 0x4028, Name = "Supersonic Wave"},
            new Command {ID = 0x4029, Name = "Rifle"},
            new Command {ID = 0x402A, Name = "Rifle"},
            new Command {ID = 0x402B, Name = "Flamethrower"},
            new Command {ID = 0x402C, Name = "Heel Drop"},
            new Command {ID = 0x402D, Name = "Thrust Kick"},
            new Command {ID = 0x402E, Name = "Squirt Gun"},
            new Command {ID = 0x402F, Name = "Breath"},
            new Command {ID = 0x4030, Name = "Breath"},
            new Command {ID = 0x4031, Name = "Breath"},
            new Command {ID = 0x4032, Name = "Pyroplexy"},
            new Command {ID = 0x4033, Name = "Fire weapon"},
            new Command {ID = 0x4034, Name = "Support fire"},
            new Command {ID = 0x4035, Name = "Bombardment"},
            new Command {ID = 0x4036, Name = "Support Bombardment"},
            new Command {ID = 0x4037, Name = "Distortion wave"},
            new Command {ID = 0x4038, Name = "Judgment"},
            new Command {ID = 0x4039, Name = "Punishment"},
            new Command {ID = 0x403A, Name = "Supernova"},
            new Command {ID = 0x403B, Name = "Die"},
            new Command {ID = 0x403C, Name = "Die"},
            new Command {ID = 0x403D, Name = "Skewer"},
            new Command {ID = 0x403E, Name = "Fire Breath"},
            new Command {ID = 0x403F, Name = "Fire Burst"},
            new Command {ID = 0x4040, Name = "Absorb"},
            new Command {ID = 0x4041, Name = "Stone"},
            new Command {ID = 0x4042, Name = "Blow"},
            new Command {ID = 0x4043, Name = "Anger"},
            new Command {ID = 0x4044, Name = "Madness"},
            new Command {ID = 0x4045, Name = "Stone Breath"},
            new Command {ID = 0x4046, Name = "Curse"},
            new Command {ID = 0x4047, Name = "Attack"},
            new Command {ID = 0x4048, Name = "Reaper"},
            new Command {ID = 0x4049, Name = "Skullcracker"},
            new Command {ID = 0x404A, Name = "Skullcracker"},
            new Command {ID = 0x404B, Name = "Electrocute"},
            new Command {ID = 0x404C, Name = "Ochu Jiggle"},
            new Command {ID = 0x404D, Name = "Ochu Dance"},
            new Command {ID = 0x404E, Name = "Ebon Powder"},
            new Command {ID = 0x404F, Name = "Nausea Powder"},
            new Command {ID = 0x4050, Name = "Pernicious Powder"},
            new Command {ID = 0x4051, Name = "El Nino "},
            new Command {ID = 0x4052, Name = "La Nina "},
            new Command {ID = 0x4053, Name = "1000 Needles"},
            new Command {ID = 0x4054, Name = "10000 Needles"},
            new Command {ID = 0x4055, Name = "Escape"},
            new Command {ID = 0x4056, Name = "Blast Punch "},
            new Command {ID = 0x4057, Name = "Haymaker"},
            new Command {ID = 0x4058, Name = "Stony Glare"},
            new Command {ID = 0x4059, Name = "Lazy Eye"},
            new Command {ID = 0x405A, Name = "Heavens Cataract (Boss ver.)"},
            new Command {ID = 0x405B, Name = "Thanatos Emblem"},
            new Command {ID = 0x405C, Name = "ecstasy"},
            new Command {ID = 0x405D, Name = "Two Hands"},
            new Command {ID = 0x405E, Name = "Counterattack"},
            new Command {ID = 0x405F, Name = "Die"},
            new Command {ID = 0x4060, Name = "Die"},
            new Command {ID = 0x4061, Name = "Expand2"},
            new Command {ID = 0x4062, Name = "Expand3"},
            new Command {ID = 0x4063, Name = "Expand4"},
            new Command {ID = 0x4064, Name = "Rush"},
            new Command {ID = 0x4065, Name = "Tick-tick-BOOM!"},
            new Command {ID = 0x4066, Name = "Kaboom!"},
            new Command {ID = 0x4067, Name = "Crackaboom!"},
            new Command {ID = 0x4068, Name = "Kercrackaboom!"},//EN
            new Command {ID = 0x4069, Name = "Full Life"},
            new Command {ID = 0x406A, Name = "Berserk"},
            new Command {ID = 0x406B, Name = "Haste"},
            new Command {ID = 0x406C, Name = "Slow"},
            new Command {ID = 0x406D, Name = "Osmose"},
            new Command {ID = 0x406E, Name = "Sleep"},
            new Command {ID = 0x406F, Name = "Blind"},
            new Command {ID = 0x4070, Name = "Confuse"},
            new Command {ID = 0x4071, Name = "Silence"},
            new Command {ID = 0x4072, Name = "Break"},
            new Command {ID = 0x4073, Name = "Doom"},
            new Command {ID = 0x4074, Name = "Rush"},
            new Command {ID = 0x4075, Name = "Aqua Breath"},
            new Command {ID = 0x4076, Name = "Chaos flame"},
            new Command {ID = 0x4077, Name = "Bad Breath"},
            new Command {ID = 0x4078, Name = "Really Bad Breath"},
            new Command {ID = 0x4079, Name = "Gastric Juice"},
            new Command {ID = 0x407A, Name = "Chomp"},
            new Command {ID = 0x407B, Name = "Staccato"},
            new Command {ID = 0x407C, Name = "Attack"},
            new Command {ID = 0x407D, Name = "Blade Rondo"},
            new Command {ID = 0x407E, Name = "Karma"},
            new Command {ID = 0x407F, Name = "Tremor"},
            new Command {ID = 0x4080, Name = "Adamant Breath"},
            new Command {ID = 0x4081, Name = "Uppercut"},
            new Command {ID = 0x4082, Name = "Tyrant Tail"},
            new Command {ID = 0x4083, Name = "Meteor"},
            new Command {ID = 0x4084, Name = "Might Guard"},
            new Command {ID = 0x4085, Name = "Might Guard G"},
            new Command {ID = 0x4086, Name = "Not-So-Mighty Guard"},
            new Command {ID = 0x4087, Name = "White Wind"},
            new Command {ID = 0x4088, Name = "White Highwind"},
            new Command {ID = 0x4089, Name = "Blaster"},
            new Command {ID = 0x408A, Name = "Death Blast"},
            new Command {ID = 0x408B, Name = "Body Splash"},
            new Command {ID = 0x408C, Name = "Storm Cannon"},
            new Command {ID = 0x408D, Name = "Poison Mist"},
            new Command {ID = 0x408E, Name = "Poison Smog"},
            new Command {ID = 0x408F, Name = "Gatling Seed"},
            new Command {ID = 0x4090, Name = "Fire Burst"},
            new Command {ID = 0x4091, Name = "Energy Ray"},
            new Command {ID = 0x4092, Name = "Sonic Wings"},
            new Command {ID = 0x4093, Name = "Energy Blast"},
            new Command {ID = 0x4094, Name = "Hellfire"},
            new Command {ID = 0x4095, Name = "Meteor Strike"},
            new Command {ID = 0x4096, Name = "Aerospark"},
            new Command {ID = 0x4097, Name = "Thor's Hammer"},
            new Command {ID = 0x4098, Name = "Recharge"},
            new Command {ID = 0x4099, Name = "Heavenly Strike"},
            new Command {ID = 0x409A, Name = "Diamond Dust"},
            new Command {ID = 0x409B, Name = "Impulse"},
            new Command {ID = 0x409C, Name = "Mega Flare"},
            new Command {ID = 0x409D, Name = "Anima Attack"},
            new Command {ID = 0x409E, Name = "Pain"},
            new Command {ID = 0x409F, Name = "Obvilion"},
            new Command {ID = 0x40A0, Name = "Daigoro"},
            new Command {ID = 0x40A1, Name = "Kozuka"},
            new Command {ID = 0x40A2, Name = "Wakizashi (Single-Target)"},
            new Command {ID = 0x40A3, Name = "Wakizashi (Multi-Target)"},
            new Command {ID = 0x40A4, Name = "Zanmato"},
            new Command {ID = 0x40A5, Name = "Daigoro"},
            new Command {ID = 0x40A6, Name = "Razzia"},
            new Command {ID = 0x40A7, Name = "Camisade"},
            new Command {ID = 0x40A8, Name = "Passado"},
            new Command {ID = 0x40A9, Name = "Delta Attack"},
            new Command {ID = 0x40AA, Name = "Calamity"},
            new Command {ID = 0x40AB, Name = "Mighty Guard"},
            new Command {ID = 0x40AC, Name = "Heaven's Caratact"},
            new Command {ID = 0x40AD, Name = "Die"},
            new Command {ID = 0x40AE, Name = "Die"},
            new Command {ID = 0x40AF, Name = "Die"},
            new Command {ID = 0x40B0, Name = "Die"},
            new Command {ID = 0x40B1, Name = "Die"},
            new Command {ID = 0x40B2, Name = "Die"},
            new Command {ID = 0x40B3, Name = "Die"},
            new Command {ID = 0x40B4, Name = "Die"},
            new Command {ID = 0x40B5, Name = "Die"},
            new Command {ID = 0x40B6, Name = "Attack"},
            new Command {ID = 0x40B7, Name = "Aqua Breath"},
            new Command {ID = 0x40B8, Name = "Chaos Flame"},
            new Command {ID = 0x40B9, Name = "Gunk"},
            new Command {ID = 0x40BA, Name = "Megaton Press"},
            new Command {ID = 0x40BB, Name = "Broken Shell"},
            new Command {ID = 0x40BC, Name = "Broken Shell 2"},
            new Command {ID = 0x40BD, Name = "Die"},
            new Command {ID = 0x40BE, Name = "Revolver"},
            new Command {ID = 0x40BF, Name = "Full-Auto"},
            new Command {ID = 0x40C0, Name = "Killer Fang"},
            new Command {ID = 0x40C1, Name = "Poison Fang"},
            new Command {ID = 0x40C2, Name = "Stone Fang"},
            new Command {ID = 0x40C3, Name = "Curse Fang"},
            new Command {ID = 0x40C4, Name = "Mind Fang"},
            new Command {ID = 0x40C5, Name = "helm Counter"},
            new Command {ID = 0x40C6, Name = "Chef's Knife"},
            new Command {ID = 0x40C7, Name = "Spider Attack"},
            new Command {ID = 0x40C8, Name = "Sticky End"},
            new Command {ID = 0x40C9, Name = "Gooey End"},
            new Command {ID = 0x40CA, Name = "Sipder Bite"},
            new Command {ID = 0x40CB, Name = "Mind Pecker"},
            new Command {ID = 0x40CC, Name = "Impale"},
            new Command {ID = 0x40CD, Name = "Blackout"},
            new Command {ID = 0x40CE, Name = "Mute"},
            new Command {ID = 0x40CF, Name = "Pollute"},
            new Command {ID = 0x40D0, Name = "Cease and Desist"},
            new Command {ID = 0x40D1, Name = "Dying Star"},
            new Command {ID = 0x40D2, Name = "Falling leaf"},
            new Command {ID = 0x40D3, Name = "Thundering wave"},
            new Command {ID = 0x40D4, Name = "Beguiling Mire"},
            new Command {ID = 0x40D5, Name = "Waning Moon"},
            new Command {ID = 0x40D6, Name = "Choking Mist"},
            new Command {ID = 0x40D7, Name = "Rend"},
            new Command {ID = 0x40D8, Name = "Flame Breath"},
            new Command {ID = 0x40D9, Name = "Tail Smash"},
            new Command {ID = 0x40DA, Name = "Damocles Photon"},
            new Command {ID = 0x40DB, Name = "Bated Breath"},
            new Command {ID = 0x40DC, Name = "Die"},
            new Command {ID = 0x40DD, Name = "Die"},
            new Command {ID = 0x40DE, Name = "Die"},
            new Command {ID = 0x40DF, Name = "Attack"},
            new Command {ID = 0x40E0, Name = "Attack"},
            new Command {ID = 0x40E1, Name = "Barrier Shift"},
            new Command {ID = 0x40E2, Name = "Die"},
            new Command {ID = 0x40E3, Name = "Attack"},
            new Command {ID = 0x40E4, Name = "Pirouette Pitch"},
            new Command {ID = 0x40E5, Name = "Supercollider"},
            new Command {ID = 0x40E6, Name = "Huggles"},
            new Command {ID = 0x40E7, Name = "1H Pistol"},
            new Command {ID = 0x40E8, Name = "Hail of Bullets"},
            new Command {ID = 0x40E9, Name = "Russian Roulette"},
            new Command {ID = 0x40EA, Name = "Russian Roulette"},
            new Command {ID = 0x40EB, Name = "Russian Roulette"},
            new Command {ID = 0x40EC, Name = "Genesis"},
            new Command {ID = 0x40ED, Name = "Big Bang"},
            new Command {ID = 0x40EE, Name = "Russian Roulette"},
            new Command {ID = 0x40EF, Name = "Russian Roulette"},
            new Command {ID = 0x40F0, Name = "Russian Roulette"},
            new Command {ID = 0x40F1, Name = "Potion"},
            new Command {ID = 0x40F2, Name = "Fan"},
            new Command {ID = 0x40F3, Name = "Sonic Fan"},
            new Command {ID = 0x40F4, Name = "Mach Fan"},
            new Command {ID = 0x40F5, Name = "Love tap"},
            new Command {ID = 0x40F6, Name = "No Love Lost"},
            new Command {ID = 0x40F7, Name = "None"},
            new Command {ID = 0x40F8, Name = "None"},
            new Command {ID = 0x40F9, Name = "Live Grenade"},
            new Command {ID = 0x40FA, Name = "Concusive shock"},
            new Command {ID = 0x40FB, Name = "Concussive Blast"},
            new Command {ID = 0x40FC, Name = "Sorry!"},
            new Command {ID = 0x40FD, Name = "Flash Bomb"},
            new Command {ID = 0x40FE, Name = "Hush Grenade"},
            new Command {ID = 0x40FF, Name = "Harbinger"},
            new Command {ID = 0x4100, Name = "Chain Attack"},
            new Command {ID = 0x4101, Name = "Glint"},
            new Command {ID = 0x4102, Name = "Looming Glacier"},
            new Command {ID = 0x4103, Name = "Drill Shot"},
            new Command {ID = 0x4104, Name = "Potion Plus"},
            new Command {ID = 0x4105, Name = "Triple Play!"},
            new Command {ID = 0x4106, Name = "Benchwarmer"},
            new Command {ID = 0x4107, Name = "Night Game"},
            new Command {ID = 0x4108, Name = "Bite the Bullet"},
            new Command {ID = 0x4109, Name = "Die"},
            new Command {ID = 0x410A, Name = "Choco-Kick"},
            new Command {ID = 0x410B, Name = "Choco-Cure"},
            new Command {ID = 0x410C, Name = "Choco-Shell"},
            new Command {ID = 0x410D, Name = "Choco-Protect"},
            new Command {ID = 0x410E, Name = "Choco-Meteo"},
            new Command {ID = 0x410F, Name = "Flee"},
            new Command {ID = 0x4110, Name = "Happy"},
            new Command {ID = 0x4111, Name = "Attack"},
            new Command {ID = 0x4112, Name = "Mortar"},
            new Command {ID = 0x4113, Name = "Grinder"},
            new Command {ID = 0x4114, Name = "Bullseye"},
            new Command {ID = 0x4115, Name = "Rippling Chroma"},
            new Command {ID = 0x4116, Name = "Greedy Aura"},
            new Command {ID = 0x4117, Name = "Lightfall"},
            new Command {ID = 0x4118, Name = "Spin Cut"},
            new Command {ID = 0x4119, Name = "Hit & Run"},
            new Command {ID = 0x411A, Name = "Force Rain"},
            new Command {ID = 0x411B, Name = "Terror of Zanarkand"},
            new Command {ID = 0x411C, Name = "Bane Lance"},
            new Command {ID = 0x411D, Name = "MP Blowout"},
            new Command {ID = 0x411E, Name = "Precision Strike"},
            new Command {ID = 0x411F, Name = "Chain Attack"},
            new Command {ID = 0x4120, Name = "Mega-Potion"},
            new Command {ID = 0x4121, Name = "Rocket Launcher"},
            new Command {ID = 0x4122, Name = "Rocket Launcher"},
            new Command {ID = 0x4123, Name = "Rocket Launcher"},
            new Command {ID = 0x4124, Name = "Rocket Launcher"},
            new Command {ID = 0x4125, Name = "Lifeslicer"},
            new Command {ID = 0x4126, Name = "Annihilator"},
            new Command {ID = 0x4127, Name = "Die"},
            new Command {ID = 0x4128, Name = "Meteor"},
            new Command {ID = 0x4129, Name = "Punch"},
            new Command {ID = 0x412A, Name = "Glimmer of Despair"}, //EN
            new Command {ID = 0x412B, Name = "Bloody Breath"},
            new Command {ID = 0x412C, Name = "Unnatural selection"},
            new Command {ID = 0x412D, Name = "Perdition's Flame"},
            new Command {ID = 0x412E, Name = "Die"},
            new Command {ID = 0x412F, Name = "Noli Me Tangere"},//EN
            new Command {ID = 0x4130, Name = "Tail Beam"},
            new Command {ID = 0x4131, Name = "Vita Brevis"}, //EN
            new Command {ID = 0x4132, Name = "Missile"},
            new Command {ID = 0x4133, Name = "Dies Irae"}, //EN
            new Command {ID = 0x4134, Name = "Hostile activity detected."},
            new Command {ID = 0x4135, Name = "Hostile activity detected."},
            new Command {ID = 0x4136, Name = "Physical attack detected."},
            new Command {ID = 0x4137, Name = "Magic attack detected."},
            new Command {ID = 0x4138, Name = "Physical attack detected."},
            new Command {ID = 0x4139, Name = "Magic attack detected."},
            new Command {ID = 0x413A, Name = "Memento Mori"},//EN
            new Command {ID = 0x413B, Name = "Charge Core"},
            new Command {ID = 0x413C, Name = "Die"},
            new Command {ID = 0x413D, Name = "Pallida Mors"}, //EN
            new Command {ID = 0x413E, Name = "Lacrimosa"},//EN
            new Command {ID = 0x413F, Name = "Lacrimosa"},//EN
            new Command {ID = 0x4140, Name = "Odi et Amo"},//EN
            new Command {ID = 0x4141, Name = "Mors Certa"},//EN
            new Command {ID = 0x4142, Name = "Nemo Ante Mortem Beatus"}, //EN
            new Command {ID = 0x4143, Name = "Die"},
            new Command {ID = 0x4144, Name = "Acta Est Fabula"}, //EN
            new Command {ID = 0x4145, Name = "Shatter Potion"},
            new Command {ID = 0x4146, Name = "Shatter Hi-Potion"},
            new Command {ID = 0x4147, Name = "Shatter Ether"},
            new Command {ID = 0x4148, Name = "Destory Elixir"},
            new Command {ID = 0x4149, Name = "Destory Phoenix Down"},
            new Command {ID = 0x414A, Name = "Shatter Turbe Ether"},
            new Command {ID = 0x414B, Name = "Double Attack"},
            new Command {ID = 0x414C, Name = "Triple Attack"},
            new Command {ID = 0x414D, Name = "Quadruple Attack"},
            new Command {ID = 0x414E, Name = "Quintuple Attack"},
            new Command {ID = 0x414F, Name = "Sextuple Attack"},
            new Command {ID = 0x4150, Name = "Storm Cannon"},
            new Command {ID = 0x4151, Name = "100 Gill-Gnasher"},
            new Command {ID = 0x4152, Name = "1000 Gill-Gnasher"},
            new Command {ID = 0x4153, Name = "Blight Wing"},
            new Command {ID = 0x4154, Name = "Silent Wing"},
            new Command {ID = 0x4155, Name = "Wild Wing"},
            new Command {ID = 0x4156, Name = "Quick Wing"},
            new Command {ID = 0x4157, Name = "Muddle Wing"},
            new Command {ID = 0x4158, Name = "Desperate strike"},
            new Command {ID = 0x4159, Name = "Sharpened Needle"},
            new Command {ID = 0x415A, Name = "Magic Up"},
            new Command {ID = 0x415B, Name = "Magic down"},
            new Command {ID = 0x415C, Name = "MP Crush"},
            new Command {ID = 0x415D, Name = "Stampede"},
            new Command {ID = 0x415E, Name = "Magic Up"},
            new Command {ID = 0x415F, Name = "Magic Down"},
            new Command {ID = 0x4160, Name = "Scum Spray"},
            new Command {ID = 0x4161, Name = "Sludge Spray"},
            new Command {ID = 0x4162, Name = "Attack command scrambler"},
            new Command {ID = 0x4163, Name = "Recovery command scrambler"},
            new Command {ID = 0x4164, Name = "Special command scrambler"},
            new Command {ID = 0x4165, Name = "Trasmitting log..."},
            new Command {ID = 0x4166, Name = "Brute Force"},
            new Command {ID = 0x4167, Name = "Secret Stamina Tonic"},
            new Command {ID = 0x4168, Name = "Secret Hi-Potion"},
            new Command {ID = 0x4169, Name = "Secret Hero Drink"},
            new Command {ID = 0x416A, Name = "Secret Dark Matter"},
            new Command {ID = 0x416B, Name = "Futile Resistance"},
            new Command {ID = 0x416C, Name = "Potion Vortex"},
            new Command {ID = 0x416D, Name = "Hi-Potion Vortex"},
            new Command {ID = 0x416E, Name = "Phoenix Down Vortex"},
            new Command {ID = 0x416F, Name = "Chicken Wing Lv.1"},
            new Command {ID = 0x4170, Name = "Chicken Wing Lv.2"},
            new Command {ID = 0x4171, Name = "Chicken Wing Lv.3"},
            new Command {ID = 0x4172, Name = "MP Break"},
            new Command {ID = 0x4173, Name = "Destroy Soft"},
            new Command {ID = 0x4174, Name = "Destroy Remedy"},
            new Command {ID = 0x4175, Name = "Hunter's Gaze"},
            new Command {ID = 0x4176, Name = "Frenzied Edge"},
            new Command {ID = 0x4177, Name = "Rip to Shreds"},
            new Command {ID = 0x4178, Name = "Rage of the Earth"},
            new Command {ID = 0x4179, Name = "Sorrow of the Earth"},
            new Command {ID = 0x417A, Name = "Negate Fire"},
            new Command {ID = 0x417B, Name = "Negate water"},
            new Command {ID = 0x417C, Name = "Negate Lightning"},
            new Command {ID = 0x417D, Name = "Negate Ice"},
            new Command {ID = 0x417E, Name = "Absorb Fire"},
            new Command {ID = 0x417F, Name = "Absorb water"},
            new Command {ID = 0x4180, Name = "Absorb Lightning"},
            new Command {ID = 0x4181, Name = "Absorb Ice"},
            new Command {ID = 0x4182, Name = "Negate Fire disabled"},
            new Command {ID = 0x4183, Name = "Negate Water disabled"},
            new Command {ID = 0x4184, Name = "Negate Lightning disabled"},
            new Command {ID = 0x4185, Name = "Negate Ice disabled"},
            new Command {ID = 0x4186, Name = "Absorb Fire disabled."},
            new Command {ID = 0x4187, Name = "Absorb Water disabled."},
            new Command {ID = 0x4188, Name = "Absorb Lightning disabled."},
            new Command {ID = 0x4189, Name = "Absorb Ice disabled."},
            new Command {ID = 0x418A, Name = "Eyeing Yuna..."},
            new Command {ID = 0x418B, Name = "Eyeing Paine..."},
            new Command {ID = 0x418C, Name = "Eyeing Rikku..."},
            new Command {ID = 0x418D, Name = "Mode: Hyperdrive!"},
            new Command {ID = 0x418E, Name = "10000 Gil Smoosher"},
            new Command {ID = 0x418F, Name = "Gathering Strength..."},
            new Command {ID = 0x4190, Name = "Still gathering strength..."},
            new Command {ID = 0x4191, Name = "Whole Lotta Strength!"},
            new Command {ID = 0x4192, Name = "Bruiser Tail"},
            new Command {ID = 0x4193, Name = "Crushing Tail"},
            new Command {ID = 0x4194, Name = "Megaton Tail"},
            new Command {ID = 0x4195, Name = "Halitosis"}, //EN
            new Command {ID = 0x4196, Name = "Ingest Antidotes"},
            new Command {ID = 0x4197, Name = "Ingest Eye Drops"},
            new Command {ID = 0x4198, Name = "Ingest Echo Screen"},
            new Command {ID = 0x4199, Name = "Ingest Holy Waters"},
            new Command {ID = 0x419A, Name = "Ingest Remedy"},
            new Command {ID = 0x419B, Name = "Tempus Laxit"},
            new Command {ID = 0x419C, Name = "Bio mode"},
            new Command {ID = 0x419D, Name = "Silence mode"},
            new Command {ID = 0x419E, Name = "Curse mode"},
            new Command {ID = 0x419F, Name = "COPY mode"},
            new Command {ID = 0x41A0, Name = "OFF mode"},
            new Command {ID = 0x41A1, Name = "Bio Punch"},
            new Command {ID = 0x41A2, Name = "Silence Punch"},
            new Command {ID = 0x41A3, Name = "Curse Punch"},
            new Command {ID = 0x41A4, Name = "Quick Attack"},
            new Command {ID = 0x41A5, Name = "Quick Flare"},
            new Command {ID = 0x41A6, Name = "Radular Grudge"},
            new Command {ID = 0x41A7, Name = "Anti-Dressphere"},
            new Command {ID = 0x41A8, Name = "Tired of that dressphere!"},
            new Command {ID = 0x41A9, Name = "Tired of Yuna!"},
            new Command {ID = 0x41AA, Name = "Tired of Rikku!"},
            new Command {ID = 0x41AB, Name = "Tired of Paine!"},
            new Command {ID = 0x41AC, Name = "Bated Breath"},
            new Command {ID = 0x41AD, Name = "Breath of the Gorgon"},
            new Command {ID = 0x41AE, Name = "Ground-Breaker"},
            new Command {ID = 0x41AF, Name = "Bombardment"},
            new Command {ID = 0x41B0, Name = "Slurp"},
            new Command {ID = 0x41B1, Name = "Tentacle Slap"},
            new Command {ID = 0x41B2, Name = "No sign"},
            new Command {ID = 0x41B3, Name = "No sign"},
            new Command {ID = 0x41B4, Name = "Die"},
            new Command {ID = 0x41B5, Name = "Thunder Breath"},
            new Command {ID = 0x41B6, Name = "Hug Bomb"},
            new Command {ID = 0x41B7, Name = "Flame Breath!"},
            new Command {ID = 0x41B8, Name = "Ice Breath!"},
            new Command {ID = 0x41B9, Name = "3000-Needle Special"},
            new Command {ID = 0x41BA, Name = "No sign"},
            new Command {ID = 0x41BB, Name = "Me no like you!"},
            new Command {ID = 0x41BC, Name = "Quiet Meridian"},
            new Command {ID = 0x41BD, Name = "Blinding Meridian"},
            new Command {ID = 0x41BE, Name = "Maddening Meridian"},
            new Command {ID = 0x41BF, Name = "Chilly Meridian"},
            new Command {ID = 0x41C0, Name = "Burning Meridian"},
            new Command {ID = 0x41C1, Name = "Drowning Meridian"},
            new Command {ID = 0x41C2, Name = "Tingling Meridian"},
            new Command {ID = 0x41C3, Name = "Cry in the night"},
            new Command {ID = 0x41C4, Name = "Final Impact"},
            new Command {ID = 0x41C5, Name = "Me no like dressphere!"},
            new Command {ID = 0x41C6, Name = "Oversoul Fever"},
            new Command {ID = 0x41C7, Name = "Sorcery Ray"},
            new Command {ID = 0x41C8, Name = "Gatling gun"},
            new Command {ID = 0x41C9, Name = "Gun-Hater"},
            new Command {ID = 0x41CA, Name = "Sword-Hater"},
            new Command {ID = 0x41CB, Name = "Mage-Hater"},
            new Command {ID = 0x41CC, Name = "Gun Payback"},
            new Command {ID = 0x41CD, Name = "Sword Payback"},
            new Command {ID = 0x41CE, Name = "Mage Payback"},
            new Command {ID = 0x41CF, Name = "Samurai Payback"},
            new Command {ID = 0x41D0, Name = "White Mage-Hater"},
            new Command {ID = 0x41D1, Name = "Alchemist-Hater"},
            new Command {ID = 0x41D2, Name = "Strength up"},
            new Command {ID = 0x41D3, Name = "Strength down"},
            new Command {ID = 0x41D4, Name = "Touch-and-Go"},
            new Command {ID = 0x41D5, Name = "Power Catalyst"},
            new Command {ID = 0x41D6, Name = "Magic Catalyst"},
            new Command {ID = 0x41D7, Name = "Dual Catalyst"},
            new Command {ID = 0x41D8, Name = "DIALOGUE"},
            new Command {ID = 0x41D9, Name = "DIALOGUE"},
            new Command {ID = 0x41DA, Name = "Attack"},
            new Command {ID = 0x41DB, Name = "Strength Plus"},
            new Command {ID = 0x41DC, Name = "Defense up "},
            new Command {ID = 0x41DD, Name = "Magic up"},
            new Command {ID = 0x41DE, Name = "Pointless"},
            new Command {ID = 0x41DF, Name = "Attack"},
            new Command {ID = 0x41E0, Name = "W.I.M.P."},
            new Command {ID = 0x41E1, Name = "Attack"},
            new Command {ID = 0x41E2, Name = "Attack"},
            new Command {ID = 0x41E3, Name = "Attack"},
            new Command {ID = 0x41E4, Name = "Attack"},
            new Command {ID = 0x41E5, Name = "Attack"},
            new Command {ID = 0x41E6, Name = "Kill Attack"},
            new Command {ID = 0x41E7, Name = "Attack"},
            new Command {ID = 0x41E8, Name = "Attack"},
            new Command {ID = 0x41E9, Name = "Fire"},
            new Command {ID = 0x41EA, Name = "Blizzard"},
            new Command {ID = 0x41EB, Name = "Thunder"},
            new Command {ID = 0x41EC, Name = "Water"},
            new Command {ID = 0x41ED, Name = "Fira"},
            new Command {ID = 0x41EE, Name = "Blizzara"},
            new Command {ID = 0x41EF, Name = "Thundara"},
            new Command {ID = 0x41F0, Name = "Waterra"},
            new Command {ID = 0x41F1, Name = "Firaga"},
            new Command {ID = 0x41F2, Name = "Bizzaga"},
            new Command {ID = 0x41F3, Name = "Thundaga"},
            new Command {ID = 0x41F4, Name = "Waterga"},
            new Command {ID = 0x41F5, Name = "Rend"},
            new Command {ID = 0x41F6, Name = "Chain Attack"},
            new Command {ID = 0x41F7, Name = "Chicken Wing Lv.1"},
            new Command {ID = 0x41F8, Name = "Chicken Wing Lv.2"},
            new Command {ID = 0x41F9, Name = "Chicken Wing Lv.3"},
            new Command {ID = 0x41FA, Name = "Flare"},
            new Command {ID = 0x41FB, Name = "Ultima"},
            new Command {ID = 0x41FC, Name = "Heaven's Cataract"},
            new Command {ID = 0x41FD, Name = "Stone Breath"},
            new Command {ID = 0x41FE, Name = "Stormin"},
            new Command {ID = 0x41FF, Name = "Partyin"},
            new Command {ID = 0x4200, Name = "Machismo"},
            new Command {ID = 0x4201, Name = "Guess I'll hit ya"},
            new Command {ID = 0x4202, Name = "Sorry about that"},
            new Command {ID = 0x4203, Name = "Spiral Cut"},
            new Command {ID = 0x4204, Name = "Machismo"},
            new Command {ID = 0x4205, Name = "Blitz Ace"},
            new Command {ID = 0x4206, Name = "Full Break"},
            new Command {ID = 0x4207, Name = "Dragon Fang"},
            new Command {ID = 0x4208, Name = "Shooting Star"},
            new Command {ID = 0x4209, Name = "T. Fire"},
            new Command {ID = 0x420A, Name = "T. Blizzard"},
            new Command {ID = 0x420B, Name = "T. Thunder"},
            new Command {ID = 0x420C, Name = "T. Water"},
            new Command {ID = 0x420D, Name = "Jump"},
            new Command {ID = 0x420E, Name = "Sunshine"},
            new Command {ID = 0x420F, Name = "Requiem"},
            new Command {ID = 0x4210, Name = "Clione"},
            new Command {ID = 0x4211, Name = "Die"},
            new Command {ID = 0x4212, Name = "Squirt Gun"},
            new Command {ID = 0x4213, Name = "HEEL drop"},
            new Command {ID = 0x4214, Name = "Punishment"},
            new Command {ID = 0x4215, Name = "Supernova"},
            new Command {ID = 0x4216, Name = "Hero's Stash"},
            new Command {ID = 0x4217, Name = "White Wind"},
            new Command {ID = 0x4218, Name = "Mighty Guard"},
            new Command {ID = 0x4219, Name = "Popper"},
            new Command {ID = 0x421A, Name = "Radis Command"},
            new Command {ID = 0x421B, Name = "Venam Command"},
            new Command {ID = 0x421C, Name = "Fulmen Command"},
            new Command {ID = 0x421D, Name = "Mortis Command"},
            new Command {ID = 0x421E, Name = "Slowga"},
            new Command {ID = 0x421F, Name = "Turbo ether"},
            new Command {ID = 0x4220, Name = "Chocobo Feather"},
            new Command {ID = 0x4221, Name = "Meteor "},
            new Command {ID = 0x4222, Name = "Blaster"},
            new Command {ID = 0x4223, Name = "Two Dice"},
            new Command {ID = 0x4224, Name = "Telekinesis"},
            new Command {ID = 0x4225, Name = "Skullcracker"},
            new Command {ID = 0x4226, Name = "Ochu Jiggle"},
            new Command {ID = 0x4227, Name = "Ochu Dance "},
            new Command {ID = 0x4228, Name = "La Nina"},
            new Command {ID = 0x4229, Name = "Greedy Aura"},
            new Command {ID = 0x422A, Name = "Thanatos Emblem"},
            new Command {ID = 0x422B, Name = "Body Splash"},
            new Command {ID = 0x422C, Name = "Adamant Breath"},
            new Command {ID = 0x422D, Name = "Tremor"},
            new Command {ID = 0x422E, Name = "Triple Play!"},
            new Command {ID = 0x422F, Name = "Tail Smash"},
            new Command {ID = 0x4230, Name = "Damocles Photon"},
            new Command {ID = 0x4231, Name = "Supercollider"},
            new Command {ID = 0x4232, Name = "Battle too long: Angry"},
            new Command {ID = 0x4233, Name = "Battle too long: Furious"},
            new Command {ID = 0x4234, Name = "Battle too long: About to Blow"},
            new Command {ID = 0x4235, Name = "Battle too long: About to Blow"},
            new Command {ID = 0x4236, Name = "Time Up: Meteor"},
            new Command {ID = 0x4237, Name = "Self-Destruct Flare"},
        };
    }

    public class Command
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}