using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Farplane.FFX2.Values
{
    class Commands
    {
        public static List<string> GetCommandNames()
        {
            List<string> names = new List<string>();
            foreach (var c in CommandList)
                names.Add(c.Name);

            return names;
        }

        public static int IndexByID(int commandID)
        {
            if (commandID == 0 || commandID == 0xFF) return 0;
            var c = CommandList.First(cl => cl.ID == commandID);
            if (c != null) return CommandList.IndexOf(c);
            return 0;
        }

        public static Command GetCommand(int ID)
        {
            var cmd = CommandList.FirstOrDefault(command => command.ID == ID);
            return cmd;
        }
        
        public static List<Command> CommandList = new List<Command>()
        {
            new Command {ID = 0x3000, Name = "Item"},
            new Command {ID = 0x3001, Name = "Escape"},
            new Command {ID = 0x3002, Name = "Dresspheres"},
            new Command {ID = 0x3003, Name = "(UNUSED)"},
            new Command {ID = 0x3004, Name = "(UNUSED)"},
            new Command {ID = 0x3005, Name = "(UNUSED)"},
            new Command {ID = 0x3006, Name = "(UNUSED)"},
            new Command {ID = 0x3007, Name = "(UNUSED)"},
            new Command {ID = 0x3008, Name = "Gunplay"},
            new Command {ID = 0x3009, Name = "Stash"},
            new Command {ID = 0x300A, Name = "Blue Bullet"},
            new Command {ID = 0x300B, Name = "Fiend Hunter"},
            new Command {ID = 0x300C, Name = "Dance"},
            new Command {ID = 0x300D, Name = "Sing"},
            new Command {ID = 0x300E, Name = "Kupo!"},
            new Command {ID = 0x300F, Name = "Wildcat"},
            new Command {ID = 0x3010, Name = "Cutlery"},
            new Command {ID = 0x3011, Name = "Flimflam"},
            new Command {ID = 0x3012, Name = "Gamble"},
            new Command {ID = 0x3013, Name = "Kogoro"},
            new Command {ID = 0x3014, Name = "Ghiki"},
            new Command {ID = 0x3015, Name = "Flurry"},
            new Command {ID = 0x3016, Name = "Fallalery"},
            new Command {ID = 0x3017, Name = "Left Pistil"},
            new Command {ID = 0x3018, Name = "Right Pistil"},
            new Command {ID = 0x3019, Name = "Machinations"},
            new Command {ID = 0x301A, Name = "Smash"},
            new Command {ID = 0x301B, Name = "Crush"},
            new Command {ID = 0x301C, Name = "Throttle"},
            new Command {ID = 0x301D, Name = "Dextral Arts"},
            new Command {ID = 0x301E, Name = "Sinistal Arts"},
            new Command {ID = 0x301F, Name = "Swordplay"},
            new Command {ID = 0x3020, Name = "Bushido"},
            new Command {ID = 0x3021, Name = "Arcana"},
            new Command {ID = 0x3022, Name = "Instinct"},
            new Command {ID = 0x3023, Name = "Black Magic"},
            new Command {ID = 0x3024, Name = "White Magic"},
            new Command {ID = 0x3025, Name = "Auto-Life"},
            new Command {ID = 0x3026, Name = "Doom"},
            new Command {ID = 0x3027, Name = "Energy Ray"},
            new Command {ID = 0x3028, Name = "Energy Blast"},
            new Command {ID = 0x3029, Name = "Hellfire"},
            new Command {ID = 0x302A, Name = "Mjollnir"},
            new Command {ID = 0x302B, Name = "Mega-Flare"},
            new Command {ID = 0x302C, Name = "Attack"},
            new Command {ID = 0x302D, Name = "Attack"},
            new Command {ID = 0x302E, Name = "Attack"},
            new Command {ID = 0x302F, Name = "Attack"},
            new Command {ID = 0x3030, Name = "Attack"},
            new Command {ID = 0x3031, Name = "Attack"},
            new Command {ID = 0x3032, Name = "Trigger Happy"},
            new Command {ID = 0x3033, Name = "Potshot"},
            new Command {ID = 0x3034, Name = "Cheap Shot"},
            new Command {ID = 0x3035, Name = "Enchanted Ammo"},
            new Command {ID = 0x3036, Name = "Target MP"},
            new Command {ID = 0x3037, Name = "Quarter Pounder"},
            new Command {ID = 0x3038, Name = "On the Level"},
            new Command {ID = 0x3039, Name = "Burst Shot"},
            new Command {ID = 0x303A, Name = "Table-turner"},
            new Command {ID = 0x303B, Name = "Scattershot"},
            new Command {ID = 0x303C, Name = "Scatterburst"},
            new Command {ID = 0x303D, Name = "Scan"},
            new Command {ID = 0x303E, Name = "Shell Cracker"},
            new Command {ID = 0x303F, Name = "Anti Aircraft"},
            new Command {ID = 0x3040, Name = "Silver Bullet"},
            new Command {ID = 0x3041, Name = "Flan Eater"},
            new Command {ID = 0x3042, Name = "Elementillery"},
            new Command {ID = 0x3043, Name = "Killasaurus"},
            new Command {ID = 0x3044, Name = "Drake Slayer"},
            new Command {ID = 0x3045, Name = "Dismantler"},
            new Command {ID = 0x3046, Name = "Mech Destroyer"},
            new Command {ID = 0x3047, Name = "Demon Muzzle"},
            new Command {ID = 0x3048, Name = "Fire Breath"},
            new Command {ID = 0x3049, Name = "Seed Cannon"},
            new Command {ID = 0x304A, Name = "Stone Breath"},
            new Command {ID = 0x304B, Name = "Absorb"},
            new Command {ID = 0x304C, Name = "White Wind"},
            new Command {ID = 0x304D, Name = "Mundgeruch"},
            new Command {ID = 0x304E, Name = "Totalabwehr"},
            new Command {ID = 0x304F, Name = "Wahnstrahl"},
            new Command {ID = 0x3050, Name = "Nachtigall"},
            new Command {ID = 0x3051, Name = "Strahlgranate"},
            new Command {ID = 0x3052, Name = "Motorkanone"},
            new Command {ID = 0x3053, Name = "Gewaltakt"},
            new Command {ID = 0x3054, Name = "Vibra-Welle"},
            new Command {ID = 0x3055, Name = "1000 Stacheln"},
            new Command {ID = 0x3056, Name = "Sturmkanone"},
            new Command {ID = 0x3057, Name = "Blaster-Kugel"},
            new Command {ID = 0x3058, Name = "Kombi-Kugel"},
            new Command {ID = 0x3059, Name = "Potion"},
            new Command {ID = 0x305A, Name = "Hi-Potion"},
            new Command {ID = 0x305B, Name = "Mega-Potion"},
            new Command {ID = 0x305C, Name = "X-Potion"},
            new Command {ID = 0x305D, Name = "Allheilmittel"},
            new Command {ID = 0x305E, Name = "Zauberläscher"},
            new Command {ID = 0x305F, Name = "Ph?nixfeder"},
            new Command {ID = 0x3060, Name = "Mega-Ph?nix"},
            new Command {ID = 0x3061, Name = "?ther"},
            new Command {ID = 0x3062, Name = "Elixier"},
            new Command {ID = 0x3063, Name = "Störmen"},
            new Command {ID = 0x3064, Name = "Schutzwall"},
            new Command {ID = 0x3065, Name = "Kraftbrecher"},
            new Command {ID = 0x3066, Name = "Panzerbrecher"},
            new Command {ID = 0x3067, Name = "Magiebrecher"},
            new Command {ID = 0x3068, Name = "Geistbrecher"},
            new Command {ID = 0x3069, Name = "Flammenschwert"},
            new Command {ID = 0x306A, Name = "Icebrand"},
            new Command {ID = 0x306B, Name = "Donnerklinge"},
            new Command {ID = 0x306C, Name = "Aqua-Klinge"},
            new Command {ID = 0x306D, Name = "Gewichtklinge"},
            new Command {ID = 0x306E, Name = "Exkalibur"},
            new Command {ID = 0x306F, Name = "Retard-Hieb"},
            new Command {ID = 0x3070, Name = "Retard-Schock"},
            new Command {ID = 0x3071, Name = "Lichtspiegel"},
            new Command {ID = 0x3072, Name = "Magicus"},
            new Command {ID = 0x3073, Name = "Immobilia"},
            new Command {ID = 0x3074, Name = "Fieberwahn"},
            new Command {ID = 0x3075, Name = "Leuchtkugel"},
            new Command {ID = 0x3076, Name = "Strahlenkugel"},
            new Command {ID = 0x3077, Name = "?bung"},
            new Command {ID = 0x3078, Name = "Shin-Zantetsu"},
            new Command {ID = 0x3079, Name = "Original"},
            new Command {ID = 0x307A, Name = "Stolz"},
            new Command {ID = 0x307B, Name = "Neubeginn"},
            new Command {ID = 0x307C, Name = "Tornado"},
            new Command {ID = 0x307D, Name = "Almosen"},
            new Command {ID = 0x307E, Name = "Zantetsu"},
            new Command {ID = 0x307F, Name = "Dunkle Macht"},
            new Command {ID = 0x3080, Name = "Verwickeln"},
            new Command {ID = 0x3081, Name = "Subvita"},
            new Command {ID = 0x3082, Name = "Gravitas"},
            new Command {ID = 0x3083, Name = "Konfus"},
            new Command {ID = 0x3084, Name = "Stein"},
            new Command {ID = 0x3085, Name = "Bio"},
            new Command {ID = 0x3086, Name = "Todesurteil"},
            new Command {ID = 0x3087, Name = "Tod"},
            new Command {ID = 0x3088, Name = "Dunkler Himmel"},
            new Command {ID = 0x3089, Name = "Tobsucht"},
            new Command {ID = 0x308A, Name = "Mumm"},
            new Command {ID = 0x308B, Name = "Kleinholz"},
            new Command {ID = 0x308C, Name = "Störmen"},
            new Command {ID = 0x308D, Name = "Neutralisieren"},
            new Command {ID = 0x308E, Name = "Wegfegen"},
            new Command {ID = 0x308F, Name = "Einsch?chtern"},
            new Command {ID = 0x3090, Name = "Anmachen"},
            new Command {ID = 0x3091, Name = "Infizieren"},
            new Command {ID = 0x3092, Name = "Schmerz"},
            new Command {ID = 0x3093, Name = "Blindtanz"},
            new Command {ID = 0x3094, Name = "Stummtanz"},
            new Command {ID = 0x3095, Name = "Zaubertanz"},
            new Command {ID = 0x3096, Name = "Z-Schutztanz"},
            new Command {ID = 0x3097, Name = "Schlaftanz"},
            new Command {ID = 0x3098, Name = "Karnevaltanz"},
            new Command {ID = 0x3099, Name = "Breakdance"},
            new Command {ID = 0x309A, Name = "Stop-Tanz"},
            new Command {ID = 0x309B, Name = "Rapid-Tanz"},
            new Command {ID = 0x309C, Name = "Final-Tanz"},
            new Command {ID = 0x309D, Name = "Hymne"},
            new Command {ID = 0x309E, Name = "Elegie"},
            new Command {ID = 0x309F, Name = "Choral"},
            new Command {ID = 0x30A0, Name = "Kantate"},
            new Command {ID = 0x30A1, Name = "Gospel"},
            new Command {ID = 0x30A2, Name = "Matadorenlied"},
            new Command {ID = 0x30A3, Name = "Sammeln"},
            new Command {ID = 0x30A4, Name = "MP-Absorption"},
            new Command {ID = 0x30A5, Name = "Feuer"},
            new Command {ID = 0x30A6, Name = "Eis"},
            new Command {ID = 0x30A7, Name = "Blitz"},
            new Command {ID = 0x30A8, Name = "Wasser"},
            new Command {ID = 0x30A9, Name = "Feura"},
            new Command {ID = 0x30AA, Name = "Eisra"},
            new Command {ID = 0x30AB, Name = "Blitzra"},
            new Command {ID = 0x30AC, Name = "Wassra"},
            new Command {ID = 0x30AD, Name = "Feuga"},
            new Command {ID = 0x30AE, Name = "Eisga"},
            new Command {ID = 0x30AF, Name = "Blitzga"},
            new Command {ID = 0x30B0, Name = "Wassga"},
            new Command {ID = 0x30B1, Name = "Beten"},
            new Command {ID = 0x30B2, Name = "Gesundheit"},
            new Command {ID = 0x30B3, Name = "Vita"},
            new Command {ID = 0x30B4, Name = "Vitra"},
            new Command {ID = 0x30B5, Name = "Vitga"},
            new Command {ID = 0x30B6, Name = "Regena"},
            new Command {ID = 0x30B7, Name = "Medica"},
            new Command {ID = 0x30B8, Name = "Anti-Z"},
            new Command {ID = 0x30B9, Name = "Engel"},
            new Command {ID = 0x30BA, Name = "Erzengel"},
            new Command {ID = 0x30BB, Name = "Shell"},
            new Command {ID = 0x30BC, Name = "Protes"},
            new Command {ID = 0x30BD, Name = "Reflek"},
            new Command {ID = 0x30BE, Name = "Maxvita"},
            new Command {ID = 0x30BF, Name = "Klauen"},
            new Command {ID = 0x30C0, Name = "Gil-Klau"},
            new Command {ID = 0x30C1, Name = "Zeit-Klau"},
            new Command {ID = 0x30C2, Name = "HP-Klau"},
            new Command {ID = 0x30C3, Name = "MP-Klau"},
            new Command {ID = 0x30C4, Name = "Super-Klau"},
            new Command {ID = 0x30C5, Name = "Raritöten-Klau"},
            new Command {ID = 0x30C6, Name = "Herz-Klau"},
            new Command {ID = 0x30C7, Name = "Moral-Klau"},
            new Command {ID = 0x30C8, Name = "Und Tsch?ss..."},
            new Command {ID = 0x30C9, Name = "Flammen-Daigo"},
            new Command {ID = 0x30CA, Name = "Schnee-Daigo"},
            new Command {ID = 0x30CB, Name = "Donner-Daigo"},
            new Command {ID = 0x30CC, Name = "Flut-Daigo"},
            new Command {ID = 0x30CD, Name = "Daigo-Kanone"},
            new Command {ID = 0x30CE, Name = "Daigo-Urteil"},
            new Command {ID = 0x30CF, Name = "Lebens-Daigo"},
            new Command {ID = 0x30D0, Name = "Medizin-Daigo"},
            new Command {ID = 0x30D1, Name = "Himmels-Daigo"},
            new Command {ID = 0x30D2, Name = "Fasst!"},
            new Command {ID = 0x30D3, Name = "Giki-Blind"},
            new Command {ID = 0x30D4, Name = "Giki-Stumm"},
            new Command {ID = 0x30D5, Name = "Giki-Raub"},
            new Command {ID = 0x30D6, Name = "Giki-Zorn"},
            new Command {ID = 0x30D7, Name = "Böser Giki"},
            new Command {ID = 0x30D8, Name = "Munter-Giki"},
            new Command {ID = 0x30D9, Name = "Heilender Giki"},
            new Command {ID = 0x30DA, Name = "Hilfs-Giki"},
            new Command {ID = 0x30DB, Name = "R?uber-Giki"},
            new Command {ID = 0x30DC, Name = "Kommt!"},
            new Command {ID = 0x30DD, Name = "Flory-Gift"},
            new Command {ID = 0x30DE, Name = "Flory-Stein"},
            new Command {ID = 0x30DF, Name = "Flory-Tod"},
            new Command {ID = 0x30E0, Name = "Flory-Schutz"},
            new Command {ID = 0x30E1, Name = "Flory-Turbo"},
            new Command {ID = 0x30E2, Name = "Flory-Schild"},
            new Command {ID = 0x30E3, Name = "Flory-Heiliung"},
            new Command {ID = 0x30E4, Name = "Flory-Kur"},
            new Command {ID = 0x30E5, Name = "Flory-Tr?ger"},
            new Command {ID = 0x30E6, Name = "Zum Angriff!"},
            new Command {ID = 0x30E7, Name = "Schlag-Lotto"},
            new Command {ID = 0x30E8, Name = "Zauber-Lotto"},
            new Command {ID = 0x30E9, Name = "Item-Lotto"},
            new Command {ID = 0x30EA, Name = "Gl?cksrad"},
            new Command {ID = 0x30EB, Name = "Zweierw?rfel"},
            new Command {ID = 0x30EC, Name = "Viererw?rfel"},
            new Command {ID = 0x30ED, Name = "Fortuna"},
            new Command {ID = 0x30EE, Name = "Segnen"},
            new Command {ID = 0x30EF, Name = "Verfähren"},
            new Command {ID = 0x30F0, Name = "Bestechen"},
            new Command {ID = 0x30F1, Name = "Mog-Vita"},
            new Command {ID = 0x30F2, Name = "Mog-Regena"},
            new Command {ID = 0x30F3, Name = "Mog-Mauer"},
            new Command {ID = 0x30F4, Name = "Mog-Erzengel"},
            new Command {ID = 0x30F5, Name = "Mog-Vitaja"},
            new Command {ID = 0x30F6, Name = "Mog-Regeja"},
            new Command {ID = 0x30F7, Name = "Mog-Mauja"},
            new Command {ID = 0x30F8, Name = "Mog-Erzenjel"},
            new Command {ID = 0x30F9, Name = "Mog-Charme"},
            new Command {ID = 0x30FA, Name = "Mog-Strahl"},
            new Command {ID = 0x30FB, Name = "Cait-Feuer"},
            new Command {ID = 0x30FC, Name = "Cait-Eis"},
            new Command {ID = 0x30FD, Name = "Cait-Blitz"},
            new Command {ID = 0x30FE, Name = "Cait-Wasser"},
            new Command {ID = 0x30FF, Name = "Kraftläscher"},
            new Command {ID = 0x3100, Name = "Panzerläscher"},
            new Command {ID = 0x3101, Name = "Magieläscher"},
            new Command {ID = 0x3102, Name = "Mentalläscher"},
            new Command {ID = 0x3103, Name = "Reflexläscher"},
            new Command {ID = 0x3104, Name = "Erstkontakt"},
            new Command {ID = 0x3105, Name = "Schlafmesser"},
            new Command {ID = 0x3106, Name = "Blindmesser"},
            new Command {ID = 0x3107, Name = "Stummesser"},
            new Command {ID = 0x3108, Name = "Giftmesser"},
            new Command {ID = 0x3109, Name = "Wutmesser"},
            new Command {ID = 0x310A, Name = "Stopmesser"},
            new Command {ID = 0x310B, Name = "Steinmesser"},
            new Command {ID = 0x310C, Name = "Todesmesser"},
            new Command {ID = 0x310D, Name = "Statusmesser"},
            new Command {ID = 0x310E, Name = "Kaktor-MG"},
            new Command {ID = 0x310F, Name = "Flamenco"},
            new Command {ID = 0x3110, Name = "Eistanz"},
            new Command {ID = 0x3111, Name = "Tekkno"},
            new Command {ID = 0x3112, Name = "Synchron"},
            new Command {ID = 0x3113, Name = "Schild"},
            new Command {ID = 0x3114, Name = "Barriere"},
            new Command {ID = 0x3115, Name = "Analyse"},
            new Command {ID = 0x3116, Name = "Flare-Tanz"},
            new Command {ID = 0x3117, Name = "Super-Engel"},
            new Command {ID = 0x3118, Name = "Finalakt"},
            new Command {ID = 0x3119, Name = "Weiße Pollen"},
            new Command {ID = 0x311A, Name = "Weiße Honig"},
            new Command {ID = 0x311B, Name = "Harter Kern"},
            new Command {ID = 0x311C, Name = "Hartes Blatt"},
            new Command {ID = 0x311D, Name = "Spiegelbl?te"},
            new Command {ID = 0x311E, Name = "Fix Flora"},
            new Command {ID = 0x311F, Name = "Floral-Bombe"},
            new Command {ID = 0x3120, Name = "Flural-Bombe"},
            new Command {ID = 0x3121, Name = "Z-Floral-Bombe"},
            new Command {ID = 0x3122, Name = "Z-Flural-Bombe"},
            new Command {ID = 0x3123, Name = "Schlusslicht"},
            new Command {ID = 0x3124, Name = "Traumpollen"},
            new Command {ID = 0x3125, Name = "Narrenkern"},
            new Command {ID = 0x3126, Name = "Schleimhonig"},
            new Command {ID = 0x3127, Name = "Halbtote Bl?te"},
            new Command {ID = 0x3128, Name = "Giftblatt"},
            new Command {ID = 0x3129, Name = "Tote Bl?te"},
            new Command {ID = 0x312A, Name = "Aschepollen"},
            new Command {ID = 0x312B, Name = "Panikpollen"},
            new Command {ID = 0x312C, Name = "Honigbrocken"},
            new Command {ID = 0x312D, Name = "Sinnespollen"},
            new Command {ID = 0x312E, Name = "Finalbolzen"},
            new Command {ID = 0x312F, Name = "Angriff"},
            new Command {ID = 0x3130, Name = "Todesrakete"},
            new Command {ID = 0x3131, Name = "Biosrakete"},
            new Command {ID = 0x3132, Name = "Steinrakete"},
            new Command {ID = 0x3133, Name = "Tobrakete"},
            new Command {ID = 0x3134, Name = "Stoprakete"},
            new Command {ID = 0x3135, Name = "Konfusrakete"},
            new Command {ID = 0x3136, Name = "Schockwelle"},
            new Command {ID = 0x3137, Name = "Schocksturm"},
            new Command {ID = 0x3138, Name = "Neustart"},
            new Command {ID = 0x3139, Name = "Vajra"},
            new Command {ID = 0x313A, Name = "Ziel-Laser"},
            new Command {ID = 0x313B, Name = "HP-Reparatur"},
            new Command {ID = 0x313C, Name = "MP-Reparatur"},
            new Command {ID = 0x313D, Name = "Granate"},
            new Command {ID = 0x313E, Name = "Schlafgranate"},
            new Command {ID = 0x313F, Name = "Gemachgranate"},
            new Command {ID = 0x3140, Name = "Schw?chegranate"},
            new Command {ID = 0x3141, Name = "Antischutzgranate"},
            new Command {ID = 0x3142, Name = "Sensor"},
            new Command {ID = 0x3113, Name = "Bunker"},
            new Command {ID = 0x3144, Name = "Beschätzer"},
            new Command {ID = 0x3145, Name = "Ziel-Laser"},
            new Command {ID = 0x3146, Name = "HP-Reparatur"},
            new Command {ID = 0x3147, Name = "MP-Reparatur"},
            new Command {ID = 0x3148, Name = "Granate"},
            new Command {ID = 0x3149, Name = "Blindgranate"},
            new Command {ID = 0x314A, Name = "Stummgranate"},
            new Command {ID = 0x314B, Name = "Anti-Z-Granate"},
            new Command {ID = 0x314C, Name = "Anti-Mentalgranate"},
            new Command {ID = 0x314D, Name = "Booster"},
            new Command {ID = 0x314E, Name = "Angriffsposition"},
            new Command {ID = 0x314F, Name = "Abwehrposition"},
            new Command {ID = 0x3150, Name = "Flamme!"},
            new Command {ID = 0x3151, Name = "Frost!"},
            new Command {ID = 0x3152, Name = "Donner!"},
            new Command {ID = 0x3153, Name = "Flut!"},
            new Command {ID = 0x3154, Name = "Schw?che!"},
            new Command {ID = 0x3155, Name = "Schmerz!"},
            new Command {ID = 0x3156, Name = "Verhängnis!"},
            new Command {ID = 0x3157, Name = "Assoil"}, //EN
            new Command {ID = 0x3158, Name = "Fright"}, //EN
            new Command {ID = 0x3159, Name = "Schwerthagel!"},
            new Command {ID = 0x315A, Name = "Toxikum!"},
            new Command {ID = 0x315B, Name = "Finsternis!"},
            new Command {ID = 0x315C, Name = "Ruhe!"},
            new Command {ID = 0x315D, Name = "Marmor!"},
            new Command {ID = 0x315E, Name = "Nickerchen!"},
            new Command {ID = 0x315F, Name = "Amok!"},
            new Command {ID = 0x3160, Name = "Halt!"},
            new Command {ID = 0x3161, Name = "Verwirrung!"},
            new Command {ID = 0x3162, Name = "Kondition!"},
            new Command {ID = 0x3163, Name = "Wille!"},
            new Command {ID = 0x3164, Name = "Hoch!"},
            new Command {ID = 0x3165, Name = "Attacke!"},
            new Command {ID = 0x3166, Name = "Schutz!"},
            new Command {ID = 0x3167, Name = "Schnell!"},
            new Command {ID = 0x3168, Name = "Spion!"},
            new Command {ID = 0x3169, Name = "Schw?chlinge!"},
            new Command {ID = 0x316A, Name = "Verliere!"},
            new Command {ID = 0x316B, Name = "Versager!"},
            new Command {ID = 0x316C, Name = "Nieten!"},
            new Command {ID = 0x316D, Name = "Kondition!"},
            new Command {ID = 0x316E, Name = "Wille!"},
            new Command {ID = 0x316F, Name = "Hoch!"},
            new Command {ID = 0x3170, Name = "Flare"},
            new Command {ID = 0x3171, Name = "Ultima"},
            new Command {ID = 0x3172, Name = "Sanctus"},
            new Command {ID = 0x3173, Name = "Schutzengel"},
            new Command {ID = 0x3174, Name = "Rauben"},
            new Command {ID = 0x3175, Name = "Abzocken"},
            new Command {ID = 0x3176, Name = "Hast"},
            new Command {ID = 0x3177, Name = "Hastga"},
            new Command {ID = 0x3178, Name = "Blind"},
            new Command {ID = 0x3179, Name = "Stumm"},
            new Command {ID = 0x317A, Name = "Schlaf"},
            new Command {ID = 0x317B, Name = "Subspirit"},
            new Command {ID = 0x317C, Name = "Absorption"},
            new Command {ID = 0x317D, Name = "(Nichts)"},
            new Command {ID = 0x317E, Name = "(Nichts)"},
            new Command {ID = 0x317F, Name = "(Nichts)"},
            new Command {ID = 0x3180, Name = "(Nichts)"},
            new Command {ID = 0x3181, Name = "Time Trip End"},
            new Command {ID = 0x3182, Name = "Milchstra?e"},
            new Command {ID = 0x3183, Name = "Ananas"},
            new Command {ID = 0x3184, Name = "Nudelholz"},
            new Command {ID = 0x3185, Name = "Cluster"},
            new Command {ID = 0x3186, Name = "Supernova"},
            new Command {ID = 0x3187, Name = "Blastermine"},
            new Command {ID = 0x3188, Name = "Gasbombe"},
            new Command {ID = 0x3189, Name = "Hitzewelle"},
            new Command {ID = 0x318A, Name = "Feuersturm"},
            new Command {ID = 0x318B, Name = "Seelenfeuer"},
            new Command {ID = 0x318C, Name = "Höllenfeuer"},
            new Command {ID = 0x318D, Name = "Abadon-Feuer"},
            new Command {ID = 0x318E, Name = "Schneesturm"},
            new Command {ID = 0x318F, Name = "Blizzard"},
            new Command {ID = 0x3190, Name = "Wintersturm"},
            new Command {ID = 0x3191, Name = "Glatteis"},
            new Command {ID = 0x3192, Name = "Kokytos"},
            new Command {ID = 0x3193, Name = "Blitzschlag"},
            new Command {ID = 0x3194, Name = "Donnerhagel"},
            new Command {ID = 0x3195, Name = "Blitzschlag"},
            new Command {ID = 0x3196, Name = "Elektroschock"},
            new Command {ID = 0x3197, Name = "Donner-Blast"},
            new Command {ID = 0x3198, Name = "Wasserfall"},
            new Command {ID = 0x3199, Name = "Springflut"},
            new Command {ID = 0x319A, Name = "Gezeitenwelle"},
            new Command {ID = 0x319B, Name = "Abwasser"},
            new Command {ID = 0x319C, Name = "Ascheregen"},
            new Command {ID = 0x319D, Name = "Gravitonwelle"},
            new Command {ID = 0x319E, Name = "Wurmloch"},
            new Command {ID = 0x319F, Name = "Gravitonbombe"},
            new Command {ID = 0x31A0, Name = "Quattrobombe"},
            new Command {ID = 0x31A1, Name = "Engelswelle"},
            new Command {ID = 0x31A2, Name = "Weißes Loch"},
            new Command {ID = 0x31A3, Name = "Allheilmittel"},
            new Command {ID = 0x31A4, Name = "Allesheiler"},
            new Command {ID = 0x31A5, Name = "Ultraheiler"},
            new Command {ID = 0x31A6, Name = "Mega-Ph?nix"},
            new Command {ID = 0x31A7, Name = "Ultima-Ph?nix"},
            new Command {ID = 0x31A8, Name = "Final Ph?nix"},
            new Command {ID = 0x31A9, Name = "Hi-Potion"},
            new Command {ID = 0x31AA, Name = "Mega-Potion"},
            new Command {ID = 0x31AB, Name = "Ultima-Potion"},
            new Command {ID = 0x31AC, Name = "End-Elixier"},
            new Command {ID = 0x31AD, Name = "Galaxieschleier"},
            new Command {ID = 0x31AE, Name = "Chocobo-Daune"},
            new Command {ID = 0x31AF, Name = "Lebensquelle"},
            new Command {ID = 0x31B0, Name = "Lebensozean"},
            new Command {ID = 0x31B1, Name = "Mauer"},
            new Command {ID = 0x31B2, Name = "Hohe Mauer"},
            new Command {ID = 0x31B3, Name = "Finale Mauer"},
            new Command {ID = 0x31B4, Name = "Mega-Vital W"},
            new Command {ID = 0x31B5, Name = "Mega-Mix W"},
            new Command {ID = 0x31B6, Name = "Mega-Mental W"},
            new Command {ID = 0x31B7, Name = "Heldentrank"},
            new Command {ID = 0x31B8, Name = "Heiligenpille"},
            new Command {ID = 0x31B9, Name = "Shin-Zantetsu"},
            new Command {ID = 0x31BA, Name = "Exkalibur"},
            new Command {ID = 0x31BB, Name = "Zerstören"},
            new Command {ID = 0x31BC, Name = "Retard-Schock"},
            new Command {ID = 0x31BD, Name = "Anmachen"},
            new Command {ID = 0x31BE, Name = "Strahlenkugel"},
            new Command {ID = 0x31BF, Name = "Neubeginn"},
            new Command {ID = 0x31C0, Name = "Kraftbrecher"},
            new Command {ID = 0x31C1, Name = "Wegfegen"},
            new Command {ID = 0x31C2, Name = "Magicus"},
            new Command {ID = 0x31C3, Name = "Panzerbrecher"},
            new Command {ID = 0x31C4, Name = "Ultima"},
            new Command {ID = 0x31C5, Name = "Dunkler Himmel"},
            new Command {ID = 0x31C6, Name = "Flare"},
            new Command {ID = 0x31C7, Name = "Feuga"},
            new Command {ID = 0x31C8, Name = "Schutzengel"},
            new Command {ID = 0x31C9, Name = "Gravitas"},
            new Command {ID = 0x31CA, Name = "Bio"},
            new Command {ID = 0x31CB, Name = "Blitzra"},
            new Command {ID = 0x31CC, Name = "Medica"},
            new Command {ID = 0x31CD, Name = "Stein"},
            new Command {ID = 0x31CE, Name = "Vitra"},
            new Command {ID = 0x31CF, Name = "Final Elixier +"},
            new Command {ID = 0x31D0, Name = "Totalabwehr +"},
            new Command {ID = 0x31D1, Name = "H?herer Stein"},
            new Command {ID = 0x31D2, Name = "Heiliger Stein"},
            new Command {ID = 0x31D3, Name = "Final-Elixier"},
            new Command {ID = 0x31D4, Name = "Totalabwehr"},
            new Command {ID = 0x31D5, Name = "Mega-?ther"},
            new Command {ID = 0x31D6, Name = "L-Bombe"},
            new Command {ID = 0x31D7, Name = "?ther"},
            new Command {ID = 0x31D8, Name = "Mondschleier +"},
            new Command {ID = 0x31D9, Name = "Lichtschleier +"},
            new Command {ID = 0x31DA, Name = "Bingo!"},
            new Command {ID = 0x31DB, Name = "Mega-Potion"},
            new Command {ID = 0x31DC, Name = "Eisga"},
            new Command {ID = 0x31DD, Name = "Nachtbr?ller"},
            new Command {ID = 0x31DE, Name = "Anti-Materie"},
            new Command {ID = 0x31DF, Name = "Totalbrecher"},
            new Command {ID = 0x31E0, Name = "Mental-Brecher"},
            new Command {ID = 0x31E1, Name = "Vita"},
            new Command {ID = 0x31E2, Name = "Premium-Granate"},
            new Command {ID = 0x31E3, Name = "Hi-Potion"},
            new Command {ID = 0x31E4, Name = "Potion"},
            new Command {ID = 0x31E5, Name = "Niete"},
            new Command {ID = 0x31E6, Name = "Psycho Bomb"},
            new Command {ID = 0x31E7, Name = "Telekinesis"},
            new Command {ID = 0x31E8, Name = "Mazer Eye"},
            new Command {ID = 0x31E9, Name = "Brain Storm"},
            new Command {ID = 0x31EA, Name = "Time Trip"},
            new Command {ID = 0x31EB, Name = "Express"},
            new Command {ID = 0x31EC, Name = "Magic Guard"},
            new Command {ID = 0x31ED, Name = "Physics Guard"},
            new Command {ID = 0x31EE, Name = "Teleportation"},
            new Command {ID = 0x31EF, Name = "Excellence"},
            new Command {ID = 0x31F0, Name = "Rhinoceros Kick"},
            new Command {ID = 0x31F1, Name = "Celebration"},
            new Command {ID = 0x31F2, Name = "Celebration"},
            new Command {ID = 0x31F3, Name = "Celebration"},
            new Command {ID = 0x31F4, Name = "Pinwheel"},
            new Command {ID = 0x31F5, Name = "Pinwheel"},
            new Command {ID = 0x31F6, Name = "Pinwheel"},
            new Command {ID = 0x31F7, Name = "Fireworks Piece"},
            new Command {ID = 0x31F8, Name = "Fireworks Piece"},
            new Command {ID = 0x31F9, Name = "Fireworks Piece"},
            new Command {ID = 0x31FA, Name = "Toy Fireworks"},
            new Command {ID = 0x31FB, Name = "Toy Fireworks"},
            new Command {ID = 0x31FC, Name = "Toy Fireworks"},
            new Command {ID = 0x31FD, Name = "Festival Firworks"},
            new Command {ID = 0x31FE, Name = "Festival Firworks"},
            new Command {ID = 0x31FF, Name = "Festival Firworks"},
            new Command {ID = 0x3200, Name = "Flame Geta"},
            new Command {ID = 0x3201, Name = "Ice Geta"},
            new Command {ID = 0x3202, Name = "Thunder Geta"},
            new Command {ID = 0x3203, Name = "Water Geta"},
            new Command {ID = 0x3204, Name = "Flare Geta"},
            new Command {ID = 0x3205, Name = "Ultima Geta"},
            new Command {ID = 0x3206, Name = "Flame Goldfish"},
            new Command {ID = 0x3207, Name = "Ice Goldfish"},
            new Command {ID = 0x3208, Name = "Thunder Goldfish"},
            new Command {ID = 0x3209, Name = "Water Goldfish"},
            new Command {ID = 0x320A, Name = "Gravity Goldfish"},
            new Command {ID = 0x320B, Name = "Holy Goldfish"},
            new Command {ID = 0x320C, Name = "Silence Omen"},
            new Command {ID = 0x320D, Name = "Darkness Omen"},
            new Command {ID = 0x320E, Name = "Poison Omen"},
            new Command {ID = 0x320F, Name = "Sleep Omen"},
            new Command {ID = 0x3210, Name = "Stop Omen"},
            new Command {ID = 0x3211, Name = "Petrify Omen"},
            new Command {ID = 0x3212, Name = "Fire"},
            new Command {ID = 0x3213, Name = "Fira"},
            new Command {ID = 0x3214, Name = "Firaga"},
            new Command {ID = 0x3215, Name = "Firaga 2"},
            new Command {ID = 0x3216, Name = "Blizzard"},
            new Command {ID = 0x3217, Name = "Blizzara"},
            new Command {ID = 0x3218, Name = "Blizzaga"},
            new Command {ID = 0x3219, Name = "Blizzaga 2"},
            new Command {ID = 0x321A, Name = "Thunder"},
            new Command {ID = 0x321B, Name = "Thundara"},
            new Command {ID = 0x321C, Name = "Thundaga"},
            new Command {ID = 0x321D, Name = "Thundaga 2"},
            new Command {ID = 0x321E, Name = "Water"},
            new Command {ID = 0x321F, Name = "Watera"},
            new Command {ID = 0x3220, Name = "Waterga"},
            new Command {ID = 0x3221, Name = "Waterga 2"},
            new Command {ID = 0x3222, Name = "Sleep"},
            new Command {ID = 0x3223, Name = "Tobsucht"},
            new Command {ID = 0x3224, Name = "Stein"},
            new Command {ID = 0x3225, Name = "Flare"},
            new Command {ID = 0x3226, Name = "Stumm"},
            new Command {ID = 0x3227, Name = "Blind"},
            new Command {ID = 0x3228, Name = "Tod"},
            new Command {ID = 0x3229, Name = "Ultima"},
            new Command {ID = 0x4000, Name = "Angriff"},
            new Command {ID = 0x4001, Name = "Angriff"},
            new Command {ID = 0x4002, Name = "(langer Name)"},
            new Command {ID = 0x4003, Name = "Angriff"},
            new Command {ID = 0x4004, Name = "Giftattacke"},
            new Command {ID = 0x4005, Name = "Schlafattacke"},
            new Command {ID = 0x4006, Name = "Stummattacke"},
            new Command {ID = 0x4007, Name = "Konfusattacke"},
            new Command {ID = 0x4008, Name = "Blindattacke"},
            new Command {ID = 0x4009, Name = "Gemachattacke"},
            new Command {ID = 0x400A, Name = "Stopattacke"},
            new Command {ID = 0x400B, Name = "Retardschlag"},
            new Command {ID = 0x400C, Name = "Kazu (?) attacke"},
            new Command {ID = 0x400D, Name = "Herzloser.."},
            new Command {ID = 0x400E, Name = "Angriff"},
            new Command {ID = 0x400F, Name = "Todesattacke"},
            new Command {ID = 0x4010, Name = "Subvitaattacke"},
            new Command {ID = 0x4011, Name = "(langer Name)"},
            new Command {ID = 0x4012, Name = "Angriff"},
            new Command {ID = 0x4013, Name = "Subspiritattacke"},
            new Command {ID = 0x4014, Name = "????"},
            new Command {ID = 0x4015, Name = "Kritische Attacke"},
            new Command {ID = 0x4016, Name = "Schlafstachel"},
            new Command {ID = 0x4017, Name = "Giftstachel"},
            new Command {ID = 0x4018, Name = "Tripleschock"},
            new Command {ID = 0x4019, Name = "Kernspucken"},
            new Command {ID = 0x401A, Name = "Kernkanone"},
            new Command {ID = 0x401B, Name = "Kerndauerspucken"},
            new Command {ID = 0x401C, Name = "Perseusblick"},
            new Command {ID = 0x401D, Name = "Vorbeben"},
            new Command {ID = 0x401E, Name = "Erdbeben"},
            new Command {ID = 0x401F, Name = "Dunkler Blick"},
            new Command {ID = 0x4020, Name = "Gemach-Blick"},
            new Command {ID = 0x4021, Name = "Gemach-Blick"},
            new Command {ID = 0x4022, Name = "Starrer Blick"},
            new Command {ID = 0x4023, Name = "Ultraschall"},
            new Command {ID = 0x4024, Name = "Schallwelle"},
            new Command {ID = 0x4025, Name = "Schallsturm"},
            new Command {ID = 0x4026, Name = "Angriff"},
            new Command {ID = 0x4027, Name = "Angriff"},
            new Command {ID = 0x4028, Name = "Kr?ftestau"},
            new Command {ID = 0x4029, Name = "Gewehr"},
            new Command {ID = 0x402A, Name = "Gewehr"},
            new Command {ID = 0x402B, Name = "Flammenwerfer"},
            new Command {ID = 0x402C, Name = "Ferskick"},
            new Command {ID = 0x402D, Name = "Wirbelkick"},
            new Command {ID = 0x402E, Name = "Wasserpistole"},
            new Command {ID = 0x402F, Name = "Hauch"},
            new Command {ID = 0x4030, Name = "Hauch"},
            new Command {ID = 0x4031, Name = "Hauch"},
            new Command {ID = 0x4032, Name = "Flammenhauch"},
            new Command {ID = 0x4033, Name = "Einzelvisier"},
            new Command {ID = 0x4034, Name = "Einzelvisier"},
            new Command {ID = 0x4035, Name = "Fl?chenvisier"},
            new Command {ID = 0x4036, Name = "Fl?chenvisier"},
            new Command {ID = 0x4037, Name = "Störsignal"},
            new Command {ID = 0x4038, Name = "Das Urteil"},
            new Command {ID = 0x4039, Name = "Die Verbannung"},
            new Command {ID = 0x403A, Name = "Wahnstrahl"},
            new Command {ID = 0x403B, Name = "Sterben"},
            new Command {ID = 0x403C, Name = "Sterben"},
            new Command {ID = 0x403D, Name = "Stichdorn"},
            new Command {ID = 0x403E, Name = "Feuerhauch"},
            new Command {ID = 0x403F, Name = "Feuersturm"},
            new Command {ID = 0x4040, Name = "Einsaugen"},
            new Command {ID = 0x4041, Name = "Steinerne Kralle"},
            new Command {ID = 0x4042, Name = "Zerreissen"},
            new Command {ID = 0x4043, Name = "Zornige Kralle"},
            new Command {ID = 0x4044, Name = "Wirre Kralle"},
            new Command {ID = 0x4045, Name = "Steinerner Hauch"},
            new Command {ID = 0x4046, Name = "Fluch"},
            new Command {ID = 0x4047, Name = "Angriff"},
            new Command {ID = 0x4048, Name = "Niederm?hen"},
            new Command {ID = 0x4049, Name = "Helmspalter"},
            new Command {ID = 0x404A, Name = "Helmspalter"},
            new Command {ID = 0x404B, Name = "Elektroschock"},
            new Command {ID = 0x404C, Name = "Richterskala"},
            new Command {ID = 0x404D, Name = "K?sschentanz "},
            new Command {ID = 0x404E, Name = "Blendepollen"},
            new Command {ID = 0x404F, Name = "Giftpollen"},
            new Command {ID = 0x4050, Name = "Nervenpollen"},
            new Command {ID = 0x4051, Name = "El Ni?o "},
            new Command {ID = 0x4052, Name = "La Ni?a "},
            new Command {ID = 0x4053, Name = "1000 Needles"},
            new Command {ID = 0x4054, Name = "10000 Needles"},
            new Command {ID = 0x4055, Name = "Fliehen"},
            new Command {ID = 0x4056, Name = "Sprengfaust "},
            new Command {ID = 0x4057, Name = "Doppelattacke"},
            new Command {ID = 0x4058, Name = "Perseusblick"},
            new Command {ID = 0x4059, Name = "Gutenachtblick"},
            new Command {ID = 0x405A, Name = "Intens-Welle"},
            new Command {ID = 0x405B, Name = "Thanatos-Emblem"},
            new Command {ID = 0x405C, Name = "Hochspannung"},
            new Command {ID = 0x405D, Name = "Zweih?ndig"},
            new Command {ID = 0x405E, Name = "Konter"},
            new Command {ID = 0x405F, Name = "Sterben"},
            new Command {ID = 0x4060, Name = "Sterben"},
            new Command {ID = 0x4061, Name = "Bl?hung 2"},
            new Command {ID = 0x4062, Name = "Bl?hung 3"},
            new Command {ID = 0x4063, Name = "Bl?hung 4"},
            new Command {ID = 0x4064, Name = "Störmen"},
            new Command {ID = 0x4065, Name = "Ticktack-Bumm!"},
            new Command {ID = 0x4066, Name = "Bumm!"},
            new Command {ID = 0x4067, Name = "Bummm!"},
            new Command {ID = 0x4068, Name = "Buuummm!"},
            new Command {ID = 0x4069, Name = "Erzengel"},
            new Command {ID = 0x406A, Name = "Tobsucht"},
            new Command {ID = 0x406B, Name = "Hast"},
            new Command {ID = 0x406C, Name = "Gemach"},
            new Command {ID = 0x406D, Name = "Subvita"},
            new Command {ID = 0x406E, Name = "Schlaf"},
            new Command {ID = 0x406F, Name = "Blind"},
            new Command {ID = 0x4070, Name = "Konfus"},
            new Command {ID = 0x4071, Name = "Stumm"},
            new Command {ID = 0x4072, Name = "Stein"},
            new Command {ID = 0x4073, Name = "Todesurteil"},
            new Command {ID = 0x4074, Name = "Störmen"},
            new Command {ID = 0x4075, Name = "Nasshauch"},
            new Command {ID = 0x4076, Name = "Chaosflamme"},
            new Command {ID = 0x4077, Name = "Mundgeruch"},
            new Command {ID = 0x4078, Name = "?bler Mundgeruch"},
            new Command {ID = 0x4079, Name = "Magens?ure"},
            new Command {ID = 0x407A, Name = "Anknabbern"},
            new Command {ID = 0x407B, Name = "Amok"},
            new Command {ID = 0x407C, Name = "Angriff"},
            new Command {ID = 0x407D, Name = "Schwert-Rondo"},
            new Command {ID = 0x407E, Name = "Fluch aller"},
            new Command {ID = 0x407F, Name = "Erdrutsch"},
            new Command {ID = 0x4080, Name = "Adaman-Hauch"},
            new Command {ID = 0x4081, Name = "Kinnhaken"},
            new Command {ID = 0x4082, Name = "Tyrannen-Schwanz"},
            new Command {ID = 0x4083, Name = "Meteo"},
            new Command {ID = 0x4084, Name = "Totalabwehr"},
            new Command {ID = 0x4085, Name = "Totalabwehr G"},
            new Command {ID = 0x4086, Name = "Miniabwehr"},
            new Command {ID = 0x4087, Name = "Himmelswind"},
            new Command {ID = 0x4088, Name = "Himmelsb?e"},
            new Command {ID = 0x4089, Name = "Blaster"},
            new Command {ID = 0x408A, Name = "Killer-Blaster"},
            new Command {ID = 0x408B, Name = "Bauchplatscher"},
            new Command {ID = 0x408C, Name = "Sturmkanone"},
            new Command {ID = 0x408D, Name = "Giftnebel"},
            new Command {ID = 0x408E, Name = "Giftsmog"},
            new Command {ID = 0x408F, Name = "Daneben!!"},
            new Command {ID = 0x4090, Name = "Volltreffer!!"},
            new Command {ID = 0x4091, Name = "Laserstrahl"},
            new Command {ID = 0x4092, Name = "Schallschwinge"},
            new Command {ID = 0x4093, Name = "Kr?ftestrahl"},
            new Command {ID = 0x4094, Name = "Inferno"},
            new Command {ID = 0x4095, Name = "Meteorit"},
            new Command {ID = 0x4096, Name = "Aero-Funken"},
            new Command {ID = 0x4097, Name = "Mj?llnir"},
            new Command {ID = 0x4098, Name = "Energiestau"},
            new Command {ID = 0x4099, Name = "Heavenly Strike"},
            new Command {ID = 0x409A, Name = "Diamond Dust"},
            new Command {ID = 0x409B, Name = "Impulse "},
            new Command {ID = 0x409C, Name = "Mega Flare"},
            new Command {ID = 0x409D, Name = "Anima-Angriff"},
            new Command {ID = 0x409E, Name = "Weltschmerz"},
            new Command {ID = 0x409F, Name = "Chaos-D"},
            new Command {ID = 0x40A0, Name = "Daigoro"},
            new Command {ID = 0x40A1, Name = "Kozuka"},
            new Command {ID = 0x40A2, Name = "Wakizashi (ein Ziel)"},
            new Command {ID = 0x40A3, Name = "Wakizashi (alle)"},
            new Command {ID = 0x40A4, Name = "Zanmatou"},
            new Command {ID = 0x40A5, Name = "Daigoro"},
            new Command {ID = 0x40A6, Name = "Schmelzklinge"},
            new Command {ID = 0x40A7, Name = "Wasserrutsche"},
            new Command {ID = 0x40A8, Name = "Nadelspr?her"},
            new Command {ID = 0x40A9, Name = "Dreiecksbeziehung"},
            new Command {ID = 0x40AA, Name = "Katastrophe"},
            new Command {ID = 0x40AB, Name = "Totalabwehr"},
            new Command {ID = 0x40AC, Name = "Mega-Graviton "},
            new Command {ID = 0x40AD, Name = "Sterben"},
            new Command {ID = 0x40AE, Name = "Sterben"},
            new Command {ID = 0x40AF, Name = "Sterben"},
            new Command {ID = 0x40B0, Name = "Sterben"},
            new Command {ID = 0x40B1, Name = "Sterben"},
            new Command {ID = 0x40B2, Name = "Sterben"},
            new Command {ID = 0x40B3, Name = "Sterben"},
            new Command {ID = 0x40B4, Name = "Sterben"},
            new Command {ID = 0x40B5, Name = "Sterben"},
            new Command {ID = 0x40B6, Name = "Angriff"},
            new Command {ID = 0x40B7, Name = "Zurückziehen"},
            new Command {ID = 0x40B8, Name = "Ausfahren"},
            new Command {ID = 0x40B9, Name = "Schleimer"},
            new Command {ID = 0x40BA, Name = "Megapresse"},
            new Command {ID = 0x40BB, Name = "Panzerbruch"},
            new Command {ID = 0x40BC, Name = "Panzerbruch 2"},
            new Command {ID = 0x40BD, Name = "Sterben"},
            new Command {ID = 0x40BE, Name = "Revolver"},
            new Command {ID = 0x40BF, Name = "Vollautomatik-Feuer"},
            new Command {ID = 0x40C0, Name = "Killerreißer"},
            new Command {ID = 0x40C1, Name = "Giftreißer"},
            new Command {ID = 0x40C2, Name = "Steinreißer"},
            new Command {ID = 0x40C3, Name = "Fluchreißer"},
            new Command {ID = 0x40C4, Name = "Geistreißer"},
            new Command {ID = 0x40C5, Name = "Helmkonter"},
            new Command {ID = 0x40C6, Name = "K?chenmesser"},
            new Command {ID = 0x40C7, Name = "Spinnen-Angriff"},
            new Command {ID = 0x40C8, Name = "Kleber"},
            new Command {ID = 0x40C9, Name = "Sekundenkleber"},
            new Command {ID = 0x40CA, Name = "Spinnenbiss"},
            new Command {ID = 0x40CB, Name = "Geistschnabel"},
            new Command {ID = 0x40CC, Name = "Killerstachel"},
            new Command {ID = 0x40CD, Name = "Blind-Arm"},
            new Command {ID = 0x40CE, Name = "Stumm-Arm"},
            new Command {ID = 0x40CF, Name = "Bio-Arm"},
            new Command {ID = 0x40D0, Name = "Stop-Arm"},
            new Command {ID = 0x40D1, Name = "Leitende Hand"},
            new Command {ID = 0x40D2, Name = "Laufende Hand"},
            new Command {ID = 0x40D3, Name = "Teilende Hand"},
            new Command {ID = 0x40D4, Name = "Fassende Hand"},
            new Command {ID = 0x40D5, Name = "Trennende Hand"},
            new Command {ID = 0x40D6, Name = "Tr?bende Hand"},
            new Command {ID = 0x40D7, Name = "Schlitzerkralle"},
            new Command {ID = 0x40D8, Name = "Flammenhauch"},
            new Command {ID = 0x40D9, Name = "Schwanzhieb"},
            new Command {ID = 0x40DA, Name = "Damokles-Photon"},
            new Command {ID = 0x40DB, Name = "Atemloser Hauch"},
            new Command {ID = 0x40DC, Name = "Sterben"},
            new Command {ID = 0x40DD, Name = "Sterben"},
            new Command {ID = 0x40DE, Name = "Sterben"},
            new Command {ID = 0x40DF, Name = "Angriff"},
            new Command {ID = 0x40E0, Name = "Angriff"},
            new Command {ID = 0x40E1, Name = "Barrierewechsel"},
            new Command {ID = 0x40E2, Name = "Sterben"},
            new Command {ID = 0x40E3, Name = "Angriff"},
            new Command {ID = 0x40E4, Name = "Mega-Zirkelwurf"},
            new Command {ID = 0x40E5, Name = "Superschleuder"},
            new Command {ID = 0x40E6, Name = "Knutschen"},
            new Command {ID = 0x40E7, Name = "Einh?ndig"},
            new Command {ID = 0x40E8, Name = "Kugelhagel"},
            new Command {ID = 0x40E9, Name = "Russisches Roulette"},
            new Command {ID = 0x40EA, Name = "Russisches Roulette"},
            new Command {ID = 0x40EB, Name = "Russisches Roulette"},
            new Command {ID = 0x40EC, Name = "Der Anfang jeglichen Seins"},
            new Command {ID = 0x40ED, Name = "Das Orakel der Krieger"},
            new Command {ID = 0x40EE, Name = "Russisches Roulette"},
            new Command {ID = 0x40EF, Name = "Russisches Roulette"},
            new Command {ID = 0x40F0, Name = "Russisches Roulette"},
            new Command {ID = 0x40F1, Name = "Potion"},
            new Command {ID = 0x40F2, Name = "Fächerschlag"},
            new Command {ID = 0x40F3, Name = "Schallfächer"},
            new Command {ID = 0x40F4, Name = "Ultra-Fächer"},
            new Command {ID = 0x40F5, Name = "Portion Mumm"},
            new Command {ID = 0x40F6, Name = "Adios-Sturm"},
            new Command {ID = 0x40F7, Name = "Nichts"},
            new Command {ID = 0x40F8, Name = "Nichts"},
            new Command {ID = 0x40F9, Name = "Bombe"},
            new Command {ID = 0x40FA, Name = "Wurfgranate"},
            new Command {ID = 0x40FB, Name = "Mega-Granate"},
            new Command {ID = 0x40FC, Name = "Tut mir Leid!"},
            new Command {ID = 0x40FD, Name = "Flammenbombe"},
            new Command {ID = 0x40FE, Name = "Stummbombe"},
            new Command {ID = 0x40FF, Name = "Varitas-Schwert"},
            new Command {ID = 0x4100, Name = "Kombo"},
            new Command {ID = 0x4101, Name = "Rotorschlag"},
            new Command {ID = 0x4102, Name = "Gefrierfaust"},
            new Command {ID = 0x4103, Name = "Panzerschuss"},
            new Command {ID = 0x4104, Name = "Potion Plus"},
            new Command {ID = 0x4105, Name = "Und los geht's!"},
            new Command {ID = 0x4106, Name = "Pausengong!"},
            new Command {ID = 0x4107, Name = "Unsichtbare B?lle!"},
            new Command {ID = 0x4108, Name = "Mund halten!"},
            new Command {ID = 0x4109, Name = "Sterben"},
            new Command {ID = 0x410A, Name = "Choco-Kick"},
            new Command {ID = 0x410B, Name = "Choco-Vita"},
            new Command {ID = 0x410C, Name = "Choco-Shell"},
            new Command {ID = 0x410D, Name = "Choco-Protes"},
            new Command {ID = 0x410E, Name = "Choco-Meteo"},
            new Command {ID = 0x410F, Name = "Fliehen"},
            new Command {ID = 0x4110, Name = "Freude"},
            new Command {ID = 0x4111, Name = "Angriff"},
            new Command {ID = 0x4112, Name = "Motorkanone"},
            new Command {ID = 0x4113, Name = "Schleifer"},
            new Command {ID = 0x4114, Name = "Finalschuss"},
            new Command {ID = 0x4115, Name = "Einzel-Tech"},
            new Command {ID = 0x4116, Name = "Zehrfunke"},
            new Command {ID = 0x4117, Name = "Lichtpartikel"},
            new Command {ID = 0x4118, Name = "Wirbelhieb"},
            new Command {ID = 0x4119, Name = "Sturm & Schlag"},
            new Command {ID = 0x411A, Name = "Kraftregen"},
            new Command {ID = 0x411B, Name = "Schrecken von Zanarkand"},
            new Command {ID = 0x411C, Name = "Fluchsto?"},
            new Command {ID = 0x411D, Name = "Magiebrecher"},
            new Command {ID = 0x411E, Name = "Tripel-Kombo"},
            new Command {ID = 0x411F, Name = "Kombo"},
            new Command {ID = 0x4120, Name = "Kombo"},
            new Command {ID = 0x4121, Name = "Raktenwerfer"},
            new Command {ID = 0x4122, Name = "Raktenwerfer"},
            new Command {ID = 0x4123, Name = "Raktenwerfer"},
            new Command {ID = 0x4124, Name = "Raktenwerfer"},
            new Command {ID = 0x4125, Name = "Lebensschlitzer"},
            new Command {ID = 0x4126, Name = "Totalvernichtung"},
            new Command {ID = 0x4127, Name = "Sterben"},
            new Command {ID = 0x4128, Name = "Meteo"},
            new Command {ID = 0x4129, Name = "Schlag"},
            new Command {ID = 0x412A, Name = "Glimmer of Despair"}, //EN
            new Command {ID = 0x412B, Name = "Blutgeruch"},
            new Command {ID = 0x412C, Name = "Genesisbeben"},
            new Command {ID = 0x412D, Name = "Fegefeuer"},
            new Command {ID = 0x412E, Name = "Sterben"},
            new Command {ID = 0x412F, Name = "Noli Me Tangere"},
            new Command {ID = 0x4130, Name = "Schwanz-Laser"},
            new Command {ID = 0x4131, Name = "Vita Brevis"},
            new Command {ID = 0x4132, Name = "Einzelrakete"},
            new Command {ID = 0x4133, Name = "Dies Irae"},
            new Command {ID = 0x4134, Name = "Feindaktivit?t registiert"},
            new Command {ID = 0x4135, Name = "Feindaktivit?t registiert"},
            new Command {ID = 0x4136, Name = "Physischen Angriff registiert"},
            new Command {ID = 0x4137, Name = "Zauberangriff registiert"},
            new Command {ID = 0x4138, Name = "Physischen Angriff registiert"},
            new Command {ID = 0x4139, Name = "Zauberangriff registiert"},
            new Command {ID = 0x413A, Name = "Memento Mori"},
            new Command {ID = 0x413B, Name = "Energiestau"},
            new Command {ID = 0x413C, Name = "Sterben"},
            new Command {ID = 0x413D, Name = "Pallida Mors"},
            new Command {ID = 0x413E, Name = "Lacrimosa"},
            new Command {ID = 0x413F, Name = "Lacrimosa"},
            new Command {ID = 0x4140, Name = "Odi et Amo"},
            new Command {ID = 0x4141, Name = "Mors Certa"},
            new Command {ID = 0x4142, Name = "Nemo Ante Mortem Beatus"},
            new Command {ID = 0x4143, Name = "Sterben"},
            new Command {ID = 0x4144, Name = "Acta Est Fabula"},
            new Command {ID = 0x4145, Name = "Potion-Brecher"},
            new Command {ID = 0x4146, Name = "Hi-Potion-Brecher"},
            new Command {ID = 0x4147, Name = "?ther-Brecher"},
            new Command {ID = 0x4148, Name = "Elixier-Brecher"},
            new Command {ID = 0x4149, Name = "Ph?nixfeder-Brecher"},
            new Command {ID = 0x414A, Name = "Turbo-?ther-Brecher"},
            new Command {ID = 0x414B, Name = "Doppel-Angriff"},
            new Command {ID = 0x414C, Name = "Tripel-Angriff"},
            new Command {ID = 0x414D, Name = "Quattro-Angriff"},
            new Command {ID = 0x414E, Name = "Penta-Angriff"},
            new Command {ID = 0x414F, Name = "Sixta-Angriff"},
            new Command {ID = 0x4150, Name = "Septa-Angriff"},
            new Command {ID = 0x4151, Name = "100 Gill-Fresser"},
            new Command {ID = 0x4152, Name = "1000 Gill-Fresser"},
            new Command {ID = 0x4153, Name = "Giftflügel"},
            new Command {ID = 0x4154, Name = "Stummflügel"},
            new Command {ID = 0x4155, Name = "Tobsuchtflügel"},
            new Command {ID = 0x4156, Name = "Hastflügel"},
            new Command {ID = 0x4157, Name = "Chaosflügel"},
            new Command {ID = 0x4158, Name = "Vollangriff"},
            new Command {ID = 0x4159, Name = "Spitznadel"},
            new Command {ID = 0x415A, Name = "Magie Plus!"},
            new Command {ID = 0x415B, Name = "Magie Minus..."},
            new Command {ID = 0x415C, Name = "MP-Störzer"},
            new Command {ID = 0x415D, Name = "Stampfer"},
            new Command {ID = 0x415E, Name = "Magie Plus!"},
            new Command {ID = 0x415F, Name = "Magie Minus..."},
            new Command {ID = 0x4160, Name = "D?mpelpistole"},
            new Command {ID = 0x4161, Name = "Toxinpistole"},
            new Command {ID = 0x4162, Name = "Angriffsd?mmer"},
            new Command {ID = 0x4163, Name = "Heilungsd?mmer"},
            new Command {ID = 0x4164, Name = "Tech-D?mmer"},
            new Command {ID = 0x4165, Name = "Daten versenden"},
            new Command {ID = 0x4166, Name = "Kraftbolzen"},
            new Command {ID = 0x4167, Name = "Versteckter Kr?ftetrank"},
            new Command {ID = 0x4168, Name = "Versteckte Hi-Potion"},
            new Command {ID = 0x4169, Name = "Versteckter Heldentrank"},
            new Command {ID = 0x416A, Name = "Versteckte Dunkelmaterie"},
            new Command {ID = 0x416B, Name = "Schicksalsschlag"},
            new Command {ID = 0x416C, Name = "Potion-Feger"},
            new Command {ID = 0x416D, Name = "Hi-Potion-Feger"},
            new Command {ID = 0x416E, Name = "Ph?nixfeder-Feger"},
            new Command {ID = 0x416F, Name = "Geflügel Lv.1"},
            new Command {ID = 0x4170, Name = "Geflügel Lv.2"},
            new Command {ID = 0x4171, Name = "Geflügel Lv.3"},
            new Command {ID = 0x4172, Name = "MP-Brecher"},
            new Command {ID = 0x4173, Name = "Goldene Nadel zerstören"},
            new Command {ID = 0x4174, Name = "Allesheiler zerstören"},
            new Command {ID = 0x4175, Name = "Drohvisier"},
            new Command {ID = 0x4176, Name = "Chaosklinge"},
            new Command {ID = 0x4177, Name = "Aufreißer"},
            new Command {ID = 0x4178, Name = "Zorn der Erde"},
            new Command {ID = 0x4179, Name = "Gram der Erde"},
            new Command {ID = 0x417A, Name = "Hitzebarriere Plus"},
            new Command {ID = 0x417B, Name = "N?ssebarriere Plus"},
            new Command {ID = 0x417C, Name = "Strombarriere Plus"},
            new Command {ID = 0x417D, Name = "K?ltebarriere Plus"},
            new Command {ID = 0x417E, Name = "Hitze-Sog Plus"},
            new Command {ID = 0x417F, Name = "N?sse-Sog Plus"},
            new Command {ID = 0x4180, Name = "Strom-Sog Plus"},
            new Command {ID = 0x4181, Name = "K?lte-Sog Plus"},
            new Command {ID = 0x4182, Name = "Hitzebarriere Aus"},
            new Command {ID = 0x4183, Name = "N?ssebarriere Aus"},
            new Command {ID = 0x4184, Name = "Strombarriere Aus"},
            new Command {ID = 0x4185, Name = "K?ltebarriere Aus"},
            new Command {ID = 0x4186, Name = "Hitze-Sog Aus"},
            new Command {ID = 0x4187, Name = "N?sse-Sog Aus"},
            new Command {ID = 0x4188, Name = "Strom-Sog Aus"},
            new Command {ID = 0x4189, Name = "K?lte-Sog Aus"},
            new Command {ID = 0x418A, Name = "Schaut zu Yuna"},
            new Command {ID = 0x418B, Name = "Schaut zu Paine"},
            new Command {ID = 0x418C, Name = "Schaut zu Rikku"},
            new Command {ID = 0x418D, Name = "Rekorder-Booster"},
            new Command {ID = 0x418E, Name = "10000 Gil vernichten!"},
            new Command {ID = 0x418F, Name = "Sammelt Kr?fte"},
            new Command {ID = 0x4190, Name = "Sammelt immer noch Kr?fte"},
            new Command {ID = 0x4191, Name = "Volle Kraft!"},
            new Command {ID = 0x4192, Name = "Kraftschwanz"},
            new Command {ID = 0x4193, Name = "Vollkraftschwanz"},
            new Command {ID = 0x4194, Name = "Mega-Schwanz"},
            new Command {ID = 0x4195, Name = "Halitosis"}, //EN
            new Command {ID = 0x4196, Name = "Antidot verdauen"},
            new Command {ID = 0x4197, Name = "Augentropfen verdauen"},
            new Command {ID = 0x4198, Name = "Echokraut verdauen"},
            new Command {ID = 0x4199, Name = "Weihwasser verdauen"},
            new Command {ID = 0x419A, Name = "Allesheiler verdauen"},
            new Command {ID = 0x419B, Name = "Gelenkb?ndiger"},
            new Command {ID = 0x419C, Name = "Bio-Modus"},
            new Command {ID = 0x419D, Name = "Stumm-Modus"},
            new Command {ID = 0x419E, Name = "Fluch-Modus"},
            new Command {ID = 0x419F, Name = "Kopier-Modus"},
            new Command {ID = 0x41A0, Name = "Modus AUS"},
            new Command {ID = 0x41A1, Name = "Sprengschlag (BIO)"},
            new Command {ID = 0x41A2, Name = "Sprengschlag (STUMM)"},
            new Command {ID = 0x41A3, Name = "Sprengschlag (FLUCH)"},
            new Command {ID = 0x41A4, Name = "Magie Plus!"},
            new Command {ID = 0x41A5, Name = "Magie Minus..."},
            new Command {ID = 0x41A6, Name = "Schneckenrache"},
            new Command {ID = 0x41A7, Name = "Anti-Kost?m-Sphöroid"},
            new Command {ID = 0x41A8, Name = "Das Kost?m nervt!"},
            new Command {ID = 0x41A9, Name = "Yuna nervt!"},
            new Command {ID = 0x41AA, Name = "Rikku nervt!"},
            new Command {ID = 0x41AB, Name = "Paine nervt!"},
            new Command {ID = 0x41AC, Name = "Das nervt mich!"},
            new Command {ID = 0x41AD, Name = "Gorgonenhauch"},
            new Command {ID = 0x41AE, Name = "Grund & Boden"},
            new Command {ID = 0x41AF, Name = "Omega-Graviton"},
            new Command {ID = 0x41B0, Name = "Schleimer"},
            new Command {ID = 0x41B1, Name = "Krakentatscher"},
            new Command {ID = 0x41B2, Name = "Keine Werbung"},
            new Command {ID = 0x41B3, Name = "Keine Werbung"},
            new Command {ID = 0x41B4, Name = "Sterben"},
            new Command {ID = 0x41B5, Name = "Killing Out"},
            new Command {ID = 0x41B6, Name = "Insektenbombe"},
            new Command {ID = 0x41B7, Name = "Hier nimm!"},
            new Command {ID = 0x41B8, Name = "Nimm das!"},
            new Command {ID = 0x41B9, Name = "3000-Needle Special"},
            new Command {ID = 0x41BA, Name = "Keine Werbung"},
            new Command {ID = 0x41BB, Name = "Ich hasse dich!"},
            new Command {ID = 0x41BC, Name = "Stumm-Akupunktur"},
            new Command {ID = 0x41BD, Name = "Blind-Akupunktur"},
            new Command {ID = 0x41BE, Name = "Tobsucht-Akupunktur"},
            new Command {ID = 0x41BF, Name = "Frier-Akupunktur"},
            new Command {ID = 0x41C0, Name = "Schwitz-Akupunktur"},
            new Command {ID = 0x41C1, Name = "Flut-Akupunktur"},
            new Command {ID = 0x41C2, Name = "Schock-Akupunktur"},
            new Command {ID = 0x41C3, Name = "Mitternachtsschrei"},
            new Command {ID = 0x41C4, Name = "Endzeit-Meteor"},
            new Command {ID = 0x41C5, Name = "Ich hasse dieses Kost?m!"},
            new Command {ID = 0x41C6, Name = "Oversoul herauslassen"},
            new Command {ID = 0x41C7, Name = "Zauberstrahl"},
            new Command {ID = 0x41C8, Name = "Gatling-Kanone"},
            new Command {ID = 0x41C9, Name = "Pistolenhasser"},
            new Command {ID = 0x41CA, Name = "Schwerthaser"},
            new Command {ID = 0x41CB, Name = "Zauberhasser"},
            new Command {ID = 0x41CC, Name = "Pistolenkiller"},
            new Command {ID = 0x41CD, Name = "Schwertkiller"},
            new Command {ID = 0x41CE, Name = "Zauberkiller"},
            new Command {ID = 0x41CF, Name = "Samurai-Hasser"},
            new Command {ID = 0x41D0, Name = "Weißmagie-Hasser"},
            new Command {ID = 0x41D1, Name = "Item-Schätzen-Hasser"},
            new Command {ID = 0x41D2, Name = "Angriff Plus!"},
            new Command {ID = 0x41D3, Name = "Angriff Minus..."},
            new Command {ID = 0x41D4, Name = "Krisensituation"},
            new Command {ID = 0x41D5, Name = "Angriffssteigerung"},
            new Command {ID = 0x41D6, Name = "Magiesteigerung"},
            new Command {ID = 0x41D7, Name = "Angriff-/Magie-Steigerung"},
            new Command {ID = 0x41D8, Name = "Rolle"},
            new Command {ID = 0x41D9, Name = "Rolle"},
            new Command {ID = 0x41DA, Name = "Angriff"},
            new Command {ID = 0x41DB, Name = "Angriff Plus"},
            new Command {ID = 0x41DC, Name = "Abwehr Plus "},
            new Command {ID = 0x41DD, Name = "Magie Plus"},
            new Command {ID = 0x41DE, Name = "EXP-0"},
            new Command {ID = 0x41DF, Name = "Angriff"},
            new Command {ID = 0x41E0, Name = "Umkleidenadel"},
            new Command {ID = 0x41E1, Name = "Angriff"},
            new Command {ID = 0x41E2, Name = "Angriff"},
            new Command {ID = 0x41E3, Name = "Angriff"},
            new Command {ID = 0x41E4, Name = "Angriff"},
            new Command {ID = 0x41E5, Name = "Angriff"},
            new Command {ID = 0x41E6, Name = "Todesattacke / ƒLƒ‹ƒAƒ^ƒbƒN"},
            new Command {ID = 0x41E7, Name = "Angriff"},
            new Command {ID = 0x41E8, Name = "Angriff"},
            new Command {ID = 0x41E9, Name = "Feuer"},
            new Command {ID = 0x41EA, Name = "Eis"},
            new Command {ID = 0x41EB, Name = "Blitz"},
            new Command {ID = 0x41EC, Name = "Wasser"},
            new Command {ID = 0x41ED, Name = "Feura"},
            new Command {ID = 0x41EE, Name = "Eisra"},
            new Command {ID = 0x41EF, Name = "Blitzra"},
            new Command {ID = 0x41F0, Name = "Wassra"},
            new Command {ID = 0x41F1, Name = "Feuga"},
            new Command {ID = 0x41F2, Name = "Eisga"},
            new Command {ID = 0x41F3, Name = "Blitzga"},
            new Command {ID = 0x41F4, Name = "Wassga"},
            new Command {ID = 0x41F5, Name = "Schlitzkralle"},
            new Command {ID = 0x41F6, Name = "Kombo"},
            new Command {ID = 0x41F7, Name = "Geflügel Lv.1"},
            new Command {ID = 0x41F8, Name = "Geflügel Lv.2"},
            new Command {ID = 0x41F9, Name = "Geflügel Lv.3"},
            new Command {ID = 0x41FA, Name = "Flare"},
            new Command {ID = 0x41FB, Name = "Ultima"},
            new Command {ID = 0x41FC, Name = "Intens-Welle"},
            new Command {ID = 0x41FD, Name = "Steinerner Hauch"},
            new Command {ID = 0x41FE, Name = "Br?derchens Rundumschlag"},
            new Command {ID = 0x41FF, Name = "Br?derchens Explosionsattacke"},
            new Command {ID = 0x4200, Name = "Br?derchens Heilungs & Angriff+10 Technik"},
            new Command {ID = 0x4201, Name = "Guess I'll hit ya"},
            new Command {ID = 0x4202, Name = "Sorry about that"},
            new Command {ID = 0x4203, Name = "Spiral Cut"},
            new Command {ID = 0x4204, Name = "Machismo"},
            new Command {ID = 0x4205, Name = "Blitz Ace"},
            new Command {ID = 0x4206, Name = "Full Break"},
            new Command {ID = 0x4207, Name = "Dragon Fang"},
            new Command {ID = 0x4208, Name = "Shooting Star"},
            new Command {ID = 0x4209, Name = "T. Fire"},
            new Command {ID = 0x420A, Name = "T. Blizzard"},
            new Command {ID = 0x420B, Name = "T. Thunder"},
            new Command {ID = 0x420C, Name = "T. Water"},
            new Command {ID = 0x420D, Name = "Jump"},
            new Command {ID = 0x420E, Name = "Sunshine"},
            new Command {ID = 0x420F, Name = "Requiem"},
            new Command {ID = 0x4210, Name = "Clione"},
            new Command {ID = 0x4211, Name = "Die"},
            new Command {ID = 0x4212, Name = "Squirt Gun"},
            new Command {ID = 0x4213, Name = "Status Attacke"},
            new Command {ID = 0x4214, Name = "Die Verbannung"},
            new Command {ID = 0x4215, Name = "Wahnstrahl"},
            new Command {ID = 0x4216, Name = "Versteckter Heldentrank"},
            new Command {ID = 0x4217, Name = "Himmelswind"},
            new Command {ID = 0x4218, Name = "Totalabwehr"},
            new Command {ID = 0x4219, Name = "Z?ndschnur"},
            new Command {ID = 0x421A, Name = "Unums Strahl"},
            new Command {ID = 0x421B, Name = "Duos Gifthauch"},
            new Command {ID = 0x421C, Name = "Trias Blitzangriff"},
            new Command {ID = 0x421D, Name = "Quattrums Steinschlag"},
            new Command {ID = 0x421E, Name = "Gemachga"},
            new Command {ID = 0x421F, Name = "Turbo-?ther"},
            new Command {ID = 0x4220, Name = "Hastga"},
            new Command {ID = 0x4221, Name = "Meteor "},
            new Command {ID = 0x4222, Name = "/ ƒOƒ‰ƒXƒ^["},
            new Command {ID = 0x4223, Name = "Zweierw?rfel"},
            new Command {ID = 0x4224, Name = "Telekinese"},
            new Command {ID = 0x4225, Name = "Helmspalter"},
            new Command {ID = 0x4226, Name = "Richterskala"},
            new Command {ID = 0x4227, Name = "K?sschentanz "},
            new Command {ID = 0x4228, Name = "La Ni?a "},
            new Command {ID = 0x4229, Name = "Emblem attacke"},
            new Command {ID = 0x422A, Name = "Thanatos-Emblem"},
            new Command {ID = 0x422B, Name = "Bauchplatscher"},
            new Command {ID = 0x422C, Name = "Nebelstrahl"},
            new Command {ID = 0x422D, Name = "Beben"},
            new Command {ID = 0x422E, Name = "B?lle"},
            new Command {ID = 0x422F, Name = "Kugel"},
            new Command {ID = 0x4230, Name = "Laserstrahlen"},
            new Command {ID = 0x4231, Name = "Rauch-Hauch"},
            new Command {ID = 0x4232, Name = "(langer Name)"},
            new Command {ID = 0x4233, Name = "(langer Name)"},
            new Command {ID = 0x4234, Name = "(langer Name)"},
            new Command {ID = 0x4235, Name = "(langer Name)"},
            new Command {ID = 0x4236, Name = "Meteror"},
            new Command {ID = 0x4237, Name = "Feuerzauber"},
        };
    }

    public class Command
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}