using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Farplane.FFX2.Values
{
    public static class Creatures
    {
        public static Creature[] CreatureList =
        {
            new Creature { ID = 0x1000, Name="Nichts (Absturz)" },
            new Creature { ID = 0x1001, Name="Sallet (CC) " },
            new Creature { ID = 0x1002, Name="Bicocette (CC)" },
            new Creature { ID = 0x1003, Name="Barbuta (CC)", Type=CreatureType.CreatureCreate },
            new Creature { ID = 0x1004, Name="Armet (CC)" },
            new Creature { ID = 0x1005, Name="Bascinet (CC)" },
            new Creature { ID = 0x1006, Name="Zurvan (CC)" },
            new Creature { ID = 0x1007, Name="Varan (CC)" },
            new Creature { ID = 0x1008, Name="Arast (CC)", Type=CreatureType.CreatureCreate },
            new Creature { ID = 0x1009, Name="Coyote (CC)" },
            new Creature { ID = 0x100A, Name="Wild Wolf (CC)" },
            new Creature { ID = 0x100B, Name="Killer Hound (CC)" },
            new Creature { ID = 0x100C, Name="White Fang (CC)" },
            new Creature { ID = 0x100D, Name="Canis Major (CC)" },
            new Creature { ID = 0x100E, Name="Lupus (CC)" },
            new Creature { ID = 0x100F, Name="Tindalos (CC)" },
            new Creature { ID = 0x1010, Name="Flan Azul (CC)" },
            new Creature { ID = 0x1011, Name="Flan Amarillo (CC)" },
            new Creature { ID = 0x1012, Name="Flan Palido (CC)" },
            new Creature { ID = 0x1013, Name="Flan Blanco (CC)" },
            new Creature { ID = 0x1014, Name="Flan Rojo (CC)" },
            new Creature { ID = 0x1015, Name="Flan Azabache (CC)" },
            new Creature { ID = 0x1016, Name="Gecko (CC)" },
            new Creature { ID = 0x1017, Name="Agama (CC)" },
            new Creature { ID = 0x1018, Name="Skink (CC)" },
            new Creature { ID = 0x1019, Name="Anole (CC)" },
            new Creature { ID = 0x101A, Name="Archaeothyris (CC)", Type=CreatureType.CreatureCreate },
            new Creature { ID = 0x101B, Name="Lacerta (CC)" },
            new Creature { ID = 0x101C, Name="Divebeak (CC)" },
            new Creature { ID = 0x101D, Name="Peregrine (CC)" },
            new Creature { ID = 0x101E, Name="Aqulia (CC)" },
            new Creature { ID = 0x101F, Name="Death Dauber (CC)" },
            new Creature { ID = 0x1020, Name="Assassin Bee (CC)", Type=CreatureType.CreatureCreate},
            new Creature { ID = 0x1021, Name="Aculeate (CC)" },
            new Creature { ID = 0x1022, Name="Vespa (CC)" },
            new Creature { ID = 0x1023, Name="Ahriman (CC)" },
            new Creature { ID = 0x1024, Name="Fly Eye (CC)" },
            new Creature { ID = 0x1025, Name="Vertigo (CC)" },
            new Creature { ID = 0x1026, Name="Grim Gaze (CC)" },
            new Creature { ID = 0x1027, Name="Purpurea (CC)" },
            new Creature { ID = 0x1028, Name="Leucophylla (CC)" },
            new Creature { ID = 0x1029, Name="Cephalotus (CC)" },
            new Creature { ID = 0x102A, Name="Shantak (CC)" },
            new Creature { ID = 0x102B, Name="Zu (CC)" },
            new Creature { ID = 0x102C, Name="Sandworm (CC)" },
            new Creature { ID = 0x102D, Name="Earthworm (CC)" },
            new Creature { ID = 0x102E, Name="YSLS-99 (CC)" },
            new Creature { ID = 0x102F, Name="YSLS-Zero (CC)" },
            new Creature { ID = 0x1030, Name="Haunt (CC)" },
            new Creature { ID = 0x1031, Name="Phantom (CC)" },
            new Creature { ID = 0x1032, Name="Nashorn (CC)" },
            new Creature { ID = 0x1033, Name="Quadricorn (CC)" },
            new Creature { ID = 0x1034, Name="Balivarha (CC)" },
            new Creature { ID = 0x1035, Name="Lesser Drake (CC)" },
            new Creature { ID = 0x1036, Name="Spine Drage (CC)" },
            new Creature { ID = 0x1037, Name="Bolt Drage (CC)" },
            new Creature { ID = 0x1038, Name="Greater Drake (CC)" },
            new Creature { ID = 0x1039, Name="Elder Drake (CC)" },
            new Creature { ID = 0x103A, Name="Malboro (CC)" },
            new Creature { ID = 0x103B, Name="Greater Malboro (CC)" },
            new Creature { ID = 0x103C, Name="Gigas (CC)" },
            new Creature { ID = 0x103D, Name="Gug (CC)" },
            new Creature { ID = 0x103E, Name="Hrimthurs (CC)" },
            new Creature { ID = 0x103F, Name="Yellow Elemental (CC)" },
            new Creature { ID = 0x1040, Name="White Elemental (CC)" },
            new Creature { ID = 0x1041, Name="Red Elemental (CC)" },
            new Creature { ID = 0x1042, Name="Gold Elemental (CC)" },
            new Creature { ID = 0x1043, Name="Blue Elemental (CC)" },
            new Creature { ID = 0x1044, Name="Dark Elemental (CC)" },
            new Creature { ID = 0x1045, Name="Black Elemental (CC)" },
            new Creature { ID = 0x1046, Name="Takouba (CC)" },
            new Creature { ID = 0x1047, Name="Barong (CC)" },
            new Creature { ID = 0x1048, Name="Behemoth (CC)" },
            new Creature { ID = 0x1049, Name="Humbaba (CC)" },
            new Creature { ID = 0x104A, Name="Protochimera (CC)" },
            new Creature { ID = 0x104B, Name="Rhyos (CC)" },
            new Creature { ID = 0x104C, Name="Coeurl (CC)" },
            new Creature { ID = 0x104D, Name="Queen Coeurl (CC)" },
            new Creature { ID = 0x104E, Name="Machina Ranger (CC)" },
            new Creature { ID = 0x104F, Name="Machina Hunter (CC)" },
            new Creature { ID = 0x1050, Name="Machina Soldier (CC)" },
            new Creature { ID = 0x1051, Name="Tomb (CC)" },
            new Creature { ID = 0x1052, Name="Scout Machina (CC)" },
            new Creature { ID = 0x1053, Name="Guard Machina (CC)" },
            new Creature { ID = 0x1054, Name="Assault Machina (CC)" },
            new Creature { ID = 0x1055, Name="Iron Giant (CC)" },
            new Creature { ID = 0x1056, Name="Iron Giant " },
            new Creature { ID = 0x1057, Name="Wolframator (andere Version) (CC)" },
            new Creature { ID = 0x1058, Name="Kukulcan (CC)" },
            new Creature { ID = 0x1059, Name="Gucumatz (CC)" },
            new Creature { ID = 0x105A, Name="Adamantoise (CC)" },
            new Creature { ID = 0x105B, Name="Daeva (CC)" },
            new Creature { ID = 0x105C, Name="Ochu (CC)" },
            new Creature { ID = 0x105D, Name="Flailing Ochu (CC)" },
            new Creature { ID = 0x105E, Name="YAC-13 (CC)" },
            new Creature { ID = 0x105F, Name="YAC-62 (CC)" },
            new Creature { ID = 0x1060, Name="Bomb (CC)" },
            new Creature { ID = 0x1061, Name="Detonator  (CC)" },
            new Creature { ID = 0x1062, Name="Volcano (CC)" },
            new Creature { ID = 0x1063, Name="YAC-28 (CC)" },
            new Creature { ID = 0x1064, Name="YAC-71 (CC)" },
            new Creature { ID = 0x1065, Name="Ordensk?ster " },
            new Creature { ID = 0x1066, Name="Ordensstörmer " },
            new Creature { ID = 0x1067, Name="Ordenswache" },
            new Creature { ID = 0x1068, Name="Ordensoffizier" },
            new Creature { ID = 0x1069, Name="Wunderpott (FFX)" },
            new Creature { ID = 0x106A, Name="Cactuar (CC)" },
            new Creature { ID = 0x106B, Name="Cactuar" },
            new Creature { ID = 0x106C, Name="Stalwart (CC)" },
            new Creature { ID = 0x106D, Name="Bully Cap (CC)" },
            new Creature { ID = 0x106E, Name="Mycotoxin (CC)" },
            new Creature { ID = 0x106F, Name="Mushroom Cloud (CC)" },
            new Creature { ID = 0x1070, Name="Pairilas (Beta) (CC)" },
            new Creature { ID = 0x1071, Name="Jahi (CC)" },
            new Creature { ID = 0x1072, Name="Tonberry (CC)" },
            new Creature { ID = 0x1073, Name="Mega-Tonberry (CC)" },
            new Creature { ID = 0x1074, Name="Guado-Wache (FFX)" },
            new Creature { ID = 0x1075, Name="Niemand" },
            new Creature { ID = 0x1076, Name="Niemand" },
            new Creature { ID = 0x1077, Name="Sahagin (FFX)" },
            new Creature { ID = 0x1078, Name="Claret Dragon (CC)" },
            new Creature { ID = 0x1079, Name="Zalamander (CC)" },
            new Creature { ID = 0x107A, Name="Flame Dragon (CC)" },
            new Creature { ID = 0x107B, Name="Recoil (CC)" },
            new Creature { ID = 0x107C, Name="Flak Python (CC)" },
            new Creature { ID = 0x107D, Name="Viper Sniper (CC)" },
            new Creature { ID = 0x107E, Name="Creeper (CC)" },
            new Creature { ID = 0x107F, Name="Hug Bug (CC)" },
            new Creature { ID = 0x1080, Name="King VERMIN! (CC)" },
            new Creature { ID = 0x1081, Name="Ormi (CC)" },
            new Creature { ID = 0x1082, Name="Logos (CC)" },
            new Creature { ID = 0x1083, Name="Leblanc (CC)" },
            new Creature { ID = 0x1084, Name="Boris (CC)" },
            new Creature { ID = 0x1085, Name="Goon (CC)" },
            new Creature { ID = 0x1086, Name="Mr. Goon (CC)" },
            new Creature { ID = 0x1087, Name="Dr. Goon (CC)", Type=CreatureType.CreatureCreate },
            new Creature { ID = 0x1088, Name="She-Goon (CC)" },
            new Creature { ID = 0x1089, Name="Ms. Goon (CC)" },
            new Creature { ID = 0x108A, Name="Fem-Goon (CC)" },
            new Creature { ID = 0x108B, Name="Niemand" },
            new Creature { ID = 0x108C, Name="Piranha (FFX)" },
            new Creature { ID = 0x108D, Name="Planschfisch (FFX)" },
            new Creature { ID = 0x108E, Name="Roter Fisch (Beta)" },
            new Creature { ID = 0x108F, Name="Sahagin (FFX)" },
            new Creature { ID = 0x1090, Name="Sahagin (CC)" },
            new Creature { ID = 0x1091, Name="Haizhe (CC)" },
            new Creature { ID = 0x1092, Name="Deep Haizhe (CC)" },
            new Creature { ID = 0x1093, Name="Xiphactinus (CC)", Type=CreatureType.CreatureCreate },
            new Creature { ID = 0x1094, Name="Dinictis (CC)" },
            new Creature { ID = 0x1095, Name="Tentacles (CC)" },
            new Creature { ID = 0x1096, Name="Ultima Weapon (CC)" },
            new Creature { ID = 0x1097, Name="Omega Weapon (CC)" },
            new Creature { ID = 0x1098, Name="Paragon (CC)" },
            new Creature { ID = 0x1099, Name="Chocobo Eater (CC)", Type=CreatureType.CreatureCreate },
            new Creature { ID = 0x109A, Name="Anything Eater (CC)" },
            new Creature { ID = 0x109B, Name="Shell Shocker (CC)" },
            new Creature { ID = 0x109C, Name="Pop Fry (CC)" },
            new Creature { ID = 0x109D, Name="Efrye (Beta) (FFX)" },
            new Creature { ID = 0x109E, Name="Amorphous Gel(CC)" },
            new Creature { ID = 0x109F, Name="Protean Gel (CC)" },
            new Creature { ID = 0x10A0, Name="Machina Panzer (CC)" },
            new Creature { ID = 0x10A1, Name="Rekorder ? (Unsichtbar)" },
            new Creature { ID = 0x10A2, Name="Guardian Beast (CC)" },
            new Creature { ID = 0x10A3, Name="Azi Dahaka (CC)" },
            new Creature { ID = 0x10A4, Name="Valfaris" },
            new Creature { ID = 0x10A5, Name="Ifrit " },
            new Creature { ID = 0x10A6, Name="Ixion " },
            new Creature { ID = 0x10A7, Name="Shiva" },
            new Creature { ID = 0x10A8, Name="Bahamut " },
            new Creature { ID = 0x10A9, Name="Anima" },
            new Creature { ID = 0x10AA, Name="Yojinbo" },
            new Creature { ID = 0x10AB, Name="Mug" },
            new Creature { ID = 0x10AC, Name="Dug " },
            new Creature { ID = 0x10AD, Name="Rug" },
            new Creature { ID = 0x10AE, Name="Daigoro (Yojinbos Hund)" },
            new Creature { ID = 0x10AF, Name="Baralai" },
            new Creature { ID = 0x10B0, Name="besessener Baralai " },
            new Creature { ID = 0x10B1, Name="besessener Gippel" },
            new Creature { ID = 0x10B2, Name="Schurke" },
            new Creature { ID = 0x10B3, Name="Liga-R?nger" },
            new Creature { ID = 0x10B4, Name="Liga-Kämpfer" },
            new Creature { ID = 0x10B5, Name="Junger Ronso" },
            new Creature { ID = 0x10B6, Name="Garik" },
            new Creature { ID = 0x10B7, Name="Yaibal " },
            new Creature { ID = 0x10B8, Name="Lucille" },
            new Creature { ID = 0x10B9, Name="Elma" },
            new Creature { ID = 0x10BA, Name="Niemand" },
            new Creature { ID = 0x10BB, Name="Niemand" },
            new Creature { ID = 0x10BC, Name="Chocobo (CC)" },
            new Creature { ID = 0x10BD, Name="Liga-Krieger" },
            new Creature { ID = 0x10BE, Name="Liga-Sp?herin" },
            new Creature { ID = 0x10BF, Name="Liga-Agentin" },
            new Creature { ID = 0x10C0, Name="Liga-Störmerin" },
            new Creature { ID = 0x10C1, Name="Liga-Fechterin" },
            new Creature { ID = 0x10C2, Name="Testapparat" },
            new Creature { ID = 0x10C3, Name="(Teil vom Testapparat)" },
            new Creature { ID = 0x10C4, Name="(Teil vom Testapparat)" },
            new Creature { ID = 0x10C5, Name="(Teil vom Testapparat)" },
            new Creature { ID = 0x10C6, Name="(Teil vom Testapparat)" },
            new Creature { ID = 0x10C7, Name="(Teil vom Testapparat)" },
            new Creature { ID = 0x10C8, Name="(Teil vom Testapparat)" },
            new Creature { ID = 0x10C9, Name="Niemand" },
            new Creature { ID = 0x10CA, Name="Niemand" },
            new Creature { ID = 0x10CB, Name="Niemand" },
            new Creature { ID = 0x10CC, Name="Niemand" },
            new Creature { ID = 0x10CD, Name="Niemand" },
            new Creature { ID = 0x10CE, Name="Niemand" },
            new Creature { ID = 0x10CF, Name="Niemand" },
            new Creature { ID = 0x10D0, Name="(Teil vom Testapparat)" },
            new Creature { ID = 0x10D1, Name="(Teil vom Testapparat)" },
            new Creature { ID = 0x10D2, Name="Liga-Gefreiter" },
            new Creature { ID = 0x10D3, Name="Liga-Soldat" },
            new Creature { ID = 0x10D4, Name="Liga-Kämpfer" },
            new Creature { ID = 0x10D5, Name="Purpurmahr" },
            new Creature { ID = 0x10D6, Name="Liga-Magierin" },
            new Creature { ID = 0x10D7, Name="Liga-Meisterin" },
            new Creature { ID = 0x10D8, Name="Beclem (?)" },
            new Creature { ID = 0x10D9, Name="Hexapod (CC)" },
            new Creature { ID = 0x10DA, Name="Machina Leader (CC)" },
            new Creature { ID = 0x10DB, Name="Killer Machina (CC)" },
            new Creature { ID = 0x10DC, Name="Sahagin Prince (CC)" },
            new Creature { ID = 0x10DD, Name="Aranea (CC)" },
            new Creature { ID = 0x10DE, Name="Dormen (CC)" },
            new Creature { ID = 0x10DF, Name="Monument (CC)" },
            new Creature { ID = 0x10E0, Name="Aeshma (CC)" },
            new Creature { ID = 0x10E1, Name="Aka Manah (CC)" },
            new Creature { ID = 0x10E2, Name="Taromati (Beta) (CC)" },
            new Creature { ID = 0x10E3, Name="Wight (CC)" },
            new Creature { ID = 0x10E4, Name="Lich (CC)" },
            new Creature { ID = 0x10E5, Name="Adamantortoise (CC)" },
            new Creature { ID = 0x10E6, Name="Ironside (CC)" },
            new Creature { ID = 0x10E7, Name="Rukh (CC)" },
            new Creature { ID = 0x10E8, Name="Concherer  (CC)" },
            new Creature { ID = 0x10E9, Name="Rekorder (Unsichtbar)" },
            new Creature { ID = 0x10EA, Name="Rekorder (Unsichtbar)" },
            new Creature { ID = 0x10EB, Name="Machina Striker (CC)" },
            new Creature { ID = 0x10EC, Name="Riesen-Wunderpott (Beta)" },
            new Creature { ID = 0x10ED, Name="Jumbo Cactuar (CC)" },
            new Creature { ID = 0x10EE, Name="Drowsy Ochu", Type=CreatureType.CreatureCreate },
            new Creature { ID = 0x10EF, Name="Chac (CC)" },
            new Creature { ID = 0x10F0, Name="Großer Chocobo (Beta)" },
            new Creature { ID = 0x10F1, Name="Ormi " },
            new Creature { ID = 0x10F2, Name="Ormi " },
            new Creature { ID = 0x10F3, Name="Ormi" },
            new Creature { ID = 0x10F4, Name="Ormi " },
            new Creature { ID = 0x10F5, Name="Ormi" },
            new Creature { ID = 0x10F6, Name="Ormi" },
            new Creature { ID = 0x10F7, Name="Logos" },
            new Creature { ID = 0x10F8, Name="Logos" },
            new Creature { ID = 0x10F9, Name="Logos" },
            new Creature { ID = 0x10FA, Name="Logos" },
            new Creature { ID = 0x10FB, Name="Logos" },
            new Creature { ID = 0x10FC, Name="Leblanc" },
            new Creature { ID = 0x10FD, Name="Leblanc" },
            new Creature { ID = 0x10FE, Name="besessene Rikku " },
            new Creature { ID = 0x10FF, Name="Niemand" },
            new Creature { ID = 0x1100, Name="besessene Paine (unsichtbares Schwert)" },
            new Creature { ID = 0x1101, Name="Niemand" },
            new Creature { ID = 0x1102, Name="besessener Nooj" },
            new Creature { ID = 0x1103, Name="Niemand" },
            new Creature { ID = 0x1104, Name="Shuyin (unsichtbares Schwert)" },
            new Creature { ID = 0x1105, Name="Niemand" },
            new Creature { ID = 0x1106, Name="Geos Maximus" },
            new Creature { ID = 0x1107, Name="Erz-W?chter" },
            new Creature { ID = 0x1108, Name="Shuyin (steht da wie eine Vogelscheuche)" },
            new Creature { ID = 0x1109, Name="Niemand" },
            new Creature { ID = 0x110A, Name="Bandit (ohne Schwert)" },
            new Creature { ID = 0x110B, Name="Niemand" },
            new Creature { ID = 0x110C, Name="Angra Mainu" },
            new Creature { ID = 0x110D, Name="Angra Mainu - Zarisha" },
            new Creature { ID = 0x110E, Name="Angra Mainu - Taurvi" },
            new Creature { ID = 0x110F, Name="Elder Zurvan (CC)" },
            new Creature { ID = 0x1110, Name="Riesen-Sturzspecht (Beta)" },
            new Creature { ID = 0x1111, Name="Wasp Queen (CC)" },
            new Creature { ID = 0x1112, Name="Sahagin Chief (CC)" },
            new Creature { ID = 0x1113, Name="Großgesepenst (CC)" },
            new Creature { ID = 0x1114, Name="King Takouba (CC)" },
            new Creature { ID = 0x1115, Name="Big Bully Cap (CC)" },
            new Creature { ID = 0x1116, Name="Grabmal (CC)" },
            new Creature { ID = 0x1117, Name="Elma (Gegner) " },
            new Creature { ID = 0x1118, Name="???? (Falsche Yuna) (No Trap?)" },
            new Creature { ID = 0x1119, Name="Niemand" },
            new Creature { ID = 0x111A, Name="Vegnagun (Schwanz)" },
            new Creature { ID = 0x111B, Name="Vegnagun (Fu?)" },
            new Creature { ID = 0x111C, Name="Vegnagun 284 (Rote Kugel)" },
            new Creature { ID = 0x111D, Name="Vegnagun 285 (Grüne Kugel)" },
            new Creature { ID = 0x111E, Name="Vegnagun 286 (Gelbe Kugel)" },
            new Creature { ID = 0x111F, Name="Vegnagun (Body)" },
            new Creature { ID = 0x1120, Name="(Rotes dreieck) (Beta?)" },
            new Creature { ID = 0x1121, Name="(Rotes dreieck) (Beta?)" },
            new Creature { ID = 0x1122, Name="Vegnagun (Body?)" },
            new Creature { ID = 0x1123, Name="Vegnagun (rechter Sto?zahn)" },
            new Creature { ID = 0x1124, Name="Vegnagun (linker Sto?zahn)" },
            new Creature { ID = 0x1125, Name="Niemand" },
            new Creature { ID = 0x1126, Name="Heavy Sallet (CC)" },
            new Creature { ID = 0x1127, Name="Trema " },
            new Creature { ID = 0x1128, Name="Nichts (Absturz)" },
            new Creature { ID = 0x1129, Name="Weltmeister (Wakkas Ultimative Waffe aus FFX)" },
            new Creature { ID = 0x112A, Name="Niemand" },
            new Creature { ID = 0x112B, Name="Vegnagun Part 1 (?)" },
            new Creature { ID = 0x112C, Name="Vegnagun Part 2 (?)" },
            new Creature { ID = 0x112D, Name="Niemand" },
            new Creature { ID = 0x112E, Name="Battlesnake (CC)" },
            new Creature { ID = 0x112F, Name="Insect Matriarch (CC)" },
            new Creature { ID = 0x1130, Name="Critical Bug (CC)" },
            new Creature { ID = 0x1131, Name="Niemand" },
            new Creature { ID = 0x1132, Name="Niemand" },
            new Creature { ID = 0x1133, Name="Niemand" },
            new Creature { ID = 0x1134, Name="Brother (CC)" },
            new Creature { ID = 0x1135, Name="Buddy (CC)" },
            new Creature { ID = 0x1136, Name="Niemand" },
            new Creature { ID = 0x1137, Name="Auron (CC)" },
            new Creature { ID = 0x1138, Name="Niemand" },
            new Creature { ID = 0x1139, Name="Kimahri (CC)" },
            new Creature { ID = 0x113A, Name="Niemand" },
            new Creature { ID = 0x113B, Name="Lulu (CC)" },
            new Creature { ID = 0x113C, Name="Niemand" },
            new Creature { ID = 0x113D, Name="Tidus (CC)" },
            new Creature { ID = 0x113E, Name="Niemand" },
            new Creature { ID = 0x113F, Name="Seymour (CC)" },
            new Creature { ID = 0x1140, Name="Niemand" },
            new Creature { ID = 0x1141, Name="Baralai (CC)" },
            new Creature { ID = 0x1142, Name="Nooj (CC)" },
            new Creature { ID = 0x1143, Name="Gippel (CC)" },
            new Creature { ID = 0x1144, Name="Garik (CC)" },
            new Creature { ID = 0x1145, Name="Yaibal (CC)" },
            new Creature { ID = 0x1146, Name="Lucille (CC)" },
            new Creature { ID = 0x1147, Name="Elma (CC)" },
            new Creature { ID = 0x1148, Name="Trema (CC)" },
            new Creature { ID = 0x1149, Name="Shinra (Demon Form) (CC)" },
            new Creature { ID = 0x114A, Name="Unum (Teil von Major Numerus)" },
            new Creature { ID = 0x114B, Name="Duo (Teil von Major Numerus)" },
            new Creature { ID = 0x114C, Name="Tria (Teil von Major Numerus) " },
            new Creature { ID = 0x114D, Name="Quartum (Teil von Major Numerus)" },
            new Creature { ID = 0x114E, Name="Major Numerus (Hauptk?rper)" },
            new Creature { ID = 0x114F, Name="(Irgendwas kleines...)" },
            new Creature { ID = 0x1150, Name="Major Numerus (Schwanz)" },
            new Creature { ID = 0x1151, Name="(Felsbrocken?)" },
            new Creature { ID = 0x1152, Name="(Felsbrocken?) " },
            new Creature { ID = 0x1153, Name="Chocobo (CC)" },
            new Creature { ID = 0x1154, Name="Riesen-Chocobo" },
            new Creature { ID = 0x1155, Name="Riesen-Barbute " },
            new Creature { ID = 0x1156, Name="Riesen-Whitefang " },
            new Creature { ID = 0x1157, Name="Riesen-Falke " },
            new Creature { ID = 0x1158, Name="Riesen-Vertigo " },
            new Creature { ID = 0x1159, Name="Riesen-Typ 99" },
            new Creature { ID = 0x115A, Name="Riesen-Balivarha (Beta)" },
            new Creature { ID = 0x115B, Name="Riesen-Salamander (Beta)" },
            new Creature { ID = 0x115C, Name="Riesen-Dornen-Drage (Beta)" },
            new Creature { ID = 0x115D, Name="Riesen-Gigas (Beta)" },
            new Creature { ID = 0x115E, Name="Riesen-Barong (Beta)" },
            new Creature { ID = 0x115F, Name="Riesen-Proto-Chim?ra (Beta)" },
            new Creature { ID = 0x1160, Name="Riesen-Eisengigant (Beta)" },
            new Creature { ID = 0x1161, Name="Riesen-Adaman Tamai (Beta)" },
            new Creature { ID = 0x1162, Name="Riesen-Defender (Beta)" },
            new Creature { ID = 0x1163, Name="Riesen-Obergehilfe (Beta) " },
            new Creature { ID = 0x1164, Name="Riesen-Haizuo (Beta) " },
            new Creature { ID = 0x1165, Name="Riesen-Tiefflug-Haizuo (Beta) " },
            new Creature { ID = 0x1166, Name="Riesen-Tentakulus (Beta) " },
            new Creature { ID = 0x1167, Name="Riesen-Chocogourmet (Beta) " },
            new Creature { ID = 0x1168, Name="Riesen-Steinschnecke (Beta)" },
            new Creature { ID = 0x1169, Name="Riesen-Schatzgardist (Beta)" },
            new Creature { ID = 0x116A, Name="Riesen-Gatling Kobra (Beta)" },
            new Creature { ID = 0x116B, Name="Valfaris " },
            new Creature { ID = 0x116C, Name="Ifrit" },
            new Creature { ID = 0x116D, Name="Ixion" },
            new Creature { ID = 0x116E, Name="Bahamut" },
            new Creature { ID = 0x116F, Name="Kaktor " },
            new Creature { ID = 0x1170, Name="Sklave" },
            new Creature { ID = 0x1171, Name="Sklavin " },
            new Creature { ID = 0x1172, Name="Nichts (Absturz)" }
        };
    }

    public class Creature
    {
        public CreatureType Type { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
    }

    public enum CreatureType
    {
        CreatureCreate,
        Normal,
        Boss
    }
}
