using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Farplane.FFX2.Values
{
    public static class GarmentGridNodes
    {
        public static GarmentGridNode[] GarmentGridNodesList =
        {
            new GarmentGridNode {GarmentGridID = 0, GGOffset = 0x0, NodePosition = 0, GarmentGridName = "First Steps"},
            new GarmentGridNode {GarmentGridID = 0, GGOffset = 0x0, NodePosition = 1, GarmentGridName = "First Steps"},
            new GarmentGridNode {GarmentGridID = 0, GGOffset = 0x0, NodePosition = 2, GarmentGridName = "First Steps"},
            new GarmentGridNode {GarmentGridID = 0, GGOffset = 0x0, NodePosition = 3, GarmentGridName = "First Steps"},
            new GarmentGridNode {GarmentGridID = 0, GGOffset = 0x0, NodePosition = 4, GarmentGridName = "First Steps"},
            new GarmentGridNode {GarmentGridID = 0, GGOffset = 0x0, NodePosition = 5, GarmentGridName = "First Steps"},
            new GarmentGridNode {GarmentGridID = 1, GGOffset = 0x20, NodePosition = 0, GarmentGridName = "Vanguard"},
            new GarmentGridNode {GarmentGridID = 1, GGOffset = 0x20, NodePosition = 1, GarmentGridName = "Vanguard"},
            new GarmentGridNode {GarmentGridID = 1, GGOffset = 0x20, NodePosition = 2, GarmentGridName = "Vanguard"},
            new GarmentGridNode {GarmentGridID = 1, GGOffset = 0x20, NodePosition = 3, GarmentGridName = "Vanguard"},
            new GarmentGridNode {GarmentGridID = 1, GGOffset = 0x20, NodePosition = 8, GarmentGridName = "Vanguard"},
            new GarmentGridNode {GarmentGridID = 2, GGOffset = 0x40, NodePosition = 0, GarmentGridName = "Bum Rush"},
            new GarmentGridNode {GarmentGridID = 2, GGOffset = 0x40, NodePosition = 1, GarmentGridName = "Bum Rush"},
            new GarmentGridNode {GarmentGridID = 2, GGOffset = 0x40, NodePosition = 2, GarmentGridName = "Bum Rush"},
            new GarmentGridNode {GarmentGridID = 2, GGOffset = 0x40, NodePosition = 3, GarmentGridName = "Bum Rush"},
            new GarmentGridNode {GarmentGridID = 2, GGOffset = 0x40, NodePosition = 8, GarmentGridName = "Bum Rush"},
            new GarmentGridNode {GarmentGridID = 3, GGOffset = 0x60, NodePosition = 0, GarmentGridName = "Undying Storm"},
            new GarmentGridNode {GarmentGridID = 3, GGOffset = 0x60, NodePosition = 1, GarmentGridName = "Undying Storm"},
            new GarmentGridNode {GarmentGridID = 3, GGOffset = 0x60, NodePosition = 2, GarmentGridName = "Undying Storm"},
            new GarmentGridNode {GarmentGridID = 3, GGOffset = 0x60, NodePosition = 3, GarmentGridName = "Undying Storm"},
            new GarmentGridNode {GarmentGridID = 3, GGOffset = 0x60, NodePosition = 8, GarmentGridName = "Undying Storm"},
            new GarmentGridNode {GarmentGridID = 4, GGOffset = 0x80, NodePosition = 0, GarmentGridName = "Flash of Steel"},
            new GarmentGridNode {GarmentGridID = 4, GGOffset = 0x80, NodePosition = 1, GarmentGridName = "Flash of Steel"},
            new GarmentGridNode {GarmentGridID = 4, GGOffset = 0x80, NodePosition = 2, GarmentGridName = "Flash of Steel"},
            new GarmentGridNode {GarmentGridID = 4, GGOffset = 0x80, NodePosition = 3, GarmentGridName = "Flash of Steel"},
            new GarmentGridNode {GarmentGridID = 4, GGOffset = 0x80, NodePosition = 8, GarmentGridName = "Flash of Steel"},
            new GarmentGridNode {GarmentGridID = 5, GGOffset = 0xA0, NodePosition = 0, GarmentGridName = "Protection Halo"},
            new GarmentGridNode {GarmentGridID = 5, GGOffset = 0xA0, NodePosition = 2, GarmentGridName = "Protection Halo"},
            new GarmentGridNode {GarmentGridID = 5, GGOffset = 0xA0, NodePosition = 4, GarmentGridName = "Protection Halo"},
            new GarmentGridNode {GarmentGridID = 5, GGOffset = 0xA0, NodePosition = 6, GarmentGridName = "Protection Halo"},
            new GarmentGridNode {GarmentGridID = 5, GGOffset = 0xA0, NodePosition = 8, GarmentGridName = "Protection Halo"},
            new GarmentGridNode {GarmentGridID = 6, GGOffset = 0xC0, NodePosition = 0, GarmentGridName = "Hour of Need"},
            new GarmentGridNode {GarmentGridID = 6, GGOffset = 0xC0, NodePosition = 2, GarmentGridName = "Hour of Need"},
            new GarmentGridNode {GarmentGridID = 6, GGOffset = 0xC0, NodePosition = 4, GarmentGridName = "Hour of Need"},
            new GarmentGridNode {GarmentGridID = 6, GGOffset = 0xC0, NodePosition = 6, GarmentGridName = "Hour of Need"},
            new GarmentGridNode {GarmentGridID = 6, GGOffset = 0xC0, NodePosition = 8, GarmentGridName = "Hour of Need"},
            new GarmentGridNode {GarmentGridID = 7, GGOffset = 0xE0, NodePosition = 0, GarmentGridName = "Unwavering Guard"},
            new GarmentGridNode {GarmentGridID = 7, GGOffset = 0xE0, NodePosition = 2, GarmentGridName = "Unwavering Guard"},
            new GarmentGridNode {GarmentGridID = 7, GGOffset = 0xE0, NodePosition = 4, GarmentGridName = "Unwavering Guard"},
            new GarmentGridNode {GarmentGridID = 7, GGOffset = 0xE0, NodePosition = 6, GarmentGridName = "Unwavering Guard"},
            new GarmentGridNode {GarmentGridID = 7, GGOffset = 0xE0, NodePosition = 8, GarmentGridName = "Unwavering Guard"},
            new GarmentGridNode {GarmentGridID = 8, GGOffset = 0x100, NodePosition = 0, GarmentGridName = "Valiant Lustre"},
            new GarmentGridNode {GarmentGridID = 8, GGOffset = 0x100, NodePosition = 2, GarmentGridName = "Valiant Lustre"},
            new GarmentGridNode {GarmentGridID = 8, GGOffset = 0x100, NodePosition = 4, GarmentGridName = "Valiant Lustre"},
            new GarmentGridNode {GarmentGridID = 8, GGOffset = 0x100, NodePosition = 6, GarmentGridName = "Valiant Lustre"},
            new GarmentGridNode {GarmentGridID = 8, GGOffset = 0x100, NodePosition = 8, GarmentGridName = "Valiant Lustre"},
            new GarmentGridNode {GarmentGridID = 9, GGOffset = 0x120, NodePosition = 0, GarmentGridName = "Highroad Winds"},
            new GarmentGridNode {GarmentGridID = 9, GGOffset = 0x120, NodePosition = 1, GarmentGridName = "Highroad Winds"},
            new GarmentGridNode {GarmentGridID = 9, GGOffset = 0x120, NodePosition = 2, GarmentGridName = "Highroad Winds"},
            new GarmentGridNode {GarmentGridID = 9, GGOffset = 0x120, NodePosition = 3, GarmentGridName = "Highroad Winds"},
            new GarmentGridNode {GarmentGridID = 10, GGOffset = 0x140, NodePosition = 0, GarmentGridName = "Mounted Assault"},
            new GarmentGridNode {GarmentGridID = 10, GGOffset = 0x140, NodePosition = 1, GarmentGridName = "Mounted Assault"},
            new GarmentGridNode {GarmentGridID = 10, GGOffset = 0x140, NodePosition = 2, GarmentGridName = "Mounted Assault"},
            new GarmentGridNode {GarmentGridID = 10, GGOffset = 0x140, NodePosition = 3, GarmentGridName = "Mounted Assault"},
            new GarmentGridNode {GarmentGridID = 11, GGOffset = 0x160, NodePosition = 0, GarmentGridName = "Heart of Flame"},
            new GarmentGridNode {GarmentGridID = 11, GGOffset = 0x160, NodePosition = 1, GarmentGridName = "Heart of Flame"},
            new GarmentGridNode {GarmentGridID = 11, GGOffset = 0x160, NodePosition = 2, GarmentGridName = "Heart of Flame"},
            new GarmentGridNode {GarmentGridID = 12, GGOffset = 0x180, NodePosition = 0, GarmentGridName = "Ice Queen"},
            new GarmentGridNode {GarmentGridID = 12, GGOffset = 0x180, NodePosition = 1, GarmentGridName = "Ice Queen"},
            new GarmentGridNode {GarmentGridID = 12, GGOffset = 0x180, NodePosition = 2, GarmentGridName = "Ice Queen"},
            new GarmentGridNode {GarmentGridID = 13, GGOffset = 0x1A0, NodePosition = 0, GarmentGridName = "Thunder Spawn"},
            new GarmentGridNode {GarmentGridID = 13, GGOffset = 0x1A0, NodePosition = 1, GarmentGridName = "Thunder Spawn"},
            new GarmentGridNode {GarmentGridID = 13, GGOffset = 0x1A0, NodePosition = 2, GarmentGridName = "Thunder Spawn"},
            new GarmentGridNode {GarmentGridID = 14, GGOffset = 0x1C0, NodePosition = 0, GarmentGridName = "Menace of The Deep"},
            new GarmentGridNode {GarmentGridID = 14, GGOffset = 0x1C0, NodePosition = 1, GarmentGridName = "Menace of The Deep"},
            new GarmentGridNode {GarmentGridID = 14, GGOffset = 0x1C0, NodePosition = 2, GarmentGridName = "Menace of The Deep"},
            new GarmentGridNode {GarmentGridID = 15, GGOffset = 0x1E0, NodePosition = 0, GarmentGridName = "Downtrodder"},
            new GarmentGridNode {GarmentGridID = 15, GGOffset = 0x1E0, NodePosition = 1, GarmentGridName = "Downtrodder"},
            new GarmentGridNode {GarmentGridID = 15, GGOffset = 0x1E0, NodePosition = 2, GarmentGridName = "Downtrodder"},
            new GarmentGridNode {GarmentGridID = 16, GGOffset = 0x200, NodePosition = 0, GarmentGridName = "Sacred Beast"},
            new GarmentGridNode {GarmentGridID = 16, GGOffset = 0x200, NodePosition = 2, GarmentGridName = "Sacred Beast"},
            new GarmentGridNode {GarmentGridID = 16, GGOffset = 0x200, NodePosition = 4, GarmentGridName = "Sacred Beast"},
            new GarmentGridNode {GarmentGridID = 16, GGOffset = 0x200, NodePosition = 6, GarmentGridName = "Sacred Beast"},
            new GarmentGridNode {GarmentGridID = 17, GGOffset = 0x220, NodePosition = 0, GarmentGridName = "Tetra Master"},
            new GarmentGridNode {GarmentGridID = 17, GGOffset = 0x220, NodePosition = 2, GarmentGridName = "Tetra Master"},
            new GarmentGridNode {GarmentGridID = 17, GGOffset = 0x220, NodePosition = 4, GarmentGridName = "Tetra Master"},
            new GarmentGridNode {GarmentGridID = 17, GGOffset = 0x220, NodePosition = 6, GarmentGridName = "Tetra Master"},
            new GarmentGridNode {GarmentGridID = 17, GGOffset = 0x220, NodePosition = 8, GarmentGridName = "Tetra Master"},
            new GarmentGridNode {GarmentGridID = 18, GGOffset = 0x240, NodePosition = 0, GarmentGridName = "Restless Sleep"},
            new GarmentGridNode {GarmentGridID = 18, GGOffset = 0x240, NodePosition = 2, GarmentGridName = "Restless Sleep"},
            new GarmentGridNode {GarmentGridID = 18, GGOffset = 0x240, NodePosition = 4, GarmentGridName = "Restless Sleep"},
            new GarmentGridNode {GarmentGridID = 18, GGOffset = 0x240, NodePosition = 6, GarmentGridName = "Restless Sleep"},
            new GarmentGridNode {GarmentGridID = 18, GGOffset = 0x240, NodePosition = 8, GarmentGridName = "Restless Sleep"},
            new GarmentGridNode {GarmentGridID = 19, GGOffset = 0x260, NodePosition = 0, GarmentGridName = "Still of Night"},
            new GarmentGridNode {GarmentGridID = 19, GGOffset = 0x260, NodePosition = 2, GarmentGridName = "Still of Night"},
            new GarmentGridNode {GarmentGridID = 19, GGOffset = 0x260, NodePosition = 4, GarmentGridName = "Still of Night"},
            new GarmentGridNode {GarmentGridID = 19, GGOffset = 0x260, NodePosition = 6, GarmentGridName = "Still of Night"},
            new GarmentGridNode {GarmentGridID = 19, GGOffset = 0x260, NodePosition = 8, GarmentGridName = "Still of Night"},
            new GarmentGridNode {GarmentGridID = 20, GGOffset = 0x280, NodePosition = 0, GarmentGridName = "Mortal Coil"},
            new GarmentGridNode {GarmentGridID = 20, GGOffset = 0x280, NodePosition = 2, GarmentGridName = "Mortal Coil"},
            new GarmentGridNode {GarmentGridID = 20, GGOffset = 0x280, NodePosition = 4, GarmentGridName = "Mortal Coil"},
            new GarmentGridNode {GarmentGridID = 20, GGOffset = 0x280, NodePosition = 6, GarmentGridName = "Mortal Coil"},
            new GarmentGridNode {GarmentGridID = 20, GGOffset = 0x280, NodePosition = 8, GarmentGridName = "Mortal Coil"},
            new GarmentGridNode {GarmentGridID = 21, GGOffset = 0x2A0, NodePosition = 0, GarmentGridName = "Racing Giant"},
            new GarmentGridNode {GarmentGridID = 21, GGOffset = 0x2A0, NodePosition = 2, GarmentGridName = "Racing Giant"},
            new GarmentGridNode {GarmentGridID = 21, GGOffset = 0x2A0, NodePosition = 4, GarmentGridName = "Racing Giant"},
            new GarmentGridNode {GarmentGridID = 21, GGOffset = 0x2A0, NodePosition = 6, GarmentGridName = "Racing Giant"},
            new GarmentGridNode {GarmentGridID = 21, GGOffset = 0x2A0, NodePosition = 8, GarmentGridName = "Racing Giant"},
            new GarmentGridNode {GarmentGridID = 22, GGOffset = 0x2C0, NodePosition = 0, GarmentGridName = "Bitter Farewell"},
            new GarmentGridNode {GarmentGridID = 22, GGOffset = 0x2C0, NodePosition = 2, GarmentGridName = "Bitter Farewell"},
            new GarmentGridNode {GarmentGridID = 22, GGOffset = 0x2C0, NodePosition = 4, GarmentGridName = "Bitter Farewell"},
            new GarmentGridNode {GarmentGridID = 22, GGOffset = 0x2C0, NodePosition = 6, GarmentGridName = "Bitter Farewell"},
            new GarmentGridNode {GarmentGridID = 22, GGOffset = 0x2C0, NodePosition = 8, GarmentGridName = "Bitter Farewell"},
            new GarmentGridNode {GarmentGridID = 23, GGOffset = 0x2E0, NodePosition = 1, GarmentGridName = "Selene Guard"},
            new GarmentGridNode {GarmentGridID = 23, GGOffset = 0x2E0, NodePosition = 2, GarmentGridName = "Selene Guard"},
            new GarmentGridNode {GarmentGridID = 23, GGOffset = 0x2E0, NodePosition = 3, GarmentGridName = "Selene Guard"},
            new GarmentGridNode {GarmentGridID = 23, GGOffset = 0x2E0, NodePosition = 4, GarmentGridName = "Selene Guard"},
            new GarmentGridNode {GarmentGridID = 24, GGOffset = 0x300, NodePosition = 1, GarmentGridName = "Helios Guard"},
            new GarmentGridNode {GarmentGridID = 24, GGOffset = 0x300, NodePosition = 2, GarmentGridName = "Helios Guard"},
            new GarmentGridNode {GarmentGridID = 24, GGOffset = 0x300, NodePosition = 3, GarmentGridName = "Helios Guard"},
            new GarmentGridNode {GarmentGridID = 24, GGOffset = 0x300, NodePosition = 4, GarmentGridName = "Helios Guard"},
            new GarmentGridNode {GarmentGridID = 25, GGOffset = 0x320, NodePosition = 1, GarmentGridName = "Shining Mirror"},
            new GarmentGridNode {GarmentGridID = 25, GGOffset = 0x320, NodePosition = 2, GarmentGridName = "Shining Mirror"},
            new GarmentGridNode {GarmentGridID = 25, GGOffset = 0x320, NodePosition = 3, GarmentGridName = "Shining Mirror"},
            new GarmentGridNode {GarmentGridID = 25, GGOffset = 0x320, NodePosition = 4, GarmentGridName = "Shining Mirror"},
            new GarmentGridNode {GarmentGridID = 26, GGOffset = 0x340, NodePosition = 0, GarmentGridName = "Covetous"},
            new GarmentGridNode {GarmentGridID = 26, GGOffset = 0x340, NodePosition = 1, GarmentGridName = "Covetous"},
            new GarmentGridNode {GarmentGridID = 26, GGOffset = 0x340, NodePosition = 2, GarmentGridName = "Covetous"},
            new GarmentGridNode {GarmentGridID = 27, GGOffset = 0x360, NodePosition = 2, GarmentGridName = "Disaster in Bloom"},
            new GarmentGridNode {GarmentGridID = 27, GGOffset = 0x360, NodePosition = 3, GarmentGridName = "Disaster in Bloom"},
            new GarmentGridNode {GarmentGridID = 27, GGOffset = 0x360, NodePosition = 4, GarmentGridName = "Disaster in Bloom"},
            new GarmentGridNode {GarmentGridID = 27, GGOffset = 0x360, NodePosition = 5, GarmentGridName = "Disaster in Bloom"},
            new GarmentGridNode {GarmentGridID = 27, GGOffset = 0x360, NodePosition = 8, GarmentGridName = "Disaster in Bloom"},
            new GarmentGridNode {GarmentGridID = 28, GGOffset = 0x380, NodePosition = 2, GarmentGridName = "Scourgebane"},
            new GarmentGridNode {GarmentGridID = 28, GGOffset = 0x380, NodePosition = 3, GarmentGridName = "Scourgebane"},
            new GarmentGridNode {GarmentGridID = 28, GGOffset = 0x380, NodePosition = 4, GarmentGridName = "Scourgebane"},
            new GarmentGridNode {GarmentGridID = 28, GGOffset = 0x380, NodePosition = 5, GarmentGridName = "Scourgebane"},
            new GarmentGridNode {GarmentGridID = 28, GGOffset = 0x380, NodePosition = 8, GarmentGridName = "Scourgebane"},
            new GarmentGridNode {GarmentGridID = 29, GGOffset = 0x3A0, NodePosition = 0, GarmentGridName = "Healing Wind"},
            new GarmentGridNode {GarmentGridID = 29, GGOffset = 0x3A0, NodePosition = 2, GarmentGridName = "Healing Wind"},
            new GarmentGridNode {GarmentGridID = 29, GGOffset = 0x3A0, NodePosition = 4, GarmentGridName = "Healing Wind"},
            new GarmentGridNode {GarmentGridID = 30, GGOffset = 0x3C0, NodePosition = 0, GarmentGridName = "Heart Reborn"},
            new GarmentGridNode {GarmentGridID = 30, GGOffset = 0x3C0, NodePosition = 1, GarmentGridName = "Heart Reborn"},
            new GarmentGridNode {GarmentGridID = 30, GGOffset = 0x3C0, NodePosition = 3, GarmentGridName = "Heart Reborn"},
            new GarmentGridNode {GarmentGridID = 31, GGOffset = 0x3E0, NodePosition = 0, GarmentGridName = "Healing Light"},
            new GarmentGridNode {GarmentGridID = 31, GGOffset = 0x3E0, NodePosition = 3, GarmentGridName = "Healing Light"},
            new GarmentGridNode {GarmentGridID = 31, GGOffset = 0x3E0, NodePosition = 4, GarmentGridName = "Healing Light"},
            new GarmentGridNode {GarmentGridID = 31, GGOffset = 0x3E0, NodePosition = 5, GarmentGridName = "Healing Light"},
            new GarmentGridNode {GarmentGridID = 32, GGOffset = 0x400, NodePosition = 0, GarmentGridName = "Immortal Soul"},
            new GarmentGridNode {GarmentGridID = 32, GGOffset = 0x400, NodePosition = 3, GarmentGridName = "Immortal Soul"},
            new GarmentGridNode {GarmentGridID = 32, GGOffset = 0x400, NodePosition = 5, GarmentGridName = "Immortal Soul"},
            new GarmentGridNode {GarmentGridID = 32, GGOffset = 0x400, NodePosition = 6, GarmentGridName = "Immortal Soul"},
            new GarmentGridNode {GarmentGridID = 33, GGOffset = 0x420, NodePosition = 0, GarmentGridName = "Wish Bringer"},
            new GarmentGridNode {GarmentGridID = 33, GGOffset = 0x420, NodePosition = 3, GarmentGridName = "Wish Bringer"},
            new GarmentGridNode {GarmentGridID = 33, GGOffset = 0x420, NodePosition = 4, GarmentGridName = "Wish Bringer"},
            new GarmentGridNode {GarmentGridID = 33, GGOffset = 0x420, NodePosition = 5, GarmentGridName = "Wish Bringer"},
            new GarmentGridNode {GarmentGridID = 33, GGOffset = 0x420, NodePosition = 6, GarmentGridName = "Wish Bringer"},
            new GarmentGridNode {GarmentGridID = 34, GGOffset = 0x440, NodePosition = 1, GarmentGridName = "Strength of One"},
            new GarmentGridNode {GarmentGridID = 34, GGOffset = 0x440, NodePosition = 3, GarmentGridName = "Strength of One"},
            new GarmentGridNode {GarmentGridID = 34, GGOffset = 0x440, NodePosition = 5, GarmentGridName = "Strength of One"},
            new GarmentGridNode {GarmentGridID = 34, GGOffset = 0x440, NodePosition = 7, GarmentGridName = "Strength of One"},
            new GarmentGridNode {GarmentGridID = 35, GGOffset = 0x460, NodePosition = 1, GarmentGridName = "Seething Cauldron"},
            new GarmentGridNode {GarmentGridID = 35, GGOffset = 0x460, NodePosition = 3, GarmentGridName = "Seething Cauldron"},
            new GarmentGridNode {GarmentGridID = 35, GGOffset = 0x460, NodePosition = 5, GarmentGridName = "Seething Cauldron"},
            new GarmentGridNode {GarmentGridID = 35, GGOffset = 0x460, NodePosition = 7, GarmentGridName = "Seething Cauldron"},
            new GarmentGridNode {GarmentGridID = 36, GGOffset = 0x480, NodePosition = 1, GarmentGridName = "Stonehewn"},
            new GarmentGridNode {GarmentGridID = 36, GGOffset = 0x480, NodePosition = 3, GarmentGridName = "Stonehewn"},
            new GarmentGridNode {GarmentGridID = 36, GGOffset = 0x480, NodePosition = 5, GarmentGridName = "Stonehewn"},
            new GarmentGridNode {GarmentGridID = 36, GGOffset = 0x480, NodePosition = 7, GarmentGridName = "Stonehewn"},
            new GarmentGridNode {GarmentGridID = 37, GGOffset = 0x4A0, NodePosition = 1, GarmentGridName = "Enigma Plate"},
            new GarmentGridNode {GarmentGridID = 37, GGOffset = 0x4A0, NodePosition = 3, GarmentGridName = "Enigma Plate"},
            new GarmentGridNode {GarmentGridID = 37, GGOffset = 0x4A0, NodePosition = 5, GarmentGridName = "Enigma Plate"},
            new GarmentGridNode {GarmentGridID = 37, GGOffset = 0x4A0, NodePosition = 7, GarmentGridName = "Enigma Plate"},
            new GarmentGridNode {GarmentGridID = 38, GGOffset = 0x4C0, NodePosition = 1, GarmentGridName = "Howling Wind"},
            new GarmentGridNode {GarmentGridID = 38, GGOffset = 0x4C0, NodePosition = 3, GarmentGridName = "Howling Wind"},
            new GarmentGridNode {GarmentGridID = 38, GGOffset = 0x4C0, NodePosition = 5, GarmentGridName = "Howling Wind"},
            new GarmentGridNode {GarmentGridID = 38, GGOffset = 0x4C0, NodePosition = 7, GarmentGridName = "Howling Wind"},
            new GarmentGridNode {GarmentGridID = 39, GGOffset = 0x4E0, NodePosition = 1, GarmentGridName = "Ray of Hope"},
            new GarmentGridNode {GarmentGridID = 39, GGOffset = 0x4E0, NodePosition = 3, GarmentGridName = "Ray of Hope"},
            new GarmentGridNode {GarmentGridID = 39, GGOffset = 0x4E0, NodePosition = 6, GarmentGridName = "Ray of Hope"},
            new GarmentGridNode {GarmentGridID = 39, GGOffset = 0x4E0, NodePosition = 7, GarmentGridName = "Ray of Hope"},
            new GarmentGridNode {GarmentGridID = 39, GGOffset = 0x4E0, NodePosition = 8, GarmentGridName = "Ray of Hope"},
            new GarmentGridNode {GarmentGridID = 39, GGOffset = 0x4E0, NodePosition = 9, GarmentGridName = "Ray of Hope"},
            new GarmentGridNode {GarmentGridID = 40, GGOffset = 0x500, NodePosition = 0, GarmentGridName = "Pride of the Sword"},
            new GarmentGridNode {GarmentGridID = 40, GGOffset = 0x500, NodePosition = 1, GarmentGridName = "Pride of the Sword"},
            new GarmentGridNode {GarmentGridID = 40, GGOffset = 0x500, NodePosition = 4, GarmentGridName = "Pride of the Sword"},
            new GarmentGridNode {GarmentGridID = 40, GGOffset = 0x500, NodePosition = 5, GarmentGridName = "Pride of the Sword"},
            new GarmentGridNode {GarmentGridID = 40, GGOffset = 0x500, NodePosition = 6, GarmentGridName = "Pride of the Sword"},
            new GarmentGridNode {GarmentGridID = 40, GGOffset = 0x500, NodePosition = 7, GarmentGridName = "Pride of the Sword"},
            new GarmentGridNode {GarmentGridID = 41, GGOffset = 0x520, NodePosition = 0, GarmentGridName = "Samurai's Honor"},
            new GarmentGridNode {GarmentGridID = 41, GGOffset = 0x520, NodePosition = 1, GarmentGridName = "Samurai's Honor"},
            new GarmentGridNode {GarmentGridID = 41, GGOffset = 0x520, NodePosition = 4, GarmentGridName = "Samurai's Honor"},
            new GarmentGridNode {GarmentGridID = 41, GGOffset = 0x520, NodePosition = 5, GarmentGridName = "Samurai's Honor"},
            new GarmentGridNode {GarmentGridID = 41, GGOffset = 0x520, NodePosition = 6, GarmentGridName = "Samurai's Honor"},
            new GarmentGridNode {GarmentGridID = 41, GGOffset = 0x520, NodePosition = 7, GarmentGridName = "Samurai's Honor"},
            new GarmentGridNode {GarmentGridID = 42, GGOffset = 0x540, NodePosition = 0, GarmentGridName = "Blood of the Beast"},
            new GarmentGridNode {GarmentGridID = 42, GGOffset = 0x540, NodePosition = 1, GarmentGridName = "Blood of the Beast"},
            new GarmentGridNode {GarmentGridID = 42, GGOffset = 0x540, NodePosition = 4, GarmentGridName = "Blood of the Beast"},
            new GarmentGridNode {GarmentGridID = 42, GGOffset = 0x540, NodePosition = 5, GarmentGridName = "Blood of the Beast"},
            new GarmentGridNode {GarmentGridID = 42, GGOffset = 0x540, NodePosition = 6, GarmentGridName = "Blood of the Beast"},
            new GarmentGridNode {GarmentGridID = 42, GGOffset = 0x540, NodePosition = 7, GarmentGridName = "Blood of the Beast"},
            new GarmentGridNode {GarmentGridID = 43, GGOffset = 0x560, NodePosition = 0, GarmentGridName = "Chaos Maelstrom"},
            new GarmentGridNode {GarmentGridID = 43, GGOffset = 0x560, NodePosition = 2, GarmentGridName = "Chaos Maelstrom"},
            new GarmentGridNode {GarmentGridID = 43, GGOffset = 0x560, NodePosition = 4, GarmentGridName = "Chaos Maelstrom"},
            new GarmentGridNode {GarmentGridID = 43, GGOffset = 0x560, NodePosition = 6, GarmentGridName = "Chaos Maelstrom"},
            new GarmentGridNode {GarmentGridID = 43, GGOffset = 0x560, NodePosition = 8, GarmentGridName = "Chaos Maelstrom"},
            new GarmentGridNode {GarmentGridID = 43, GGOffset = 0x560, NodePosition = 9, GarmentGridName = "Chaos Maelstrom"},
            new GarmentGridNode {GarmentGridID = 44, GGOffset = 0x580, NodePosition = 0, GarmentGridName = "White Signet"},
            new GarmentGridNode {GarmentGridID = 44, GGOffset = 0x580, NodePosition = 2, GarmentGridName = "White Signet"},
            new GarmentGridNode {GarmentGridID = 44, GGOffset = 0x580, NodePosition = 4, GarmentGridName = "White Signet"},
            new GarmentGridNode {GarmentGridID = 44, GGOffset = 0x580, NodePosition = 6, GarmentGridName = "White Signet"},
            new GarmentGridNode {GarmentGridID = 44, GGOffset = 0x580, NodePosition = 8, GarmentGridName = "White Signet"},
            new GarmentGridNode {GarmentGridID = 44, GGOffset = 0x580, NodePosition = 9, GarmentGridName = "White Signet"},
            new GarmentGridNode {GarmentGridID = 45, GGOffset = 0x5A0, NodePosition = 0, GarmentGridName = "Black Tabard"},
            new GarmentGridNode {GarmentGridID = 45, GGOffset = 0x5A0, NodePosition = 2, GarmentGridName = "Black Tabard"},
            new GarmentGridNode {GarmentGridID = 45, GGOffset = 0x5A0, NodePosition = 4, GarmentGridName = "Black Tabard"},
            new GarmentGridNode {GarmentGridID = 45, GGOffset = 0x5A0, NodePosition = 6, GarmentGridName = "Black Tabard"},
            new GarmentGridNode {GarmentGridID = 45, GGOffset = 0x5A0, NodePosition = 8, GarmentGridName = "Black Tabard"},
            new GarmentGridNode {GarmentGridID = 45, GGOffset = 0x5A0, NodePosition = 9, GarmentGridName = "Black Tabard"},
            new GarmentGridNode {GarmentGridID = 46, GGOffset = 0x5C0, NodePosition = 0, GarmentGridName = "Mercurial Strike"},
            new GarmentGridNode {GarmentGridID = 46, GGOffset = 0x5C0, NodePosition = 1, GarmentGridName = "Mercurial Strike"},
            new GarmentGridNode {GarmentGridID = 46, GGOffset = 0x5C0, NodePosition = 2, GarmentGridName = "Mercurial Strike"},
            new GarmentGridNode {GarmentGridID = 46, GGOffset = 0x5C0, NodePosition = 3, GarmentGridName = "Mercurial Strike"},
            new GarmentGridNode {GarmentGridID = 46, GGOffset = 0x5C0, NodePosition = 6, GarmentGridName = "Mercurial Strike"},
            new GarmentGridNode {GarmentGridID = 46, GGOffset = 0x5C0, NodePosition = 8, GarmentGridName = "Mercurial Strike"},
            new GarmentGridNode {GarmentGridID = 47, GGOffset = 0x5E0, NodePosition = 0, GarmentGridName = "Tricks of the Trade"},
            new GarmentGridNode {GarmentGridID = 47, GGOffset = 0x5E0, NodePosition = 1, GarmentGridName = "Tricks of the Trade"},
            new GarmentGridNode {GarmentGridID = 47, GGOffset = 0x5E0, NodePosition = 2, GarmentGridName = "Tricks of the Trade"},
            new GarmentGridNode {GarmentGridID = 47, GGOffset = 0x5E0, NodePosition = 3, GarmentGridName = "Tricks of the Trade"},
            new GarmentGridNode {GarmentGridID = 47, GGOffset = 0x5E0, NodePosition = 4, GarmentGridName = "Tricks of the Trade"},
            new GarmentGridNode {GarmentGridID = 47, GGOffset = 0x5E0, NodePosition = 6, GarmentGridName = "Tricks of the Trade"},
            new GarmentGridNode {GarmentGridID = 48, GGOffset = 0x600, NodePosition = 0, GarmentGridName = "Horn of Penalty"},
            new GarmentGridNode {GarmentGridID = 48, GGOffset = 0x600, NodePosition = 1, GarmentGridName = "Horn of Penalty"},
            new GarmentGridNode {GarmentGridID = 48, GGOffset = 0x600, NodePosition = 2, GarmentGridName = "Horn of Penalty"},
            new GarmentGridNode {GarmentGridID = 48, GGOffset = 0x600, NodePosition = 3, GarmentGridName = "Horn of Penalty"},
            new GarmentGridNode {GarmentGridID = 48, GGOffset = 0x600, NodePosition = 4, GarmentGridName = "Horn of Penalty"},
            new GarmentGridNode {GarmentGridID = 49, GGOffset = 0x620, NodePosition = 0, GarmentGridName = "Tresure Hunt"},
            new GarmentGridNode {GarmentGridID = 49, GGOffset = 0x620, NodePosition = 1, GarmentGridName = "Tresure Hunt"},
            new GarmentGridNode {GarmentGridID = 49, GGOffset = 0x620, NodePosition = 2, GarmentGridName = "Tresure Hunt"},
            new GarmentGridNode {GarmentGridID = 49, GGOffset = 0x620, NodePosition = 3, GarmentGridName = "Tresure Hunt"},
            new GarmentGridNode {GarmentGridID = 49, GGOffset = 0x620, NodePosition = 4, GarmentGridName = "Tresure Hunt"},
            new GarmentGridNode {GarmentGridID = 50, GGOffset = 0x640, NodePosition = 1, GarmentGridName = "Temperd Will"},
            new GarmentGridNode {GarmentGridID = 50, GGOffset = 0x640, NodePosition = 2, GarmentGridName = "Temperd Will"},
            new GarmentGridNode {GarmentGridID = 50, GGOffset = 0x640, NodePosition = 3, GarmentGridName = "Temperd Will"},
            new GarmentGridNode {GarmentGridID = 50, GGOffset = 0x640, NodePosition = 4, GarmentGridName = "Temperd Will"},
            new GarmentGridNode {GarmentGridID = 50, GGOffset = 0x640, NodePosition = 5, GarmentGridName = "Temperd Will"},
            new GarmentGridNode {GarmentGridID = 51, GGOffset = 0x660, NodePosition = 0, GarmentGridName = "Covenant of Growth"},
            new GarmentGridNode {GarmentGridID = 51, GGOffset = 0x660, NodePosition = 1, GarmentGridName = "Covenant of Growth"},
            new GarmentGridNode {GarmentGridID = 51, GGOffset = 0x660, NodePosition = 2, GarmentGridName = "Covenant of Growth"},
            new GarmentGridNode {GarmentGridID = 51, GGOffset = 0x660, NodePosition = 3, GarmentGridName = "Covenant of Growth"},
            new GarmentGridNode {GarmentGridID = 51, GGOffset = 0x660, NodePosition = 4, GarmentGridName = "Covenant of Growth"},
            new GarmentGridNode {GarmentGridID = 52, GGOffset = 0x680, NodePosition = 0, GarmentGridName = "Salvation Promised"},
            new GarmentGridNode {GarmentGridID = 52, GGOffset = 0x680, NodePosition = 2, GarmentGridName = "Salvation Promised"},
            new GarmentGridNode {GarmentGridID = 52, GGOffset = 0x680, NodePosition = 4, GarmentGridName = "Salvation Promised"},
            new GarmentGridNode {GarmentGridID = 52, GGOffset = 0x680, NodePosition = 5, GarmentGridName = "Salvation Promised"},
            new GarmentGridNode {GarmentGridID = 53, GGOffset = 0x6A0, NodePosition = 1, GarmentGridName = "Conflagration"},
            new GarmentGridNode {GarmentGridID = 53, GGOffset = 0x6A0, NodePosition = 2, GarmentGridName = "Conflagration"},
            new GarmentGridNode {GarmentGridID = 53, GGOffset = 0x6A0, NodePosition = 3, GarmentGridName = "Conflagration"},
            new GarmentGridNode {GarmentGridID = 53, GGOffset = 0x6A0, NodePosition = 6, GarmentGridName = "Conflagration"},
            new GarmentGridNode {GarmentGridID = 54, GGOffset = 0x6C0, NodePosition = 1, GarmentGridName = "Supreme Light"},
            new GarmentGridNode {GarmentGridID = 54, GGOffset = 0x6C0, NodePosition = 2, GarmentGridName = "Supreme Light"},
            new GarmentGridNode {GarmentGridID = 54, GGOffset = 0x6C0, NodePosition = 3, GarmentGridName = "Supreme Light"},
            new GarmentGridNode {GarmentGridID = 54, GGOffset = 0x6C0, NodePosition = 4, GarmentGridName = "Supreme Light"},
            new GarmentGridNode {GarmentGridID = 54, GGOffset = 0x6C0, NodePosition = 5, GarmentGridName = "Supreme Light"},
            new GarmentGridNode {GarmentGridID = 55, GGOffset = 0x6E0, NodePosition = 2, GarmentGridName = "Megiddo"},
            new GarmentGridNode {GarmentGridID = 55, GGOffset = 0x6E0, NodePosition = 3, GarmentGridName = "Megiddo"},
            new GarmentGridNode {GarmentGridID = 55, GGOffset = 0x6E0, NodePosition = 4, GarmentGridName = "Megiddo"},
            new GarmentGridNode {GarmentGridID = 55, GGOffset = 0x6E0, NodePosition = 5, GarmentGridName = "Megiddo"},
            new GarmentGridNode {GarmentGridID = 55, GGOffset = 0x6E0, NodePosition = 7, GarmentGridName = "Megiddo"},
            new GarmentGridNode {GarmentGridID = 56, GGOffset = 0x700, NodePosition = 0, GarmentGridName = "Unerring Path"},
            new GarmentGridNode {GarmentGridID = 56, GGOffset = 0x700, NodePosition = 1, GarmentGridName = "Unerring Path"},
            new GarmentGridNode {GarmentGridID = 57, GGOffset = 0x720, NodePosition = 1, GarmentGridName = "Font of Power"},
            new GarmentGridNode {GarmentGridID = 57, GGOffset = 0x720, NodePosition = 4, GarmentGridName = "Font of Power"},
            new GarmentGridNode {GarmentGridID = 57, GGOffset = 0x720, NodePosition = 5, GarmentGridName = "Font of Power"},
            new GarmentGridNode {GarmentGridID = 57, GGOffset = 0x720, NodePosition = 6, GarmentGridName = "Font of Power"},
            new GarmentGridNode {GarmentGridID = 58, GGOffset = 0x740, NodePosition = 0, GarmentGridName = "Higher Power"},
            new GarmentGridNode {GarmentGridID = 58, GGOffset = 0x740, NodePosition = 2, GarmentGridName = "Higher Power"},
            new GarmentGridNode {GarmentGridID = 58, GGOffset = 0x740, NodePosition = 4, GarmentGridName = "Higher Power"},
            new GarmentGridNode {GarmentGridID = 58, GGOffset = 0x740, NodePosition = 6, GarmentGridName = "Higher Power"},
            new GarmentGridNode {GarmentGridID = 58, GGOffset = 0x740, NodePosition = 8, GarmentGridName = "Higher Power"},
            new GarmentGridNode {GarmentGridID = 59, GGOffset = 0x760, NodePosition = 0, GarmentGridName = "The End"},
            new GarmentGridNode {GarmentGridID = 59, GGOffset = 0x760, NodePosition = 1, GarmentGridName = "The End"},
            new GarmentGridNode {GarmentGridID = 59, GGOffset = 0x760, NodePosition = 2, GarmentGridName = "The End"},
            new GarmentGridNode {GarmentGridID = 59, GGOffset = 0x760, NodePosition = 3, GarmentGridName = "The End"},
            new GarmentGridNode {GarmentGridID = 59, GGOffset = 0x760, NodePosition = 8, GarmentGridName = "The End"},
            new GarmentGridNode {GarmentGridID = 60, GGOffset = 0x780, NodePosition = 0, GarmentGridName = "Intrepid"},
            new GarmentGridNode {GarmentGridID = 60, GGOffset = 0x780, NodePosition = 3, GarmentGridName = "Intrepid"},
            new GarmentGridNode {GarmentGridID = 60, GGOffset = 0x780, NodePosition = 4, GarmentGridName = "Intrepid"},
            new GarmentGridNode {GarmentGridID = 61, GGOffset = 0x7A0, NodePosition = 0, GarmentGridName = "Abominable"},
            new GarmentGridNode {GarmentGridID = 61, GGOffset = 0x7A0, NodePosition = 1, GarmentGridName = "Abominable"},
            new GarmentGridNode {GarmentGridID = 61, GGOffset = 0x7A0, NodePosition = 2, GarmentGridName = "Abominable"},
            new GarmentGridNode {GarmentGridID = 61, GGOffset = 0x7A0, NodePosition = 3, GarmentGridName = "Abominable"},
            new GarmentGridNode {GarmentGridID = 61, GGOffset = 0x7A0, NodePosition = 4, GarmentGridName = "Abominable"},
            new GarmentGridNode {GarmentGridID = 62, GGOffset = 0x7C0, NodePosition = 0, GarmentGridName = "Peerless"},
            new GarmentGridNode {GarmentGridID = 62, GGOffset = 0x7C0, NodePosition = 2, GarmentGridName = "Peerless"},
            new GarmentGridNode {GarmentGridID = 62, GGOffset = 0x7C0, NodePosition = 4, GarmentGridName = "Peerless"},
            new GarmentGridNode {GarmentGridID = 62, GGOffset = 0x7C0, NodePosition = 6, GarmentGridName = "Peerless"},
            new GarmentGridNode {GarmentGridID = 63, GGOffset = 0x7E0, NodePosition = 0, GarmentGridName = "Last Resort"},
            new GarmentGridNode {GarmentGridID = 63, GGOffset = 0x7E0, NodePosition = 2, GarmentGridName = "Last Resort"},
            new GarmentGridNode {GarmentGridID = 63, GGOffset = 0x7E0, NodePosition = 4, GarmentGridName = "Last Resort"},
            new GarmentGridNode {GarmentGridID = 63, GGOffset = 0x7E0, NodePosition = 6, GarmentGridName = "Last Resort"},
            new GarmentGridNode {GarmentGridID = 63, GGOffset = 0x7E0, NodePosition = 8, GarmentGridName = "Last Resort"},
        };

    }

    public class GarmentGridNode
    {
        public int GarmentGridID { get; set; }
        public int GGOffset { get; set; }
        public int NodePosition { get; set; }
        public string GarmentGridName { get; set; }
    }
}
